      const phrases = ['Lions',
 'The Golden Altar',
 'Education',
 'Art',
 'Deserts',
 'Birds',
 'Idolatry',
 'Mercy',
 'Eagles',
 'King Saul',
 'Minhag',
 'Beit El',
 'Mental Health',
 'Sin of Peor',
 'Ephraim',
 'HaSharon',
 'Sefirat HaOmer',
 'Racism',
 'Second Temple',
 'Letters',
 'Gemorrah',
 'God',
 'Heavens',
 'Shemaiah',
 'National Library of Israel',
 'Bullying',
 'The Land of Judah',
 'Lot',
 'Michael',
 'Rosh Hashanah',
 'Abortion',
 'Oxen',
 'Extra Soul',
 'Man and Wife',
 'Mother',
 'The Idol of Micha',
 'Netilat Yadayim',
 'Blessing of Levi',
 'Winds',
 'Particularism',
 'Pigs',
 'The Throne of Glory',
 'Hate',
 'Tallit',
 'Theodicy',
 'Edom',
 'Shaliach Tsibur',
 'Folklore',
 'Holiness',
 'Dan',
 'Ethics',
 'Sustainability',
 "The Hardening of Pharaoh's Heart",
 'Mount Sinai',
 "Pharaoh's Daughter",
 'Horses',
 'Questions',
 'Ulla',
 'The Spies',
 'Truth',
 'Rabbi Yehoshua b. Levi',
 "Noah's Sacrifice",
 'Empathy',
 'Oppression',
 'Rabban Gamliel of Yavneh (II)',
 'Myrtles',
 'Daniel',
 'Esau',
 'Partnership',
 'Hashkiveinu',
 'Workers',
 '[Shimon] b. Zoma',
 'Metatron',
 'Daughters of Tzelofchad',
 'Shemoneh Esrei',
 'Conversion',
 'Chasidut',
 'Sigd',
 'Devekut',
 'Hope',
 'Mountains',
 'Rabbi Eliezer b. Hyrcanus',
 'The Tablets',
 'Rav Ashi',
 'Impulses',
 'Rabban Yochanan b. Zakkai',
 'Figs',
 'Love Your Neighbor as Yourself',
 'Moses',
 'Dances',
 'Colors',
 'Calendar',
 'Prophecy',
 'Blessings (Halakhah)',
 'Renewal',
 'Music',
 'Midrash',
 'War with Amalek',
 'Worms',
 'Ruach Hakodesh',
 'En Dor',
 'Good',
 'Purpose of Life',
 'Plague of Wild Animals',
 'Tests of Abraham',
 'Faith',
 'Independence',
 'Crossing the Jordan River and Setting of the Stones',
 'Converts',
 'Mount Gerizim and Mount Ebal',
 'Raising Up and Anointing the Tabernacle',
 'Four Questions',
 'Shimon b. Shetach',
 'Abraham and the Kings',
 'Slaves',
 'Eruv',
 'Tashlich',
 'Midian',
 'Humility',
 'Weather',
 'Plague of Boils',
 'Appointment of Judges for The Generation of the Desert',
 'Shemini Atzeret',
 'The Worship of Molech',
 'Maror',
 'Baseless Hatred',
 'Mashiach',
 'Vows',
 'Adoniah',
 'Temple Mount',
 'Leadership',
 'Plague of Blood',
 'Non Jews',
 'Diversity',
 'Keturah',
 'Shifrah and Puah',
 'Wine',
 'The Promise to Jacob',
 'Amalek',
 'Moses and Israel',
 'Kings',
 'Abraham in Egypt',
 'Sacrifices in the Desert',
 'Shekhinah',
 'Ezekiel',
 'Spices',
 'Snow',
 'Ecology',
 'Shabbat',
 'Ever HaYarden',
 'Nachshon Ben Aminadav',
 'Destruction of Babylonia',
 'Hillel',
 'Nehemiah',
 'Management',
 'Goliath',
 "Tabernacle's Journey",
 'Listening',
 'Alacrity',
 'Teshuvah',
 'Gechazi',
 'The Ocean',
 'Machloket',
 'Tower of Babel',
 'Temple Vessels',
 "God's Existence",
 'Lilies',
 'Generation of the Flood',
 'Inauguration of the Temple',
 'Lulav',
 'The Effects of a Commandment',
 'The Sons of Eli',
 'Alexandria',
 'Gardening',
 'Money',
 "Joseph's Blessing",
 'Uzziah',
 'Fish',
 'Generation of the Desert',
 'Heretics',
 'The Book of Ruth',
 'Students',
 'Growth',
 'Modesty',
 'Science',
 'Elul',
 'Cities',
 'Deceit',
 'Fear (פחד)',
 'Chayot',
 'Libations',
 'Knowing God',
 'The Tree of Life',
 'Cats',
 'Demons',
 'Gehinnom',
 'Liberation',
 'Kavanah',
 'Authority',
 'Tikkun',
 'The Four Kingdoms',
 'Fire',
 'Wealth',
 'Shammai',
 'Satan',
 'Rav Zera',
 'Sarah',
 'Wheat',
 'Plague of Hail',
 'Cities of Refuge',
 'Asarah BeTevet',
 'Tzaddik',
 'Aleinu',
 'Outside of Israel',
 "Tisha B'Av",
 'Jonadab, the Son of Rechab',
 'Aram',
 'Blessings',
 'The Curtain',
 'Feminism',
 'Jubilee',
 'Scorpions',
 'Revenge',
 'Mincha (קרבן)',
 'Censuses',
 "Tu B'Av",
 'Ravens',
 'Stars',
 'The Copper Altar',
 'Parents',
 'Piyyut',
 'Fruit',
 'Grass',
 'Zimri',
 'Ammon',
 'Torah Study',
 'Rabbi Akiva',
 'Honesty',
 'Nazir',
 'Leah',
 'Expertise',
 'Identity',
 'Abraham and the Angels',
 'Rav Sheshet',
 'Sun',
 'Chanukkah',
 'Amram',
 'Destruction of the Land of Israel',
 'Betzalel',
 'Giving of the Torah',
 'Prayer',
 'Ushpizin',
 'The Messianic Era',
 'Bar Mitzvah',
 'The Four Children',
 'Eliezer',
 'The Tabernacle in Shiloh',
 '"That it was Good"',
 'The Four Expressions of Redemption',
 'Bat Kol',
 'Goats (שעירים)',
 'Absalom',
 'Greece',
 'Gazelles',
 'Tabernacle Courtyard',
 'Plague of Pestilence (דֶּבֶר )',
 'Creation of Heavens and Earth',
 'Welcoming Guests',
 'Consent',
 'Rebecca',
 'Aron HaBrit',
 'Shabbat Candles',
 'Travel',
 'Abel',
 'Kush',
 'Resurrection',
 'Angels',
 'Adar',
 'Plague of Lice',
 'Songs',
 'Plague of Locusts',
 'Decree Against Sons',
 'Beit Hamikdash',
 'Humanity',
 'Yahrzeit',
 'Yitro',
 'Animals',
 'Havdalah',
 'Milk',
 'The Ten Tribes',
 'Food Ethics',
 'Korach',
 "Jacob's Blessing",
 'Shema',
 'Simeon',
 'Vidui',
 'Priestly Garments',
 'Righteous',
 'Fasting',
 'Zechariah',
 '[Yochanan] Ben Bag Bag',
 'Iddo',
 'Mikveh',
 'Doves',
 'Determinism',
 'Naomi',
 'Mules',
 'Achan',
 'Hunger',
 'Springs',
 'Yokheved',
 'Creation of Light and Luminaires',
 'Father',
 'Egyptian Subjugation',
 'Abraham',
 'Grapes',
 'Alcohol',
 'Plants',
 'The Prophecy of Ezekiel',
 'Inspiration',
 'Jezebel',
 'Kal Vechomer',
 'Jerusalem',
 "Mourner's Kaddish",
 'Trees',
 'Pidyon Haben',
 'Action',
 'Energy',
 'Levite Cities',
 'Minyan',
 'Torah',
 'Flax',
 'Hiram',
 'Humor',
 "David's Wars",
 'Sorcery (קסם)',
 'Journey in the Desert',
 'Fresh Grain',
 'Sodom',
 'Mistakes',
 'Esther',
 'Comfort',
 'Silence',
 'Welcoming',
 "Isaac's Blessing",
 'Organ Donation',
 'Hashgacha',
 'Generosity',
 'Water',
 'Dinah',
 "David's Census",
 'Jacob and the Angel',
 'Chur',
 'Rosh Chodesh',
 'Rehoboam',
 'Sin and Punishment of the Serpent',
 'Asa',
 'Sefirot (Kabbalah)',
 'King Solomon',
 'Ants',
 'Tzara’at',
 'Israel',
 'Azazel',
 'Omer Offering',
 'Society',
 'Poetry',
 'Ten',
 'Tribes',
 'Health',
 'Poverty',
 'Pharaoh',
 'Marah',
 "Tabernacle's Making",
 'Mordekhai',
 'Rav',
 'Medicine',
 'Stopping of the Sun in Gibeon',
 'Priesthood',
 'Cain',
 'Sukkah',
 'Eating',
 'Lag BaOmer',
 'Pregnancy',
 'Rainbows',
 "Akavyah b. Mahalal'el",
 'Prophecy of the Patriarchs',
 'Neighbors',
 "Moses' Birth",
 'Olam Hazeh',
 'Dreams',
 'Chanukah Menorah',
 'Circumcision',
 'Abner',
 'Strangers',
 'Unity',
 'Flour',
 'Lies',
 'Ketubah',
 'Kitniyot',
 'Birthdays',
 'Monotheism',
 'Souls',
 'Gideon',
 'Nebuchadnezzar',
 'Evildoers',
 'Image of God',
 'Egypt',
 'Selichot',
 'Taharah',
 'Respect',
 'Seth',
 'Wolves',
 'Rabbi Elazar b. Azaryah',
 'Sitra Achra',
 'Psychology',
 'Sea Monsters',
 'Isaac',
 'Birth',
 'Moses and the Torah',
 'The Seven Nations',
 'Bat Mitzvah',
 'Beitar',
 'Jewish People',
 'Syria',
 'Shechem',
 'Morality',
 'Witches',
 'Ben Sorer Umoreh',
 'Bar Kokhba',
 'Trade',
 'Samson',
 'Shalom Bayit',
 'Book of Life',
 'Sumkhos',
 'Creation of the Animals',
 'Gabriel the Angel',
 'Discernment',
 'Joy',
 'Punishment',
 'Rahab',
 'Wholeness',
 'Religion',
 'Tapuach',
 "Aaron's Death",
 'Potiphar',
 'Gender',
 'Retributions during the Exodus from Egypt',
 'Praise of God',
 'Flood',
 'The Ten Commandments',
 "Moses' Blessing",
 'Rabban Shimon b. Gamliel (II)',
 'Zeresh',
 'Rabi',
 'Eve',
 'Nephilim',
 'Kehillah',
 '[Shimon] b. Azzai',
 'Mitzvot',
 'Issachar',
 'Rabbi Meir',
 'Etrog',
 'Zachor',
 'Safek',
 'Magicians',
 'Rabbi Chiyya',
 "Moses' Prayer after the Sin of the Calf",
 'Trust',
 'Haman',
 'Melchizedek',
 'Noah and the Ark',
 'Rebuke',
 'Rav Huna',
 'Abraham and Sodom',
 'Ahaz',
 'Shacharit',
 'Yom Kippur',
 'David and the Ark',
 'Planting',
 'Thoughts',
 'Creation of Water',
 'Distinctions of the Land of Israel',
 'Eye for an Eye',
 'Prophets',
 'Earth',
 "Abel's Sacrifice",
 'Covenant of Abraham',
 'Rachel',
 'Tamar',
 'Work',
 'Sorcery',
 'Laughter',
 "Balaam's Prophecy",
 'Isaiah',
 'Zeal',
 'Plague of Frogs',
 'Rabbi Yohanan Hasandlar',
 "Isaac's Wells",
 'Diaspora',
 'Leaders (פרנס)',
 'Joseph in Egypt',
 'Yom Yerushalayim',
 'Amasa',
 'Menashe (King of Judah)',
 'Sanhedrin',
 'Zevulun',
 'Cedars',
 'Journey of the Ark',
 'Miriam',
 'The Future to Come',
 'Habakkuk',
 'Snakes',
 'Egyptian Exile',
 'Kiddush',
 'Magicians and the Ten Plagues',
 'The Patriarchs',
 'Tzimtzum',
 'Malachi',
 'Honey',
 'Nature',
 'Sherets',
 'The Angel of Death',
 'Curiosity',
 'Terumah',
 'Universalism',
 'Bal Tashchit',
 'The Four Parshiot',
 'Peppers',
 'Migrants',
 'Teaching',
 'Jehoiakim',
 'Binding of Isaac',
 'Ezra',
 'Goats',
 'Zion',
 'Generation of the Dispersion',
 'Rain',
 'Meat in the Sinai Desert',
 'Fast of Gedaliah',
 'Eli',
 'Josiah',
 'Human Knowledge',
 'Power',
 'Niddah',
 'The Great Assembly',
 'Wild Animals',
 'Red Sea',
 'Amos',
 'Food',
 'Gratitude',
 'Tachanun',
 'Memory',
 'Days of Cordoning',
 'Hasmoneans',
 'Conquest of Jericho',
 "Joseph and Potiphar's Wife",
 'Hagar',
 "Hosh'ana Rabbah",
 'Bikkurim',
 'Adam',
 'Challah',
 'Menorah',
 'Aaron',
 'Evil',
 'Governments',
 'Queen of Sheba',
 'Media',
 'Civil Discourse',
 'Philosophy',
 'Boaz',
 'Moses and the Priesthood',
 "Judah's Blessing",
 'Balaam',
 'Learning',
 "Na'aman",
 'Mezuzah',
 'Sukkot',
 'Adam and Eve',
 'Judges (שופט)',
 'Chosenness',
 'Cyrus',
 'Golden Calf',
 'Migration',
 'Women in Tanakh',
 'Jewish Unity',
 'Cup of Blessing',
 'Rams',
 'Garden of Eden',
 'Fast of Gedaliah',
 'Incorporeality of God',
 'Reuben',
 'Sin of the Spies',
 'The Four Rivers',
 'Nahum of Gamzo',
 'Mice',
 'Altars',
 "Adam's Sin and His Punishment",
 'Torah Scroll',
 'Prophetess',
 'Kashrut',
 'Kindness',
 'Pomegranates',
 'Damascus',
 'Knowledge',
 'Murder',
 'Vines',
 'Assyria',
 'Dates',
 'Land',
 'Ownership',
 'The Gatherer',
 'Elijah',
 'Atonement',
 'God and Man',
 'Tyre',
 "Moses' Rebuke",
 'Aaron and the Golden Calf',
 'Protection',
 'Lambs',
 'Women',
 'Beit Midrash',
 'Israel in Egypt',
 'Willows',
 'Shemitah',
 'Responsibility',
 'Chavruta',
 'Zedekiah',
 'Moses at the Bush',
 'Presence',
 'Tikkun Olam',
 'The Exodus from Egypt',
 'Sexuality',
 'Jewish Identity',
 'Hallel',
 'Jeremiah',
 'Social Justice',
 'Moses in Midian',
 'Donkeys',
 'Halakhah',
 'The Matriarchs',
 'Sensibilities',
 'Modernity',
 '"The Children of the Angels"',
 'Camels',
 'The Nile River',
 'Parah Adumah',
 'Tzelofchad',
 'Clothing',
 'Imagination',
 'Love',
 'Golems',
 'Light',
 'Environment',
 'Naaseh Venishma',
 'Marriage',
 'Strength',
 'Ewes',
 'Race',
 'Pillar of Cloud',
 'Rabbi Hananyah b. Teradyon',
 'Vashti',
 'Lilith',
 'King Yannai',
 'Creation of Plants',
 'Values',
 'Mourning',
 'Hezekiah',
 'Compassion',
 'Giving',
 'Rabbah Bar Bar Chanah',
 'Forgiveness (מחילה)',
 "Moses and Joseph's Coffin",
 'Meaning',
 'Revelation',
 'Beauty',
 'Destruction of Jerusalem',
 'Matzah',
 'Warnings about the Ten Plagues',
 'Nineveh',
 'Ohel Moed',
 'Bread',
 'Freedom',
 'Sadness',
 'Avishai',
 "Ma'aseh Hamerkavah",
 "God's Blessing and Promise to Abraham",
 'Judah',
 'Al Hanisim',
 'Joshua',
 'Dew',
 'Service',
 'Inclusion',
 'Sacrifices',
 'Head Coverings',
 'Kabbalat Shabbat',
 'Complaints in the Desert',
 'Time',
 'Splitting of the Red Sea',
 "Moses' Prayer after the Sin of the Spies",
 'Showbread',
 'Doeg',
 "Jacob's Dream",
 'The Tree of Knowledge',
 'Encampment of Israel',
 'Covenant with the Patriarchs',
 'Seas',
 'Night',
 'Nimrod',
 'Gog and Magog',
 'Olives',
 'Ahab',
 'Passover',
 'Leviathan',
 'Tefillin',
 'Terach',
 'Children',
 'Books',
 'Abaye',
 'Jonah',
 'Technology',
 'Shalosh Regalim',
 'Wars',
 'Shimei',
 'Shabbat Prayers',
 '"In the Beginning of"',
 'Famine in Egypt',
 'Rabbi Yehoshua [b. Hananyah]',
 'Babylonian Exile',
 'Intellect',
 'Relationships',
 'Chametz',
 'Writing',
 'Numbers',
 'Tabernacle Inauguration',
 'Jacob and the Birthright',
 'Prophecy of Abraham',
 'The House of David',
 'Dogs',
 'Noah',
 'Gad',
 'Counting of the Levites',
 'Simchat Torah',
 'Yirat Shamayim',
 'The Sons of Korach',
 'Sisera',
 'Abigail',
 "Moses' Prophecy",
 'Spirituality',
 "Moses' Knowledge",
 'Creativity',
 'Niggun',
 'Rome',
 'Samael',
 'Bodies',
 'Meat',
 'David and Batsheva',
 'Noah and the Vineyard',
 "Ma'aser Sheni",
 'Roosters',
 'Creation of Man',
 'Oils',
 'Kippah',
 'Masculinity',
 'Divorce',
 "Cain's Sacrifice",
 'Arvit',
 'Germany',
 'Honoring Parents',
 'King David',
 'Kaddish',
 'Birthright',
 'Tzitzit',
 'The Written Torah and the Oral Torah',
 'Nadav and Avihu',
 'Seven Species',
 'Generation of Enosh',
 'The Elements',
 'Babel',
 'Poor',
 'Achitofel',
 'Forgiveness',
 'Harmful Forces',
 'Jesse',
 'Disabilities',
 'Jacob in Egypt',
 'The Ten Plagues',
 'Shimon Bar Yochai',
 'Destruction of the Temple',
 'Rabbinic Authority',
 "Moses' Death and Burial",
 'Love of God',
 'Divine Names',
 'Burial',
 'The Sale of Joseph',
 'Drinking',
 'Death',
 'Oral Torah',
 'Sleep',
 'Beruriah',
 'Hannah',
 'Birkot Hashachar',
 'Elisha Ben Abuya',
 'Seder',
 'Haggadah',
 'Political Thought',
 'Peace',
 'Jericho',
 'Plague of Darkness',
 'Tiberias',
 'Benjamin',
 'Man and Animals',
 'Fertility',
 'Serah the Daughter of Asher',
 'Disability',
 'Pluralism',
 'Rabbi Tarfon',
 'Birkat HaMazon',
 'Incense',
 "Pharaoh's Dream",
 'Galil',
 'Jeroboam (Son of Nebat)',
 'Happiness',
 'Friendship',
 'Judith',
 'Agency',
 'New Year',
 'Ham',
 'Asher',
 'Tekhelet',
 'Hitbodedut',
 "Jacob's Oath",
 'Mishloach Manot',
 'Infertility',
 'Beit Din',
 'Edom and the Generation of the Desert',
 'Moab',
 '13 Principles of Faith',
 'Avtalyon',
 'Shem',
 'Ahasuerus',
 'Rav Chisda',
 'Exile',
 'Moses and the Tablets',
 'Song of the Sea',
 "Joseph's Dream",
 'Innovation',
 'Head Covering',
 'Ruth',
 'Vegetarianism',
 'Democracy',
 'Candles',
 'Yetzer Hatov',
 'Yoash (King of Judah)',
 'Human Dignity',
 'Free Will',
 'The Book of Esther',
 'Elisha',
 'Plague of the Firstborn',
 'Manna',
 'Superstitions',
 'Effect of Sin',
 "God's Will",
 'Physicians',
 'Middot',
 'Spring',
 'Rabbi Chanina b. Dosa',
 'Og',
 'Yavneh',
 'Deborah',
 'Mentally Handicapped People',
 'Moses and the Tent of Meeting',
 'Donations for the Tabernacle',
 'Shmuel (Amora)',
 'Rav Pappa',
 'Visiting the Sick',
 'Mishkan',
 'Motzi',
 'Pinchas',
 'Sennacherib',
 'Bioethics',
 'Summer',
 'Gift Giving',
 'Vulnerability',
 'Shofar',
 'War with Midian',
 'Argument',
 'Tarshish',
 'Burning Bush',
 'Agriculture',
 'Moriah',
 'Carefulness',
 'Courage',
 'Justice',
 'Air',
 'Rituals',
 'Moses and the Egyptian',
 'Business',
 'Four Cups',
 "Jacob's Burial",
 'Purim',
 'Shmuel the Little',
 'Mah Tovu',
 'Frogs',
 'Locusts',
 'Redemption of Captives',
 'Miracles',
 'Shabbat Hagadol',
 'Yetzer Hara',
 "Moses' Signs",
 'Obadiah',
 'Beersheba',
 'Astronomy',
 'Lashon Hara',
 'Dirt',
 'Modern Thought',
 'Losses',
 'Wisdom',
 'Avodat Hashem',
 'Elkanah',
 'The Ten Days of Repentance',
 'Partitions',
 'Clouds',
 'Well in the Desert',
 'Olam Haba',
 'Shavuot',
 'Life',
 'Yom HaAtzmaut',
 'Creation',
 'Reality',
 "V'ahavta",
 'Mindfulness',
 'Joseph',
 'Neshama',
 'Rava',
 'Tzedakah',
 'Knowing',
 'Rabbi Shimon b. Lakish',
 'The Waters of Meribah',
 'David and the Temple',
 'Joseph and the Wine Steward',
 'Rivers',
 'Jacob',
 'Ishmael',
 'Perspective',
 'Thanks',
 'Tumah',
 'Borrowing the Property during the Exodus from Egypt',
 'Jacob and the Sticks',
 'High Holidays',
 'Agunah',
 'Abraham and the Hittites',
 'Isaac and Esau',
 'Abraham in Ur Kasdim and his Departure from There',
 'Reincarnation',
 'Conquest and Division'];
