      const ordered_phrases = ['Shabbat',
 'Rosh Chodesh',
 'Rosh Hashanah',
 'Yom Kippur',
 'Sukkot',
 'Shemini Atzeret',
 'Simchat Torah',
 'Chanukkah',
 'Purim',
 'Passover',
 'Shavuot',
 "Tisha B'Av",
 'Fasting',
 "Tu B'Av",
 'Lag BaOmer',
 'Sefirat HaOmer',
 'The Ten Days of Repentance',
 'Shabbat Hagadol',
 'High Holidays',
 'Seder',
 'New Year',
 'Yom Yerushalayim',
 'Fast of Gedaliah',
 'Asarah BeTevet',
 'Yom HaAtzmaut',
 'Sigd',
 'Elul',
 'Four Questions',
 'The Four Children',
 'The Four Expressions of Redemption',
 'Fast of Gedaliah',
 "Hosh'ana Rabbah",
 'The Patriarchs',
 'Abigail',
 'Avishai',
 'Abner',
 'Abraham',
 'Absalom',
 'Achitofel',
 'Adoniah',
 'Adam',
 'Adam and Eve',
 'Aaron',
 'Ahab',
 'Ahaz',
 'Jezebel',
 'Elijah',
 'Eliezer',
 'Elisha',
 'Elkanah',
 'The Matriarchs',
 'Asa',
 'Esther',
 'Ephraim',
 'Aram',
 'Boaz',
 'Balaam',
 'Benjamin',
 'Gad',
 'Gechazi',
 'Goliath',
 'Deborah',
 'Doeg',
 'King David',
 'The Spies',
 'Dinah',
 'Dan',
 'Daniel',
 'Abel',
 'Hagar',
 'Haman',
 'Vashti',
 'Zevulun',
 'Zechariah',
 'Zimri',
 'Zeresh',
 'Habakkuk',
 'Chur',
 'Hezekiah',
 'Hiram',
 'Ham',
 'Hannah',
 'Judah',
 'Judith',
 'Jehoiakim',
 'Jonadab, the Son of Rechab',
 'Joshua',
 'Yoash (King of Judah)',
 'Jonah',
 'Joseph',
 'Ezekiel',
 'Jacob',
 'Isaac and Esau',
 'Isaac',
 'Jeroboam (Son of Nebat)',
 'Yokheved',
 'Moses',
 'Jeremiah',
 'Jesse',
 'Ishmael',
 'Isaiah',
 'Issachar',
 'Yitro',
 'Cyrus',
 'Leah',
 'Lot',
 'Lilith',
 'Malachi',
 'Melchizedek',
 'Menashe (King of Judah)',
 'Mordekhai',
 'Miriam',
 'Nebuchadnezzar',
 'Nadav and Avihu',
 'Noah',
 'Nehemiah',
 'Nimrod',
 'Naomi',
 "Na'aman",
 'Nephilim',
 'Sisera',
 'Sennacherib',
 'Serah the Daughter of Asher',
 'Iddo',
 'Obadiah',
 'Og',
 'Uzziah',
 'Ezra',
 'Achan',
 'The Sons of Eli',
 'Eli',
 'Amos',
 'Amalek',
 'Amram',
 'Amasa',
 'Esau',
 'Potiphar',
 'Pinchas',
 'Pharaoh',
 'Daughters of Tzelofchad',
 'Tzelofchad',
 'Keturah',
 'Cain',
 'The Sons of Korach',
 'Korach',
 'Reuben',
 'Rebecca',
 'Ruth',
 'Rahab',
 'Rehoboam',
 'Rachel',
 'King Saul',
 'King Solomon',
 'Simeon',
 'Shimei',
 'Samson',
 'Tamar',
 'Terach',
 'Queen of Sheba',
 'Sarah',
 'Josiah',
 'Zedekiah',
 'Eve',
 'Betzalel',
 'Shem',
 'Gideon',
 'Ahasuerus',
 "Pharaoh's Daughter",
 'Asher',
 'Seth',
 'Nachshon Ben Aminadav',
 'Prayer',
 'Haggadah',
 'Kavanah',
 'Praise of God',
 'Blessings',
 'Birkat HaMazon',
 'Havdalah',
 'Hallel',
 'Hitbodedut',
 'Vidui',
 'Niggun',
 'Kiddush',
 'Kaddish',
 'Shema',
 'Arvit',
 'Shabbat Prayers',
 'Shacharit',
 'Tashlich',
 'Al Hanisim',
 'Kabbalat Shabbat',
 "Mourner's Kaddish",
 'Aleinu',
 'Hashkiveinu',
 'Mah Tovu',
 'Motzi',
 'Selichot',
 "V'ahavta",
 'Birkot Hashachar',
 'Shemoneh Esrei',
 'Blessings (Halakhah)',
 'Tachanun',
 'Mourning',
 'Mother',
 'Bar Mitzvah',
 'Divorce',
 'Parents',
 'Losses',
 'Education',
 'Yahrzeit',
 'Children',
 'Ketubah',
 'Birth',
 'Circumcision',
 'Death',
 'Marriage',
 'Fertility',
 'Burial',
 'Conversion',
 'Bat Mitzvah',
 'Pidyon Haben',
 'Etrog',
 'Four Cups',
 'Priestly Garments',
 'Cup of Blessing',
 'The Golden Altar',
 'The Copper Altar',
 'Menorah',
 'The Curtain',
 'Temple Vessels',
 'Head Coverings',
 'The Tablets',
 'Lulav',
 'Showbread',
 'Mezuzah',
 'Chanukah Menorah',
 "Ma'aser Sheni",
 'Mikveh',
 'Mishkan',
 'Candles',
 'Sukkah',
 'Torah Scroll',
 'Parah Adumah',
 'Tzitzit',
 'Incense',
 'Mincha (קרבן)',
 'Libations',
 'Omer Offering',
 'Shabbat Candles',
 'Shofar',
 'Oils',
 'Tefillin',
 'Terumah',
 'Kippah',
 'Tallit',
 'Man and Wife',
 'Converts',
 'Identity',
 'Women',
 'Ownership',
 'Diaspora',
 'Strangers',
 'Jewish People',
 'Human Dignity',
 'Deceit',
 'Power',
 'Money',
 'Wars',
 'Governments',
 'Leadership',
 'Censuses',
 'Trade',
 'Travel',
 'Non Jews',
 'Tzaddik',
 'Revenge',
 'Business',
 'Slaves',
 'Work',
 'Poverty',
 'Punishment',
 'Wealth',
 'Poor',
 'Oppression',
 'Workers',
 'Action',
 'Leaders (פרנס)',
 'Society',
 'Authority',
 'Hunger',
 'Mentally Handicapped People',
 'Partnership',
 'Neighbors',
 'Agency',
 'Hate',
 'Murder',
 'Feminism',
 'Sexuality',
 'Abortion',
 'Migration',
 'Inclusion',
 'Disability',
 'Political Thought',
 'Civil Discourse',
 'Relationships',
 'Pluralism',
 'Democracy',
 'Media',
 'Race',
 'Racism',
 'Diversity',
 'Service',
 'Protection',
 'Modernity',
 'Bullying',
 'Independence',
 'Liberation',
 'Migrants',
 'Innovation',
 'Technology',
 'Management',
 'Masculinity',
 'Disabilities',
 'Social Justice',
 'Marah',
 'Covenant with the Patriarchs',
 'Prophecy of the Patriarchs',
 'Abraham in Ur Kasdim and his Departure from There',
 'Abraham in Egypt',
 'Covenant of Abraham',
 "God's Blessing and Promise to Abraham",
 'Abraham and the Hittites',
 'Abraham and the Angels',
 'Abraham and the Kings',
 'Abraham and Sodom',
 'Prophecy of Abraham',
 'Tests of Abraham',
 'Creation of Man',
 "Adam's Sin and His Punishment",
 'Aaron and the Golden Calf',
 "Aaron's Death",
 'The Great Assembly',
 'Destruction of the Land of Israel',
 'Conquest and Division',
 'Destruction of Babylonia',
 'Destruction of the Temple',
 'Inauguration of the Temple',
 "Balaam's Prophecy",
 '"The Children of the Angels"',
 '"In the Beginning of"',
 'Creation of Light and Luminaires',
 'Creation of the Animals',
 '"That it was Good"',
 'Creation of Water',
 'Creation of Plants',
 'Creation of Heavens and Earth',
 'Creation',
 'Gog and Magog',
 'Decree Against Sons',
 'Israel in Egypt',
 'Egyptian Subjugation',
 'Egyptian Exile',
 'Plague of Pestilence (דֶּבֶר )',
 'The House of David',
 'David and the Temple',
 'David and the Ark',
 'David and Batsheva',
 "David's Wars",
 "David's Census",
 'Generation of Enosh',
 'Generation of the Flood',
 'Well in the Desert',
 'Meat in the Sinai Desert',
 'Appointment of Judges for The Generation of the Desert',
 'Edom and the Generation of the Desert',
 'Golden Calf',
 'Sin of the Spies',
 'Sin of Peor',
 'War with Midian',
 'Manna',
 'Journey in the Desert',
 'The Gatherer',
 'Naaseh Venishma',
 'Sacrifices in the Desert',
 'Complaints in the Desert',
 'Generation of the Desert',
 'Generation of the Dispersion',
 "Abel's Sacrifice",
 'Destruction of Jerusalem',
 "Judah's Blessing",
 'Conquest of Jericho',
 'Stopping of the Sun in Gibeon',
 "Joseph's Blessing",
 "Joseph and Potiphar's Wife",
 'Joseph in Egypt',
 'Joseph and the Wine Steward',
 "Joseph's Dream",
 'The Sale of Joseph',
 'The Prophecy of Ezekiel',
 'Jacob and the Birthright',
 "Jacob's Blessing",
 'The Promise to Jacob',
 "Jacob's Dream",
 'Jacob and the Angel',
 'Jacob and the Sticks',
 'Jacob in Egypt',
 "Jacob's Oath",
 "Jacob's Burial",
 "Isaac's Wells",
 "Isaac's Blessing",
 "Moses' Signs",
 'Borrowing the Property during the Exodus from Egypt',
 'Retributions during the Exodus from Egypt',
 'The Exodus from Egypt',
 'Crossing the Jordan River and Setting of the Stones',
 'Journey of the Ark',
 'Blessing of Levi',
 'Counting of the Levites',
 'Leviathan',
 'Tower of Babel',
 'The Idol of Micha',
 'Famine in Egypt',
 'Moses and the Tent of Meeting',
 'Moses in Midian',
 'Moses at the Bush',
 "Moses' Blessing",
 "Moses and Joseph's Coffin",
 'Moses and the Tablets',
 'Moses and the Egyptian',
 'Moses and Israel',
 "Moses' Knowledge",
 'Moses and the Priesthood',
 "Moses' Birth",
 'The Waters of Meribah',
 "Moses' Death and Burial",
 "Moses' Prophecy",
 "Moses' Rebuke",
 'Moses and the Torah',
 "Moses' Prayer after the Sin of the Spies",
 "Moses' Prayer after the Sin of the Calf",
 'Raising Up and Anointing the Tabernacle',
 'Tabernacle Inauguration',
 "Tabernacle's Journey",
 "Tabernacle's Making",
 'Donations for the Tabernacle',
 'Days of Cordoning',
 'Noah and the Ark',
 'Noah and the Vineyard',
 "Noah's Sacrifice",
 'Sin and Punishment of the Serpent',
 'The Worship of Molech',
 'Pillar of Cloud',
 'War with Amalek',
 'The Tree of Knowledge',
 'The Tree of Life',
 'Binding of Isaac',
 'Plague of Locusts',
 'Plague of Hail',
 'Plague of Blood',
 'Warnings about the Ten Plagues',
 'Magicians and the Ten Plagues',
 'Plague of Darkness',
 'Plague of Lice',
 'Plague of the Firstborn',
 'Plague of Wild Animals',
 'Plague of Frogs',
 'Plague of Boils',
 'The Ten Plagues',
 'The Ten Commandments',
 'The Ten Tribes',
 "The Hardening of Pharaoh's Heart",
 "Pharaoh's Dream",
 "Cain's Sacrifice",
 'Tribes',
 'The Seven Nations',
 'Song of the Sea',
 'Giving of the Torah',
 'Flood',
 'Splitting of the Red Sea',
 'Values',
 'Knowing God',
 'Unity',
 'Peace',
 'Middot',
 'Life',
 'Love',
 'Happiness',
 'Faith',
 'Courage',
 'Truth',
 'Humor',
 'Trust',
 'Bal Tashchit',
 'Visiting the Sick',
 'Expertise',
 'Strength',
 'Kindness',
 'Devekut',
 'Imagination',
 'Thanks',
 'Welcoming Guests',
 'Gratitude',
 'Modesty',
 'Renewal',
 'Carefulness',
 'Memory',
 'Alacrity',
 'Friendship',
 'Wisdom',
 'Compassion',
 'Giving',
 'Freedom',
 'Knowing',
 'Honesty',
 'Righteous',
 'Honoring Parents',
 'Respect',
 'Atonement',
 'Learning',
 'Teaching',
 'Forgiveness (מחילה)',
 'Machloket',
 'Generosity',
 'Comfort',
 'Rebuke',
 'Forgiveness',
 'Curiosity',
 'Love of God',
 'Yirat Shamayim',
 'Avodat Hashem',
 'Humility',
 'Responsibility',
 'Fear (פחד)',
 'Tzedakah',
 'Kehillah',
 'Hope',
 'Zeal',
 'Listening',
 'Spirituality',
 'Mercy',
 'Questions',
 'Discernment',
 'Wholeness',
 'Joy',
 'Silence',
 'Tikkun',
 'Teshuvah',
 'Chavruta',
 'Consent',
 'Mindfulness',
 'Creativity',
 'Torah Study',
 'Argument',
 'Presence',
 'Welcoming',
 'Perspective',
 'Shalom Bayit',
 'Empathy',
 'Growth',
 'Inspiration',
 'Vulnerability',
 'Love Your Neighbor as Yourself',
 'Neshama',
 'Image of God',
 'God and Man',
 'Incorporeality of God',
 'Hashgacha',
 'Monotheism',
 "God's Existence",
 "God's Will",
 'God',
 'Bat Kol',
 'Gehinnom',
 'Reincarnation',
 'Religion',
 'Effect of Sin',
 'Impulses',
 'Priesthood',
 'The Throne of Glory',
 'Heretics',
 'The Future to Come',
 'Metatron',
 'Michael',
 'Gabriel the Angel',
 'Chayot',
 'The Angel of Death',
 "Ma'aseh Hamerkavah",
 'The Effects of a Commandment',
 'Mitzvot',
 'The Messianic Era',
 'Mashiach',
 'Prophecy',
 'Prophets',
 'Miracles',
 'Souls',
 'Extra Soul',
 'Sitra Achra',
 'Samael',
 'Sanhedrin',
 'Sefirot (Kabbalah)',
 'Idolatry',
 'Olam Haba',
 'Olam Hazeh',
 'Theodicy',
 'Tzimtzum',
 'Holiness',
 'Rabbinic Authority',
 'Ruach Hakodesh',
 'Satan',
 'Shekhinah',
 'Divine Names',
 'The Written Torah and the Oral Torah',
 'Torah',
 'Resurrection',
 'Revelation',
 'Rituals',
 'Chosenness',
 'Book of Life',
 'Prophetess',
 'Beit Din',
 'Angels',
 'Yetzer Hatov',
 'Yetzer Hara',
 'Air',
 'Animals',
 'Ants',
 'Astronomy',
 'Birds',
 'Camels',
 'Cats',
 'Cedars',
 'Clouds',
 'Dates',
 'Deserts',
 'Nature',
 'Dew',
 'Dirt',
 'Dogs',
 'Donkeys',
 'Doves',
 'Eagles',
 'Earth',
 'Ecology',
 'Energy',
 'Environment',
 'Ewes',
 'Figs',
 'Fire',
 'Fish',
 'Flax',
 'Frogs',
 'Gardening',
 'Gazelles',
 'Goats',
 'Goats (שעירים)',
 'Grapes',
 'Grass',
 'Horses',
 'Lambs',
 'Land',
 'Light',
 'Lilies',
 'Lions',
 'Locusts',
 'Man and Animals',
 'Mice',
 'Mountains',
 'Mules',
 'Myrtles',
 'Night',
 'Oxen',
 'Pigs',
 'Plants',
 'Rain',
 'Rams',
 'Ravens',
 'Rivers',
 'Roosters',
 'Science',
 'Scorpions',
 'Seas',
 'Sherets',
 'Snakes',
 'Snow',
 'Spring',
 'Springs',
 'Summer',
 'Sun',
 'Sustainability',
 'Tapuach',
 'The Elements',
 'The Ocean',
 'Trees',
 'Vines',
 'Water',
 'Weather',
 'Wild Animals',
 'Willows',
 'Winds',
 'Wolves',
 'Worms',
 'Yavneh',
 'Edom',
 'Ohel Moed',
 'The Four Kingdoms',
 'Alexandria',
 'The Four Rivers',
 'Distinctions of the Land of Israel',
 'Babel',
 'Beersheba',
 'Beit El',
 'Beit Hamikdash',
 'Beitar',
 'Galil',
 'Germany',
 'Damascus',
 'Mount Gerizim and Mount Ebal',
 'Moriah',
 'Outside of Israel',
 'Tiberias',
 'The Land of Judah',
 'Greece',
 'Jerusalem',
 'Kush',
 'Levite Cities',
 'Midian',
 'Moab',
 'Partitions',
 'Encampment of Israel',
 'Egypt',
 'Tabernacle Courtyard',
 'The Nile River',
 'Nineveh',
 'Sodom',
 'Syria',
 'Ever HaYarden',
 'Cities',
 'Ammon',
 'Gemorrah',
 'Tyre',
 'Zion',
 'Rome',
 'The Tabernacle in Shiloh',
 'Shechem',
 'Heavens',
 'HaSharon',
 'Tarshish',
 'National Library of Israel',
 'Beit Midrash',
 'Temple Mount',
 'Red Sea',
 'Mount Sinai',
 'Second Temple',
 'En Dor',
 'Jericho',
 'Israel',
 'Assyria',
 'Food',
 'Eating',
 'Honey',
 'Olives',
 'Milk',
 'Challah',
 'Chametz',
 'Agriculture',
 'Wine',
 'Fresh Grain',
 'Bread',
 'Kashrut',
 'Maror',
 'Planting',
 'Peppers',
 'Fruit',
 'Flour',
 'Drinking',
 'Spices',
 'Food Ethics',
 'Alcohol',
 'Vegetarianism',
 'Meat',
 'Kitniyot',
 'Matzah',
 'Pomegranates',
 'Wheat',
 'Philosophy',
 'Ethics',
 'Human Knowledge',
 'Free Will',
 'Evil',
 'Intellect',
 'Time',
 'Dreams',
 'Beauty',
 'Thoughts',
 'Reality',
 'Evildoers',
 'Jewish Identity',
 'Universalism',
 'Psychology',
 'Particularism',
 'Morality',
 'Sensibilities',
 'Meaning',
 'Determinism',
 'Knowledge',
 'Modern Thought',
 'Bioethics',
 'Purpose of Life',
 'Good',
 'Folklore',
 'Superstitions',
 'Magicians',
 'Sorcery',
 'Harmful Forces',
 'Witches',
 'Sorcery (קסם)',
 'Demons',
 'Sea Monsters',
 'Golems',
 'Infertility',
 'Medicine',
 'Mental Health',
 'Organ Donation',
 'Physicians',
 'Sleep',
 'Health',
 'Art',
 'Colors',
 'Songs',
 'Music',
 'Piyyut',
 'Dances',
 'Poetry',
 'Rabbi Akiva',
 'Shimon Bar Yochai',
 'Nahum of Gamzo',
 'Avtalyon',
 'Rabbi Meir',
 'Shemaiah',
 'Shammai',
 'Hillel',
 'Rav',
 'Rava',
 'Rav Sheshet',
 'Rabbi Eliezer b. Hyrcanus',
 "Akavyah b. Mahalal'el",
 'Rabban Shimon b. Gamliel (II)',
 'Rabbi Shimon b. Lakish',
 'Rabi',
 'Rav Zera',
 'Rabbah Bar Bar Chanah',
 '[Shimon] b. Zoma',
 'Sumkhos',
 'Ulla',
 'Rabbi Yohanan Hasandlar',
 'Rabbi Yehoshua b. Levi',
 'Abaye',
 'Elisha Ben Abuya',
 'Rabbi Elazar b. Azaryah',
 'Rabban Yochanan b. Zakkai',
 'Rabbi Chanina b. Dosa',
 '[Yochanan] Ben Bag Bag',
 'Rabbi Chiyya',
 'Beruriah',
 'Rabbi Hananyah b. Teradyon',
 'Shmuel (Amora)',
 'Shimon b. Shetach',
 'Rabbi Yehoshua [b. Hananyah]',
 '[Shimon] b. Azzai',
 'Bar Kokhba',
 'Rabbi Tarfon',
 'Rav Pappa',
 'Rav Chisda',
 'Rabban Gamliel of Yavneh (II)',
 'Rav Ashi',
 'Rav Huna',
 'Shmuel the Little',
 '13 Principles of Faith',
 'Redemption of Captives',
 'Mishloach Manot',
 'The Book of Esther',
 'Zachor',
 'Oral Torah',
 'Kings',
 'Sacrifices',
 'Shemitah',
 'Jubilee',
 'Eye for an Eye',
 'Cities of Refuge',
 'Exile',
 'Bikkurim',
 'Shifrah and Puah',
 'Rainbows',
 'Gift Giving',
 'Minhag',
 'Ben Sorer Umoreh',
 'The Four Parshiot',
 'Tzara’at',
 'Tumah',
 'Taharah',
 'Niddah',
 'Hasmoneans',
 'The Book of Ruth',
 'Clothing',
 'Head Covering',
 'Adar',
 'Baseless Hatred',
 'Altars',
 'Seven Species',
 'Jewish Unity',
 'Lashon Hara',
 'Justice',
 'Tekhelet',
 'Halakhah',
 'Minyan',
 'Ten',
 'Shaliach Tsibur',
 'Azazel',
 'Garden of Eden',
 'Chasidut',
 'Agunah',
 'Judges (שופט)',
 'Babylonian Exile',
 'King Yannai',
 'Letters',
 'Numbers',
 'Ushpizin',
 'Bodies',
 'Shalosh Regalim',
 'Writing',
 'Gender',
 'Humanity',
 'Calendar',
 'Safek',
 'Stars',
 'Burning Bush',
 'Tikkun Olam',
 'Students',
 'Birthright',
 'Pregnancy',
 'Women in Tanakh',
 'Sadness',
 'Laughter',
 'Lies',
 'Birthdays',
 'Aron HaBrit',
 'Mistakes',
 'Nazir',
 'Midrash',
 'Vows',
 'Eruv',
 'Kal Vechomer',
 'Netilat Yadayim',
 'Father',
 'Books'];
      const phrases = ['Lions',
 'The Golden Altar',
 'Education',
 'Art',
 'Deserts',
 'Birds',
 'Idolatry',
 'Mercy',
 'Eagles',
 'King Saul',
 'Minhag',
 'Beit El',
 'Mental Health',
 'Sin of Peor',
 'Ephraim',
 'HaSharon',
 'Sefirat HaOmer',
 'Racism',
 'Second Temple',
 'Letters',
 'Gemorrah',
 'God',
 'Heavens',
 'Shemaiah',
 'National Library of Israel',
 'Bullying',
 'The Land of Judah',
 'Lot',
 'Michael',
 'Rosh Hashanah',
 'Abortion',
 'Oxen',
 'Extra Soul',
 'Man and Wife',
 'Mother',
 'The Idol of Micha',
 'Netilat Yadayim',
 'Blessing of Levi',
 'Winds',
 'Particularism',
 'Pigs',
 'The Throne of Glory',
 'Hate',
 'Tallit',
 'Theodicy',
 'Edom',
 'Shaliach Tsibur',
 'Folklore',
 'Holiness',
 'Dan',
 'Ethics',
 'Sustainability',
 "The Hardening of Pharaoh's Heart",
 'Mount Sinai',
 "Pharaoh's Daughter",
 'Horses',
 'Questions',
 'Ulla',
 'The Spies',
 'Truth',
 'Rabbi Yehoshua b. Levi',
 "Noah's Sacrifice",
 'Empathy',
 'Oppression',
 'Rabban Gamliel of Yavneh (II)',
 'Myrtles',
 'Daniel',
 'Esau',
 'Partnership',
 'Hashkiveinu',
 'Workers',
 '[Shimon] b. Zoma',
 'Metatron',
 'Daughters of Tzelofchad',
 'Shemoneh Esrei',
 'Conversion',
 'Chasidut',
 'Sigd',
 'Devekut',
 'Hope',
 'Mountains',
 'Rabbi Eliezer b. Hyrcanus',
 'The Tablets',
 'Rav Ashi',
 'Impulses',
 'Rabban Yochanan b. Zakkai',
 'Figs',
 'Love Your Neighbor as Yourself',
 'Moses',
 'Dances',
 'Colors',
 'Calendar',
 'Prophecy',
 'Blessings (Halakhah)',
 'Renewal',
 'Music',
 'Midrash',
 'War with Amalek',
 'Worms',
 'Ruach Hakodesh',
 'En Dor',
 'Good',
 'Purpose of Life',
 'Plague of Wild Animals',
 'Tests of Abraham',
 'Faith',
 'Independence',
 'Crossing the Jordan River and Setting of the Stones',
 'Converts',
 'Mount Gerizim and Mount Ebal',
 'Raising Up and Anointing the Tabernacle',
 'Four Questions',
 'Shimon b. Shetach',
 'Abraham and the Kings',
 'Slaves',
 'Eruv',
 'Tashlich',
 'Midian',
 'Humility',
 'Weather',
 'Plague of Boils',
 'Appointment of Judges for The Generation of the Desert',
 'Shemini Atzeret',
 'The Worship of Molech',
 'Maror',
 'Baseless Hatred',
 'Mashiach',
 'Vows',
 'Adoniah',
 'Temple Mount',
 'Leadership',
 'Plague of Blood',
 'Non Jews',
 'Diversity',
 'Keturah',
 'Shifrah and Puah',
 'Wine',
 'The Promise to Jacob',
 'Amalek',
 'Moses and Israel',
 'Kings',
 'Abraham in Egypt',
 'Sacrifices in the Desert',
 'Shekhinah',
 'Ezekiel',
 'Spices',
 'Snow',
 'Ecology',
 'Shabbat',
 'Ever HaYarden',
 'Nachshon Ben Aminadav',
 'Destruction of Babylonia',
 'Hillel',
 'Nehemiah',
 'Management',
 'Goliath',
 "Tabernacle's Journey",
 'Listening',
 'Alacrity',
 'Teshuvah',
 'Gechazi',
 'The Ocean',
 'Machloket',
 'Tower of Babel',
 'Temple Vessels',
 "God's Existence",
 'Lilies',
 'Generation of the Flood',
 'Inauguration of the Temple',
 'Lulav',
 'The Effects of a Commandment',
 'The Sons of Eli',
 'Alexandria',
 'Gardening',
 'Money',
 "Joseph's Blessing",
 'Uzziah',
 'Fish',
 'Generation of the Desert',
 'Heretics',
 'The Book of Ruth',
 'Students',
 'Growth',
 'Modesty',
 'Science',
 'Elul',
 'Cities',
 'Deceit',
 'Fear (פחד)',
 'Chayot',
 'Libations',
 'Knowing God',
 'The Tree of Life',
 'Cats',
 'Demons',
 'Gehinnom',
 'Liberation',
 'Kavanah',
 'Authority',
 'Tikkun',
 'The Four Kingdoms',
 'Fire',
 'Wealth',
 'Shammai',
 'Satan',
 'Rav Zera',
 'Sarah',
 'Wheat',
 'Plague of Hail',
 'Cities of Refuge',
 'Asarah BeTevet',
 'Tzaddik',
 'Aleinu',
 'Outside of Israel',
 "Tisha B'Av",
 'Jonadab, the Son of Rechab',
 'Aram',
 'Blessings',
 'The Curtain',
 'Feminism',
 'Jubilee',
 'Scorpions',
 'Revenge',
 'Mincha (קרבן)',
 'Censuses',
 "Tu B'Av",
 'Ravens',
 'Stars',
 'The Copper Altar',
 'Parents',
 'Piyyut',
 'Fruit',
 'Grass',
 'Zimri',
 'Ammon',
 'Torah Study',
 'Rabbi Akiva',
 'Honesty',
 'Nazir',
 'Leah',
 'Expertise',
 'Identity',
 'Abraham and the Angels',
 'Rav Sheshet',
 'Sun',
 'Chanukkah',
 'Amram',
 'Destruction of the Land of Israel',
 'Betzalel',
 'Giving of the Torah',
 'Prayer',
 'Ushpizin',
 'The Messianic Era',
 'Bar Mitzvah',
 'The Four Children',
 'Eliezer',
 'The Tabernacle in Shiloh',
 '"That it was Good"',
 'The Four Expressions of Redemption',
 'Bat Kol',
 'Goats (שעירים)',
 'Absalom',
 'Greece',
 'Gazelles',
 'Tabernacle Courtyard',
 'Plague of Pestilence (דֶּבֶר )',
 'Creation of Heavens and Earth',
 'Welcoming Guests',
 'Consent',
 'Rebecca',
 'Aron HaBrit',
 'Shabbat Candles',
 'Travel',
 'Abel',
 'Kush',
 'Resurrection',
 'Angels',
 'Adar',
 'Plague of Lice',
 'Songs',
 'Plague of Locusts',
 'Decree Against Sons',
 'Beit Hamikdash',
 'Humanity',
 'Yahrzeit',
 'Yitro',
 'Animals',
 'Havdalah',
 'Milk',
 'The Ten Tribes',
 'Food Ethics',
 'Korach',
 "Jacob's Blessing",
 'Shema',
 'Simeon',
 'Vidui',
 'Priestly Garments',
 'Righteous',
 'Fasting',
 'Zechariah',
 '[Yochanan] Ben Bag Bag',
 'Iddo',
 'Mikveh',
 'Doves',
 'Determinism',
 'Naomi',
 'Mules',
 'Achan',
 'Hunger',
 'Springs',
 'Yokheved',
 'Creation of Light and Luminaires',
 'Father',
 'Egyptian Subjugation',
 'Abraham',
 'Grapes',
 'Alcohol',
 'Plants',
 'The Prophecy of Ezekiel',
 'Inspiration',
 'Jezebel',
 'Kal Vechomer',
 'Jerusalem',
 "Mourner's Kaddish",
 'Trees',
 'Pidyon Haben',
 'Action',
 'Energy',
 'Levite Cities',
 'Minyan',
 'Torah',
 'Flax',
 'Hiram',
 'Humor',
 "David's Wars",
 'Sorcery (קסם)',
 'Journey in the Desert',
 'Fresh Grain',
 'Sodom',
 'Mistakes',
 'Esther',
 'Comfort',
 'Silence',
 'Welcoming',
 "Isaac's Blessing",
 'Organ Donation',
 'Hashgacha',
 'Generosity',
 'Water',
 'Dinah',
 "David's Census",
 'Jacob and the Angel',
 'Chur',
 'Rosh Chodesh',
 'Rehoboam',
 'Sin and Punishment of the Serpent',
 'Asa',
 'Sefirot (Kabbalah)',
 'King Solomon',
 'Ants',
 'Tzara’at',
 'Israel',
 'Azazel',
 'Omer Offering',
 'Society',
 'Poetry',
 'Ten',
 'Tribes',
 'Health',
 'Poverty',
 'Pharaoh',
 'Marah',
 "Tabernacle's Making",
 'Mordekhai',
 'Rav',
 'Medicine',
 'Stopping of the Sun in Gibeon',
 'Priesthood',
 'Cain',
 'Sukkah',
 'Eating',
 'Lag BaOmer',
 'Pregnancy',
 'Rainbows',
 "Akavyah b. Mahalal'el",
 'Prophecy of the Patriarchs',
 'Neighbors',
 "Moses' Birth",
 'Olam Hazeh',
 'Dreams',
 'Chanukah Menorah',
 'Circumcision',
 'Abner',
 'Strangers',
 'Unity',
 'Flour',
 'Lies',
 'Ketubah',
 'Kitniyot',
 'Birthdays',
 'Monotheism',
 'Souls',
 'Gideon',
 'Nebuchadnezzar',
 'Evildoers',
 'Image of God',
 'Egypt',
 'Selichot',
 'Taharah',
 'Respect',
 'Seth',
 'Wolves',
 'Rabbi Elazar b. Azaryah',
 'Sitra Achra',
 'Psychology',
 'Sea Monsters',
 'Isaac',
 'Birth',
 'Moses and the Torah',
 'The Seven Nations',
 'Bat Mitzvah',
 'Beitar',
 'Jewish People',
 'Syria',
 'Shechem',
 'Morality',
 'Witches',
 'Ben Sorer Umoreh',
 'Bar Kokhba',
 'Trade',
 'Samson',
 'Shalom Bayit',
 'Book of Life',
 'Sumkhos',
 'Creation of the Animals',
 'Gabriel the Angel',
 'Discernment',
 'Joy',
 'Punishment',
 'Rahab',
 'Wholeness',
 'Religion',
 'Tapuach',
 "Aaron's Death",
 'Potiphar',
 'Gender',
 'Retributions during the Exodus from Egypt',
 'Praise of God',
 'Flood',
 'The Ten Commandments',
 "Moses' Blessing",
 'Rabban Shimon b. Gamliel (II)',
 'Zeresh',
 'Rabi',
 'Eve',
 'Nephilim',
 'Kehillah',
 '[Shimon] b. Azzai',
 'Mitzvot',
 'Issachar',
 'Rabbi Meir',
 'Etrog',
 'Zachor',
 'Safek',
 'Magicians',
 'Rabbi Chiyya',
 "Moses' Prayer after the Sin of the Calf",
 'Trust',
 'Haman',
 'Melchizedek',
 'Noah and the Ark',
 'Rebuke',
 'Rav Huna',
 'Abraham and Sodom',
 'Ahaz',
 'Shacharit',
 'Yom Kippur',
 'David and the Ark',
 'Planting',
 'Thoughts',
 'Creation of Water',
 'Distinctions of the Land of Israel',
 'Eye for an Eye',
 'Prophets',
 'Earth',
 "Abel's Sacrifice",
 'Covenant of Abraham',
 'Rachel',
 'Tamar',
 'Work',
 'Sorcery',
 'Laughter',
 "Balaam's Prophecy",
 'Isaiah',
 'Zeal',
 'Plague of Frogs',
 'Rabbi Yohanan Hasandlar',
 "Isaac's Wells",
 'Diaspora',
 'Leaders (פרנס)',
 'Joseph in Egypt',
 'Yom Yerushalayim',
 'Amasa',
 'Menashe (King of Judah)',
 'Sanhedrin',
 'Zevulun',
 'Cedars',
 'Journey of the Ark',
 'Miriam',
 'The Future to Come',
 'Habakkuk',
 'Snakes',
 'Egyptian Exile',
 'Kiddush',
 'Magicians and the Ten Plagues',
 'The Patriarchs',
 'Tzimtzum',
 'Malachi',
 'Honey',
 'Nature',
 'Sherets',
 'The Angel of Death',
 'Curiosity',
 'Terumah',
 'Universalism',
 'Bal Tashchit',
 'The Four Parshiot',
 'Peppers',
 'Migrants',
 'Teaching',
 'Jehoiakim',
 'Binding of Isaac',
 'Ezra',
 'Goats',
 'Zion',
 'Generation of the Dispersion',
 'Rain',
 'Meat in the Sinai Desert',
 'Fast of Gedaliah',
 'Eli',
 'Josiah',
 'Human Knowledge',
 'Power',
 'Niddah',
 'The Great Assembly',
 'Wild Animals',
 'Red Sea',
 'Amos',
 'Food',
 'Gratitude',
 'Tachanun',
 'Memory',
 'Days of Cordoning',
 'Hasmoneans',
 'Conquest of Jericho',
 "Joseph and Potiphar's Wife",
 'Hagar',
 "Hosh'ana Rabbah",
 'Bikkurim',
 'Adam',
 'Challah',
 'Menorah',
 'Aaron',
 'Evil',
 'Governments',
 'Queen of Sheba',
 'Media',
 'Civil Discourse',
 'Philosophy',
 'Boaz',
 'Moses and the Priesthood',
 "Judah's Blessing",
 'Balaam',
 'Learning',
 "Na'aman",
 'Mezuzah',
 'Sukkot',
 'Adam and Eve',
 'Judges (שופט)',
 'Chosenness',
 'Cyrus',
 'Golden Calf',
 'Migration',
 'Women in Tanakh',
 'Jewish Unity',
 'Cup of Blessing',
 'Rams',
 'Garden of Eden',
 'Fast of Gedaliah',
 'Incorporeality of God',
 'Reuben',
 'Sin of the Spies',
 'The Four Rivers',
 'Nahum of Gamzo',
 'Mice',
 'Altars',
 "Adam's Sin and His Punishment",
 'Torah Scroll',
 'Prophetess',
 'Kashrut',
 'Kindness',
 'Pomegranates',
 'Damascus',
 'Knowledge',
 'Murder',
 'Vines',
 'Assyria',
 'Dates',
 'Land',
 'Ownership',
 'The Gatherer',
 'Elijah',
 'Atonement',
 'God and Man',
 'Tyre',
 "Moses' Rebuke",
 'Aaron and the Golden Calf',
 'Protection',
 'Lambs',
 'Women',
 'Beit Midrash',
 'Israel in Egypt',
 'Willows',
 'Shemitah',
 'Responsibility',
 'Chavruta',
 'Zedekiah',
 'Moses at the Bush',
 'Presence',
 'Tikkun Olam',
 'The Exodus from Egypt',
 'Sexuality',
 'Jewish Identity',
 'Hallel',
 'Jeremiah',
 'Social Justice',
 'Moses in Midian',
 'Donkeys',
 'Halakhah',
 'The Matriarchs',
 'Sensibilities',
 'Modernity',
 '"The Children of the Angels"',
 'Camels',
 'The Nile River',
 'Parah Adumah',
 'Tzelofchad',
 'Clothing',
 'Imagination',
 'Love',
 'Golems',
 'Light',
 'Environment',
 'Naaseh Venishma',
 'Marriage',
 'Strength',
 'Ewes',
 'Race',
 'Pillar of Cloud',
 'Rabbi Hananyah b. Teradyon',
 'Vashti',
 'Lilith',
 'King Yannai',
 'Creation of Plants',
 'Values',
 'Mourning',
 'Hezekiah',
 'Compassion',
 'Giving',
 'Rabbah Bar Bar Chanah',
 'Forgiveness (מחילה)',
 "Moses and Joseph's Coffin",
 'Meaning',
 'Revelation',
 'Beauty',
 'Destruction of Jerusalem',
 'Matzah',
 'Warnings about the Ten Plagues',
 'Nineveh',
 'Ohel Moed',
 'Bread',
 'Freedom',
 'Sadness',
 'Avishai',
 "Ma'aseh Hamerkavah",
 "God's Blessing and Promise to Abraham",
 'Judah',
 'Al Hanisim',
 'Joshua',
 'Dew',
 'Service',
 'Inclusion',
 'Sacrifices',
 'Head Coverings',
 'Kabbalat Shabbat',
 'Complaints in the Desert',
 'Time',
 'Splitting of the Red Sea',
 "Moses' Prayer after the Sin of the Spies",
 'Showbread',
 'Doeg',
 "Jacob's Dream",
 'The Tree of Knowledge',
 'Encampment of Israel',
 'Covenant with the Patriarchs',
 'Seas',
 'Night',
 'Nimrod',
 'Gog and Magog',
 'Olives',
 'Ahab',
 'Passover',
 'Leviathan',
 'Tefillin',
 'Terach',
 'Children',
 'Books',
 'Abaye',
 'Jonah',
 'Technology',
 'Shalosh Regalim',
 'Wars',
 'Shimei',
 'Shabbat Prayers',
 '"In the Beginning of"',
 'Famine in Egypt',
 'Rabbi Yehoshua [b. Hananyah]',
 'Babylonian Exile',
 'Intellect',
 'Relationships',
 'Chametz',
 'Writing',
 'Numbers',
 'Tabernacle Inauguration',
 'Jacob and the Birthright',
 'Prophecy of Abraham',
 'The House of David',
 'Dogs',
 'Noah',
 'Gad',
 'Counting of the Levites',
 'Simchat Torah',
 'Yirat Shamayim',
 'The Sons of Korach',
 'Sisera',
 'Abigail',
 "Moses' Prophecy",
 'Spirituality',
 "Moses' Knowledge",
 'Creativity',
 'Niggun',
 'Rome',
 'Samael',
 'Bodies',
 'Meat',
 'David and Batsheva',
 'Noah and the Vineyard',
 "Ma'aser Sheni",
 'Roosters',
 'Creation of Man',
 'Oils',
 'Kippah',
 'Masculinity',
 'Divorce',
 "Cain's Sacrifice",
 'Arvit',
 'Germany',
 'Honoring Parents',
 'King David',
 'Kaddish',
 'Birthright',
 'Tzitzit',
 'The Written Torah and the Oral Torah',
 'Nadav and Avihu',
 'Seven Species',
 'Generation of Enosh',
 'The Elements',
 'Babel',
 'Poor',
 'Achitofel',
 'Forgiveness',
 'Harmful Forces',
 'Jesse',
 'Disabilities',
 'Jacob in Egypt',
 'The Ten Plagues',
 'Shimon Bar Yochai',
 'Destruction of the Temple',
 'Rabbinic Authority',
 "Moses' Death and Burial",
 'Love of God',
 'Divine Names',
 'Burial',
 'The Sale of Joseph',
 'Drinking',
 'Death',
 'Oral Torah',
 'Sleep',
 'Beruriah',
 'Hannah',
 'Birkot Hashachar',
 'Elisha Ben Abuya',
 'Seder',
 'Haggadah',
 'Political Thought',
 'Peace',
 'Jericho',
 'Plague of Darkness',
 'Tiberias',
 'Benjamin',
 'Man and Animals',
 'Fertility',
 'Serah the Daughter of Asher',
 'Disability',
 'Pluralism',
 'Rabbi Tarfon',
 'Birkat HaMazon',
 'Incense',
 "Pharaoh's Dream",
 'Galil',
 'Jeroboam (Son of Nebat)',
 'Happiness',
 'Friendship',
 'Judith',
 'Agency',
 'New Year',
 'Ham',
 'Asher',
 'Tekhelet',
 'Hitbodedut',
 "Jacob's Oath",
 'Mishloach Manot',
 'Infertility',
 'Beit Din',
 'Edom and the Generation of the Desert',
 'Moab',
 '13 Principles of Faith',
 'Avtalyon',
 'Shem',
 'Ahasuerus',
 'Rav Chisda',
 'Exile',
 'Moses and the Tablets',
 'Song of the Sea',
 "Joseph's Dream",
 'Innovation',
 'Head Covering',
 'Ruth',
 'Vegetarianism',
 'Democracy',
 'Candles',
 'Yetzer Hatov',
 'Yoash (King of Judah)',
 'Human Dignity',
 'Free Will',
 'The Book of Esther',
 'Elisha',
 'Plague of the Firstborn',
 'Manna',
 'Superstitions',
 'Effect of Sin',
 "God's Will",
 'Physicians',
 'Middot',
 'Spring',
 'Rabbi Chanina b. Dosa',
 'Og',
 'Yavneh',
 'Deborah',
 'Mentally Handicapped People',
 'Moses and the Tent of Meeting',
 'Donations for the Tabernacle',
 'Shmuel (Amora)',
 'Rav Pappa',
 'Visiting the Sick',
 'Mishkan',
 'Motzi',
 'Pinchas',
 'Sennacherib',
 'Bioethics',
 'Summer',
 'Gift Giving',
 'Vulnerability',
 'Shofar',
 'War with Midian',
 'Argument',
 'Tarshish',
 'Burning Bush',
 'Agriculture',
 'Moriah',
 'Carefulness',
 'Courage',
 'Justice',
 'Air',
 'Rituals',
 'Moses and the Egyptian',
 'Business',
 'Four Cups',
 "Jacob's Burial",
 'Purim',
 'Shmuel the Little',
 'Mah Tovu',
 'Frogs',
 'Locusts',
 'Redemption of Captives',
 'Miracles',
 'Shabbat Hagadol',
 'Yetzer Hara',
 "Moses' Signs",
 'Obadiah',
 'Beersheba',
 'Astronomy',
 'Lashon Hara',
 'Dirt',
 'Modern Thought',
 'Losses',
 'Wisdom',
 'Avodat Hashem',
 'Elkanah',
 'The Ten Days of Repentance',
 'Partitions',
 'Clouds',
 'Well in the Desert',
 'Olam Haba',
 'Shavuot',
 'Life',
 'Yom HaAtzmaut',
 'Creation',
 'Reality',
 "V'ahavta",
 'Mindfulness',
 'Joseph',
 'Neshama',
 'Rava',
 'Tzedakah',
 'Knowing',
 'Rabbi Shimon b. Lakish',
 'The Waters of Meribah',
 'David and the Temple',
 'Joseph and the Wine Steward',
 'Rivers',
 'Jacob',
 'Ishmael',
 'Perspective',
 'Thanks',
 'Tumah',
 'Borrowing the Property during the Exodus from Egypt',
 'Jacob and the Sticks',
 'High Holidays',
 'Agunah',
 'Abraham and the Hittites',
 'Isaac and Esau',
 'Abraham in Ur Kasdim and his Departure from There',
 'Reincarnation',
 'Conquest and Division'];

  const he_en = ['Peppers',
 'Simchat Torah',
 'Partitions',
 'פסיכולוגיה',
 'מציאות',
 'תבלין',
 'מוות',
 'Cup of Blessing',
 'Rabbi Yehoshua [b. Hananyah]',
 'הר הבית',
 'The Copper Altar',
 'שְׁלֹמֹה',
 'שמונה עשרה',
 '[Yochanan] Ben Bag Bag',
 'גר',
 'Travel',
 'Leah',
 'Olam Haba',
 'חרבן ארץ ישראל',
 'The Tablets',
 'Hashkiveinu',
 'עגל הזהב',
 'Joseph',
 'זכריה',
 'Matzah',
 'שוטה',
 'סמכות',
 'Books',
 "Jacob's Burial",
 'Creation of Plants',
 'יופי',
 'Bodies',
 'Counting of the Levites',
 'חנוכה',
 'Flax',
 "Moses' Knowledge",
 'התראה בעשר המכות',
 'Birth',
 'Migrants',
 'מכת דם',
 'קטניות',
 'Creation of the Animals',
 'Tikkun Olam',
 'Beruriah',
 'מלחמות דוד',
 'National Library of Israel',
 'בן סורר ומורה',
 'נרות',
 'Holiness',
 'ישעיהו',
 'דמיון',
 '[Shimon] b. Azzai',
 'Gazelles',
 'Michael',
 'Goliath',
 'ספר תורה',
 'באר שבע',
 'סנה בוער',
 'מכשפה',
 'The Waters of Meribah',
 'יוסף ושר המשקים',
 'Zimri',
 'Jubilee',
 'Discernment',
 'Rabbi Elazar b. Azaryah',
 'Management',
 'שלושה רגלים',
 'שרה',
 'Cain',
 'גולם',
 'Memory',
 'Hashgacha',
 'Ishmael',
 'Journey in the Desert',
 'יין',
 'שמעי',
 'ראש חודש',
 'רב חסדא',
 'ישר',
 'Expertise',
 'Yetzer Hatov',
 'Listening',
 'Adam',
 'מעשה המשכן',
 'בנימין',
 'פולקלור',
 'Fear (פחד)',
 'רבן גמליאל דיבנה',
 'The Four Rivers',
 'שתילה',
 'Welcoming',
 'צבי',
 'Death',
 'שת',
 'Morality',
 'זהות יהודית',
 'מזוזה',
 'Inauguration of the Temple',
 'קרבן',
 'נבואת בלעם',
 'Service',
 'Rabbi Hananyah b. Teradyon',
 'Alexandria',
 'בארות יצחק',
 'Jerusalem',
 'ארץ',
 'ענוה',
 'חכמה',
 'שור',
 'Nephilim',
 'סקרנות',
 'Mitzvot',
 'Appointment of Judges for The Generation of the Desert',
 'Temple Vessels',
 'סנחריב',
 'רבי חנינה בן תרדיון',
 'Eagles',
 'הִלֵּל',
 'ארבעה יסודות',
 'סוס',
 'Birds',
 'Heavens',
 'Jacob in Egypt',
 'Vashti',
 'רשע',
 'הגר',
 'Rahab',
 'פוריות',
 'Jacob',
 'Red Sea',
 'בקיאות',
 'יונה הנביא',
 'ר יהושע',
 'Tashlich',
 'ידיעת השם',
 'Dreams',
 'אחשוורוש',
 'The Ten Commandments',
 'Compassion',
 'רופא',
 'שמחה',
 'אמהות',
 'חלום',
 'Seven Species',
 'The Ten Plagues',
 'Adar',
 'Moses in Midian',
 'Food Ethics',
 'נפילים',
 'Damascus',
 'Revenge',
 'שנאה',
 'מכת ערוב',
 'Ever HaYarden',
 'Babylonian Exile',
 'Zion',
 'נחש',
 'Jewish Identity',
 'Wisdom',
 'Rebuke',
 'עבודה זרה',
 'Civil Discourse',
 'יאשיהו',
 'Neshama',
 'עפר',
 'King Saul',
 'Galil',
 'Isaac',
 'רחמים',
 'ברכות השחר',
 'משה במדין',
 'יצחק ועשו',
 'רבי יהושע בן לוי',
 'Governments',
 'שבועות',
 'ביכורים',
 'Comfort',
 'ברכת יעקב',
 'Covenant of Abraham',
 'ניגון',
 'Hunger',
 'Sea Monsters',
 'The Sons of Eli',
 'Piyyut',
 'תחנון',
 'בטחון',
 'Punishment',
 'Rosh Hashanah',
 'פרד',
 'Libations',
 'En Dor',
 "David's Wars",
 "Mourner's Kaddish",
 'שמחת תורה',
 'גמל',
 'גהינום',
 'חיה',
 'Eve',
 'Golden Calf',
 'Giving',
 'Candles',
 'King Solomon',
 'המלך שאול',
 "Judah's Blessing",
 'Rav Zera',
 'גלגול נשמות',
 'Ruach Hakodesh',
 'עושר',
 'הקורבנות במדבר',
 'Harmful Forces',
 'אמונה',
 'חוה',
 'Ahaz',
 'תפילת ערבית',
 'נפש',
 'מפקד',
 'Jonah',
 'Social Justice',
 'Zachor',
 'הר המוריה',
 'The Angel of Death',
 'שכל',
 'שלילת גשמות האל',
 'Abraham and the Hittites',
 'מידות',
 'Hallel',
 'דעת',
 'שמעון',
 'מצרים',
 'Isaac and Esau',
 'יהונדב בן רכב',
 'The Sale of Joseph',
 'חָלָב',
 'Days of Cordoning',
 'Resurrection',
 'Ahab',
 'Ketubah',
 'יעקב והמקלות',
 'מלכת שבא',
 'משה והמצרי',
 'ליל הסֵדֶר',
 'Yahrzeit',
 'ציפורים',
 'Asa',
 'שכם',
 'Satan',
 'בית המקדש',
 'זיכרון',
 'ברכת יצחק',
 'Rabban Gamliel of Yavneh (II)',
 'שדים',
 'תמרים',
 'The Idol of Micha',
 'גזענות',
 'Tapuach',
 'Hitbodedut',
 'Zeal',
 'דוד ובת שבע',
 'קרח',
 'Agunah',
 'Doves',
 'פעולת המצווה',
 'ידיעה אנושית',
 'Creation of Man',
 'עץ החיים',
 'מעין',
 'Azazel',
 'Creation of Heavens and Earth',
 'Deserts',
 'ממשלה',
 'עֲבוֹדָה',
 'Man and Wife',
 'Praise of God',
 'יהודה',
 'חטא המרגלים',
 'Responsibility',
 'מסע הארון',
 'מחיצה (כללי)',
 'Mount Sinai',
 "God's Blessing and Promise to Abraham",
 'Miriam',
 'Korach',
 'Book of Life',
 'Zevulun',
 'נדבת המשכן',
 'הבדלה',
 'נדרים',
 'Golems',
 'אנשי כנסת הגדולה',
 'ארם',
 'Daniel',
 'עכבר',
 'חור',
 'יהושע',
 'Tumah',
 'מצוות',
 'חם',
 'Raising Up and Anointing the Tabernacle',
 'עמוד ענן',
 'The Gatherer',
 'David and Batsheva',
 'The Four Expressions of Redemption',
 'Moses and the Egyptian',
 'סנהדרין',
 'מינוי דיינים בדור המדבר',
 'Wine',
 'חטא הנחש ועונש',
 'סטרא אחרא',
 'Tabernacle Courtyard',
 'שבעת העממים',
 'שכינה',
 'דמוקרטיה',
 'שירת הים',
 'מכת חושך',
 'Tiberias',
 'Plague of Blood',
 'Jewish People',
 'Mules',
 'שֵׁרוּת',
 'שמשון',
 'Human Dignity',
 'Kush',
 'Omer Offering',
 'קרבן העומר',
 'אברהם והמלכים',
 'בית אל',
 'Flour',
 'Sorcery',
 'Leviathan',
 'Incorporeality of God',
 'תרומה',
 'רוע',
 'אבלות',
 'Altars',
 'צמיחה',
 'Magicians',
 'הפסד',
 'יששכר',
 'דור הפלגה',
 'זהות',
 "Joseph's Dream",
 'לעתיד לבא',
 'פרעה',
 'Angels',
 'Water',
 'Potiphar',
 'Art',
 'Prophecy of Abraham',
 'נמלה',
 'Showbread',
 'Generosity',
 'אכילה',
 'Rabbi Tarfon',
 'פסח',
 "Pharaoh's Daughter",
 'תודה',
 'סדום',
 'Unity',
 'בכורה',
 'Tikkun',
 'אלכוהול',
 'Writing',
 'שליחות',
 'Moriah',
 'Abaye',
 'Plague of Locusts',
 'קין',
 'רב אשי',
 'Zechariah',
 'Plants',
 'מזבחות',
 'Planting',
 'Liberation',
 'ינאי המלך',
 'Chametz',
 'ערי הלויים',
 'אָמָּנוּת',
 'Beit Midrash',
 'צמח',
 'Haggadah',
 'Impulses',
 "Moses' Blessing",
 'Kashrut',
 'לילית',
 'Image of God',
 'איל',
 'שנאת חינם',
 'Food',
 'נתינה',
 'אביגיל',
 'Rachel',
 'Tests of Abraham',
 'עץ',
 'רוחניות',
 'Taharah',
 'Abraham and the Kings',
 'Light',
 'Judges (שופט)',
 'Sefirot (Kabbalah)',
 'טענה',
 'Strength',
 'Women',
 'Israel',
 'Sin of Peor',
 'בית דוד',
 'חטא פעור',
 'גוף',
 'Joseph and the Wine Steward',
 'War with Midian',
 'מלכי צדק',
 'המוציא',
 'Bal Tashchit',
 'נס',
 'Chanukkah',
 'הומור',
 'אליהו',
 'בלעם',
 'Mezuzah',
 'Fertility',
 'Weather',
 'ארץ יהודה',
 'השרון',
 'Terumah',
 'הקמת המשכן ומשיחתו',
 'Nebuchadnezzar',
 'כבוד אנושי',
 'Spices',
 'חברה (סביבה אנושית)',
 'חיים',
 'Boaz',
 'דבר',
 'Respect',
 'Song of the Sea',
 'אלול',
 'יעקב ומצרים',
 "Moses' Prophecy",
 'Plague of Wild Animals',
 'ישמעאל',
 'חתול',
 'Modern Thought',
 'Chanukah Menorah',
 'Rabbi Yehoshua b. Levi',
 'Faith',
 'The Written Torah and the Oral Torah',
 'בנות צלפחד',
 'פינחס',
 'Plague of Lice',
 'ראובן',
 'Mishkan',
 'שלמות',
 'Witches',
 'ירמיהו',
 'כלי תקשורת',
 '[Shimon] b. Zoma',
 'שמיני עצרת',
 'Moses and the Tent of Meeting',
 'Prophetess',
 "Tabernacle's Journey",
 'שמעון בן שטח',
 'Astronomy',
 'Wheat',
 'Crossing the Jordan River and Setting of the Stones',
 'Syria',
 'Folklore',
 'צחוק',
 'קרבן הבל',
 'טבריה',
 'קטורה',
 'King Yannai',
 'Kehillah',
 "Hosh'ana Rabbah",
 'Deborah',
 'Sin of the Spies',
 'עכן',
 'Fast of Gedaliah',
 'מלאכים',
 'כרמל',
 'Chosenness',
 'ברכות',
 'יריחו',
 'Perspective',
 'מוגבלות',
 'Leaders (פרנס)',
 'תורה שבכתב ושבעל פה',
 'Dances',
 'Josiah',
 'החרטומים בעשר המכות',
 'ספר',
 "Moses' Prayer after the Sin of the Calf",
 'שירים',
 'מצה',
 "Adam's Sin and His Punishment",
 'Miracles',
 'Shekhinah',
 'Rabi',
 'עוזיה',
 'אמא',
 'Exile',
 'גלות מצרים',
 'Sorcery (קסם)',
 'Jeroboam (Son of Nebat)',
 'בחירה חופשית',
 'Edom',
 'Vulnerability',
 'נעשה ונשמע',
 'Grapes',
 'The Nile River',
 'אדם הראשון',
 'Ruth',
 'Ravens',
 'שכנים',
 'Four Questions',
 'רב פפא',
 'חדשנות',
 'HaSharon',
 'עין תחת עין',
 'Elul',
 "י' בטבת",
 'Magicians and the Ten Plagues',
 "Tabernacle's Making",
 'Purim',
 'נילוס',
 'שמן',
 'Marriage',
 'Honey',
 'Freedom',
 'בית שני',
 'מלאכי',
 'Jonadab, the Son of Rechab',
 'Forgiveness',
 'Modernity',
 'הגנה',
 'Empathy',
 'עשרת ימי תשובה',
 'Shimon b. Shetach',
 'Protection',
 'Giving of the Torah',
 'אוניברסליזם',
 'מלחמת מדיין',
 'תן ותנין',
 'Rabbi Akiva',
 'Ezekiel',
 'Neighbors',
 'מה טובו',
 "אהבת ה'",
 'Non Jews',
 'סבר פנים',
 'Rain',
 'חנכת בית המקדש',
 'The Effects of a Commandment',
 'יתרו',
 "עבודת ה'",
 'לימוד תורה',
 'כוח',
 'אברהם והמלאכים',
 'הסכמה',
 'Ahasuerus',
 'רבי מאיר',
 'The Tabernacle in Shiloh',
 'Meat in the Sinai Desert',
 'The Worship of Molech',
 'ערבה (עץ)',
 'Rabbi Meir',
 'עוג',
 'פמיניזם',
 "Cain's Sacrifice",
 'Birthright',
 'משכן שילה',
 'The Ten Tribes',
 'שותפות',
 'דור המבול',
 'עולם הזה',
 'עצמאות',
 'קרבן קין',
 'Ephraim',
 'דוד המלך',
 'סוריה',
 'Ezra',
 'Passover',
 'יוחנן בן בג בג',
 'בריאת הצמחים',
 'God and Man',
 'Motzi',
 'דיני מתנות ותרומות',
 'Human Knowledge',
 'Happiness',
 'ריקוד',
 'ההבטחה ליעקב',
 'Silence',
 'קרבן נח',
 'עוני',
 'מעלות ארץ ישראל',
 'וידוי',
 'Lulav',
 'Birthdays',
 'ארבע כוסות',
 'לולב',
 'Yetzer Hara',
 'Israel in Egypt',
 'Havdalah',
 'Rabban Shimon b. Gamliel (II)',
 'גבורה',
 'אבטליון',
 'נוחות',
 'Racism',
 'Baseless Hatred',
 'בר כוכבא',
 'מוסיקה',
 'Elisha',
 'רבי',
 'יום הולדת',
 'מעשה מרכבה',
 'Students',
 'תפילת שחרית',
 'Judith',
 'יהודית',
 'Eli',
 'בריאת בעלי החיים',
 'Kabbalat Shabbat',
 "Jacob's Oath",
 'Jeremiah',
 'כשרות',
 'Germany',
 'Pigs',
 'טוב',
 "Aaron's Death",
 'פרנס',
 'מכת כינים',
 'מבול',
 'Lag BaOmer',
 'גחזי',
 'The House of David',
 'קהילה',
 'Knowing God',
 'Generation of the Dispersion',
 'Second Temple',
 'Lambs',
 'על הניסים',
 'ימי הגבלה',
 'סליחות',
 'Sarah',
 'Parents',
 'Amos',
 'כבש',
 'כפרה',
 'שמואל (שם אמורא)',
 'Jacob and the Sticks',
 'עשרת הדיברות',
 'Moses and Israel',
 'Shifrah and Puah',
 'Ham',
 'Locusts',
 'Burial',
 'שעבוד מצרים',
 'עורב',
 "Balaam's Prophecy",
 'המרגלים',
 'Shabbat Candles',
 'David and the Ark',
 'Heretics',
 'תשליך',
 'Benjamin',
 'רות',
 'עשרת השבטים',
 'לידת משה',
 'Gad',
 'Sin and Punishment of the Serpent',
 'אמונה טפלה',
 'הר',
 'Tzara’at',
 'אתיקה',
 'Temple Mount',
 "Na'aman",
 'צמצום',
 'תֵּבֵל',
 'דן',
 'War with Amalek',
 'איש ואשה',
 'אביי',
 'Humanity',
 'Kiddush',
 'Souls',
 'התלונות במדב',
 'The Book of Esther',
 'Disability',
 'Babel',
 'Idolatry',
 'Deceit',
 'Generation of the Flood',
 'נינוה',
 'Middot',
 'Lilies',
 'Habakkuk',
 'רבי טרפון',
 'שופר',
 'Seth',
 'Yom Kippur',
 'Women in Tanakh',
 'מרה',
 'תלמיד',
 'גבריות',
 'Judah',
 'מכת בכורות',
 'פסל מיכה',
 "Ma'aseh Hamerkavah",
 'Poverty',
 'Gog and Magog',
 'חבקוק',
 'Teaching',
 'רבן שמעון בן גמליאל (2)',
 'Wars',
 'פשתים',
 'Divine Names',
 'Argument',
 'Wolves',
 'Menorah',
 'אדר',
 'בריאת שמים וארץ',
 'מכת שחין',
 'צום גדליה',
 'Air',
 'טקס',
 'שפרה ופועה',
 'בר מצווה',
 'Nadav and Avihu',
 'Songs',
 'Cedars',
 'Sanhedrin',
 'שבת הגדול',
 'שושנה',
 'צדקיהו',
 'יצר הרע',
 'התבודדות',
 'זהירות',
 'הושענא רבה',
 'עולם הבא',
 'חירם',
 'Kindness',
 'Trees',
 'אלישע',
 'הלכה',
 'נכות',
 'הדס',
 'נידה',
 'בני קרח',
 'מחשבה',
 'Egypt',
 'מואב',
 'Joy',
 'Priesthood',
 'נדב ואביהוא',
 'בית דין',
 'Psychology',
 'ברכת יוסף',
 'Zedekiah',
 'The Matriarchs',
 'Moses and the Torah',
 'מעשר שני',
 'מציאות אלקים',
 'יבנה',
 'Honesty',
 'בעלי חיים',
 'Bikkurim',
 'Lot',
 'Goats',
 'הבאר במדבר',
 'The Messianic Era',
 'ארבעת הבנים',
 'Political Thought',
 'Outside of Israel',
 'Sacrifices in the Desert',
 'קטורת',
 'קבורת יעקב',
 'כסף',
 'Gideon',
 'Greece',
 'ברכת לוי',
 'Sustainability',
 'עץ הדעת',
 'דוד ובית המקדש',
 'Universalism',
 'מלך',
 'Clothing',
 'קריאת שמע',
 'המלאך גבריאל',
 'שנה חדשה',
 'חברות',
 'Love Your Neighbor as Yourself',
 'Inclusion',
 'Rehoboam',
 'הַלֵּל',
 'The Elements',
 'Letters',
 'Bat Kol',
 'אושר',
 'כהונה',
 'Frogs',
 'Shema',
 'לילה',
 "Noah's Sacrifice",
 'אש',
 'קנאות',
 'Plague of Pestilence (דֶּבֶר )',
 'רצון אלקים',
 'שאלות',
 'Creativity',
 'אור',
 'Meat',
 'הבל',
 'Scorpions',
 'Spring',
 'בת מצווה',
 'Manna',
 'מלאך המות',
 'Niddah',
 'Tzimtzum',
 'Mistakes',
 'Plague of Boils',
 'Disabilities',
 'ראש השנה',
 'אדוניה',
 'זבולון',
 'Shmuel the Little',
 'Race',
 'Peace',
 'מכירת יוסף',
 'Figs',
 'פרה אדומה',
 'יצר טוב',
 'Absalom',
 'Father',
 'Imagination',
 'Demons',
 'עקרות',
 'דור המדבר',
 'לידה',
 'מנהיגות',
 'עושק',
 'Torah Study',
 'יונה',
 'Identity',
 'יוסף ואשת פוטיפר',
 'רבי אלעזר בן עזריה',
 'תקוה',
 'Rabbah Bar Bar Chanah',
 'צבע',
 'נביאה',
 'קבלת שבת',
 'צור',
 'חורבן בבל',
 'Mount Gerizim and Mount Ebal',
 'The Ocean',
 'מכת ברד',
 'פעולה',
 'Minhag',
 'Calendar',
 'Myrtles',
 'Thanks',
 'Health',
 'ציון',
 'Eating',
 'Intellect',
 'Tamar',
 'Knowledge',
 'חינוך',
 'עלינו',
 'נשמה יתרה',
 'חמור',
 'יוכבד',
 'שתיקה',
 'Trade',
 'Rebecca',
 'בראשית',
 'רחבעם',
 'Burning Bush',
 'פדיון הבן',
 'Reality',
 'התגלות',
 'Aram',
 'Shalom Bayit',
 'עם ישראל',
 'Ohel Moed',
 'כיפה',
 'שימת לב',
 'Gabriel the Angel',
 'ערכים',
 'בני עלי',
 'חלום פרעה',
 'Serah the Daughter of Asher',
 'חיות',
 'Moses and the Tablets',
 'אלוהים',
 'שמות קדושים',
 'נסיעה',
 'נזיר',
 'Love of God',
 'Moses',
 'גדעון',
 'תרנגול',
 'לחם הפנים',
 'אהבה',
 'עמלק',
 'גיור',
 'Rav Sheshet',
 'פרטיקולריות',
 'Purpose of Life',
 'כלי המקדש',
 'Etrog',
 'יובל',
 'שלג',
 'קדיש יתום',
 'Bar Kokhba',
 'Flood',
 'Daughters of Tzelofchad',
 'קיימות',
 'Abraham',
 'כיבוד הורים',
 'Earth',
 'גזרת הבנים',
 'ביואתיקה',
 'ביקור חולים',
 'מזבח הנחושת',
 'אחז',
 'Sisera',
 'Humor',
 'Naaseh Venishma',
 'Edom and the Generation of the Desert',
 'Winds',
 'הכנסת אורחים',
 'Ewes',
 'Seas',
 "Isaac's Blessing",
 'Cities',
 'אלקנה',
 'אברהם במצרים',
 'Tallit',
 'Eliezer',
 'הנהלה',
 'Plague of Hail',
 'מגדל בבל',
 'מין',
 'Stopping of the Sun in Gibeon',
 'ארז',
 'Moses and the Priesthood',
 'Workers',
 'אחיתופל',
 'שטן',
 'דבקות',
 'Shabbat Prayers',
 'Shalosh Regalim',
 'בועז',
 'אשר',
 'The Book of Ruth',
 'תורה שבעל פה',
 'Jacob and the Angel',
 'תיקון עולם',
 'גליל',
 'Avodat Hashem',
 'צלם אלוקים',
 'יצרים',
 'תרח',
 'Clouds',
 'תחיית המתים',
 'Rabbi Yohanan Hasandlar',
 'לוח שנה',
 'Amram',
 'Mah Tovu',
 'מנורה',
 'Inspiration',
 'Physicians',
 'השכיבנו',
 'High Holidays',
 'Destruction of Jerusalem',
 'השראה',
 'שאלת הרכוש ביציאת מצרים',
 'יוסף',
 'כבוש יריחו',
 'Parah Adumah',
 'Jehoiakim',
 'המסע במדבר',
 'Rosh Chodesh',
 'Aaron and the Golden Calf',
 'תיבת נח',
 'Technology',
 'קדיש',
 'הקשבה',
 'חלום יעקב',
 '"The Children of the Angels"',
 'עבודת המולך',
 'The Promise to Jacob',
 'הר גריזים ועיבל',
 'Oils',
 'Energy',
 'Land',
 'פגיעות',
 'ספק',
 'תהילת אלקים',
 'חטא אדם הראשון ועונשו',
 'Plague of Frogs',
 'Noah and the Vineyard'];
