  const phrase_objects = [{'slug': 'shabbat', 'en': 'Shabbat', 'he': 'שבת', 'cat': 'jewish-calendar2'},
 {'slug': 'rosh-chodesh',
  'en': 'Rosh Chodesh',
  'he': 'ראש חודש',
  'cat': 'jewish-calendar2'},
 {'slug': 'rosh-hashanah',
  'en': 'Rosh Hashanah',
  'he': 'ראש השנה',
  'cat': 'jewish-calendar2'},
 {'slug': 'yom-kippur',
  'en': 'Yom Kippur',
  'he': 'יום כיפור',
  'cat': 'jewish-calendar2'},
 {'slug': 'sukkot', 'en': 'Sukkot', 'he': 'סוכות', 'cat': 'jewish-calendar2'},
 {'slug': 'the-four-species',
  'en': 'The Four Species',
  'he': 'ארבעת המינים',
  'cat': 'ritual-objects'},
 {'slug': 'shemini-atzeret',
  'en': 'Shemini Atzeret',
  'he': 'שמיני עצרת',
  'cat': 'jewish-calendar2'},
 {'slug': 'simchat-torah',
  'en': 'Simchat Torah',
  'he': 'שמחת תורה',
  'cat': 'jewish-calendar2'},
 {'slug': 'chanukkah',
  'en': 'Chanukkah',
  'he': 'חנוכה',
  'cat': 'jewish-calendar2'},
 {'slug': 'tu-bishvat',
  'en': 'Tu Bishvat',
  'he': 'ט"ו בשבט',
  'cat': 'jewish-calendar2'},
 {'slug': 'purim', 'en': 'Purim', 'he': 'פורים', 'cat': 'jewish-calendar2'},
 {'slug': 'passover',
  'en': 'Passover',
  'he': 'פסח',
  'cat': 'jewish-calendar2'},
 {'slug': 'shavuot',
  'en': 'Shavuot',
  'he': 'שבועות',
  'cat': 'jewish-calendar2'},
 {'slug': 'tisha-bav',
  'en': "Tisha B'Av",
  'he': 'תשעה באב',
  'cat': 'jewish-calendar2'},
 {'slug': 'fasting',
  'en': 'Fasting',
  'he': 'תענית',
  'cat': 'jewish-calendar2'},
 {'slug': 'tu-bav',
  'en': "Tu B'Av",
  'he': 'ט"ו באב',
  'cat': 'jewish-calendar2'},
 {'slug': 'lag-baomer',
  'en': 'Lag BaOmer',
  'he': 'ל"ג בעומר',
  'cat': 'jewish-calendar2'},
 {'slug': 'sefirat-haomer',
  'en': 'Sefirat HaOmer',
  'he': 'ספירת העומר',
  'cat': 'jewish-calendar2'},
 {'slug': 'the-ten-days-of-repentance',
  'en': 'The Ten Days of Repentance',
  'he': 'עשרת ימי תשובה',
  'cat': 'jewish-calendar2'},
 {'slug': 'shabbat-hagadol',
  'en': 'Shabbat Hagadol',
  'he': 'שבת הגדול',
  'cat': 'jewish-calendar2'},
 {'slug': 'high-holidays',
  'en': 'High Holidays',
  'he': 'הימים הנוראים',
  'cat': 'jewish-calendar2'},
 {'slug': 'seder',
  'en': 'Seder',
  'he': 'ליל הסֵדֶר',
  'cat': 'jewish-calendar2'},
 {'slug': 'hagaddah', 'en': 'Hagaddah', 'he': '', 'cat': ''},
 {'slug': 'new-year',
  'en': 'New Year',
  'he': 'שנה חדשה',
  'cat': 'jewish-calendar2'},
 {'slug': 'yom-yerushalayim',
  'en': 'Yom Yerushalayim',
  'he': 'יום ירושלים',
  'cat': 'jewish-calendar2'},
 {'slug': 'asarah-betevet',
  'en': 'Asarah BeTevet',
  'he': "י' בטבת",
  'cat': 'jewish-calendar2'},
 {'slug': 'shivah-asar-betammuz',
  'en': 'Shivah Asar BeTammuz',
  'he': 'שבעה עשר בתמוז',
  'cat': ''},
 {'slug': 'yom-haatzmaut',
  'en': 'Yom HaAtzmaut',
  'he': 'יום העצמאות',
  'cat': 'jewish-calendar2'},
 {'slug': 'sigd', 'en': 'Sigd', 'he': 'חג הסיגד', 'cat': 'jewish-calendar2'},
 {'slug': 'elul', 'en': 'Elul', 'he': 'אלול', 'cat': 'jewish-calendar2'},
 {'slug': 'four-questions',
  'en': 'Four Questions',
  'he': 'ארבע קושיות (מה נשתנה)',
  'cat': 'jewish-calendar2'},
 {'slug': 'the-four-children',
  'en': 'The Four Children',
  'he': 'ארבעת הבנים',
  'cat': 'jewish-calendar2'},
 {'slug': 'the-four-expressions-of-redemption',
  'en': 'The Four Expressions of Redemption',
  'he': 'ארבע לשונות גאולה',
  'cat': 'jewish-calendar2'},
 {'slug': 'fast-of-gedaliah',
  'en': 'Fast of Gedaliah',
  'he': 'צום גדליה',
  'cat': 'jewish-calendar2'},
 {'slug': 'hoshana-rabbah',
  'en': "Hosh'ana Rabbah",
  'he': 'הושענא רבה',
  'cat': 'jewish-calendar2'},
 {'slug': 'the-patriarchs',
  'en': 'The Patriarchs',
  'he': 'אבות',
  'cat': 'biblical-figures'},
 {'slug': 'abigail',
  'en': 'Abigail',
  'he': 'אביגיל',
  'cat': 'biblical-figures'},
 {'slug': 'avishai',
  'en': 'Avishai',
  'he': 'אבישי',
  'cat': 'biblical-figures'},
 {'slug': 'abner', 'en': 'Abner', 'he': 'אבנר', 'cat': 'biblical-figures'},
 {'slug': 'abraham',
  'en': 'Abraham',
  'he': 'אברהם',
  'cat': 'biblical-figures'},
 {'slug': 'absalom',
  'en': 'Absalom',
  'he': 'אבשלום',
  'cat': 'biblical-figures'},
 {'slug': 'achitofel',
  'en': 'Achitofel',
  'he': 'אחיתופל',
  'cat': 'biblical-figures'},
 {'slug': 'adoniah',
  'en': 'Adoniah',
  'he': 'אדוניה',
  'cat': 'biblical-figures'},
 {'slug': 'adam', 'en': 'Adam', 'he': 'אדם הראשון', 'cat': 'biblical-figures'},
 {'slug': 'adam-and-eve',
  'en': 'Adam and Eve',
  'he': 'אדם וחוה',
  'cat': 'biblical-figures'},
 {'slug': 'aaron', 'en': 'Aaron', 'he': 'אהרון', 'cat': 'biblical-figures'},
 {'slug': 'ahab', 'en': 'Ahab', 'he': 'אחאב', 'cat': 'biblical-figures'},
 {'slug': 'ahaz', 'en': 'Ahaz', 'he': 'אחז', 'cat': 'biblical-figures'},
 {'slug': 'jezebel',
  'en': 'Jezebel',
  'he': 'איזבל',
  'cat': 'biblical-figures'},
 {'slug': 'elijah', 'en': 'Elijah', 'he': 'אליהו', 'cat': 'biblical-figures'},
 {'slug': 'elimelekh1',
  'en': 'Elimelekh',
  'he': 'אלימלך',
  'cat': 'biblical-figures'},
 {'slug': 'elifaz1', 'en': 'Elifaz', 'he': 'אליפז', 'cat': 'biblical-figures'},
 {'slug': 'elisheva',
  'en': 'Elisheva',
  'he': 'אלישבע',
  'cat': 'biblical-figures'},
 {'slug': 'elisha', 'en': 'Elisha', 'he': 'אלישע', 'cat': 'biblical-figures'},
 {'slug': 'elazar', 'en': 'Elazar', 'he': 'אלעזר', 'cat': 'biblical-figures'},
 {'slug': 'elkanah',
  'en': 'Elkanah',
  'he': 'אלקנה',
  'cat': 'biblical-figures'},
 {'slug': 'the-matriarchs',
  'en': 'The Matriarchs',
  'he': 'אמהות',
  'cat': 'biblical-figures'},
 {'slug': 'asa', 'en': 'Asa', 'he': 'אסא', 'cat': 'biblical-figures'},
 {'slug': 'esther', 'en': 'Esther', 'he': 'אסתר', 'cat': 'biblical-figures'},
 {'slug': 'ephraim',
  'en': 'Ephraim',
  'he': 'אפרים',
  'cat': 'biblical-figures'},
 {'slug': 'aram', 'en': 'Aram', 'he': 'ארם', 'cat': 'biblical-figures'},
 {'slug': 'boaz', 'en': 'Boaz', 'he': 'בועז', 'cat': 'biblical-figures'},
 {'slug': 'balaam', 'en': 'Balaam', 'he': 'בלעם', 'cat': 'biblical-figures'},
 {'slug': 'belshatzar',
  'en': 'Belshatzar',
  'he': 'בלשאצר',
  'cat': 'biblical-figures'},
 {'slug': 'benjamin',
  'en': 'Benjamin',
  'he': 'בנימין',
  'cat': 'biblical-figures'},
 {'slug': 'barukh-ben-neriah',
  'en': 'Barukh ben Neriah',
  'he': 'ברוך בן נריה',
  'cat': 'biblical-figures'},
 {'slug': 'gad', 'en': 'Gad', 'he': 'גד (שבט)', 'cat': 'biblical-figures'},
 {'slug': 'gechazi', 'en': 'Gechazi', 'he': 'גחזי', 'cat': 'biblical-figures'},
 {'slug': 'gedaliah', 'en': 'Gedaliah', 'he': 'גדליה', 'cat': ''},
 {'slug': 'goliath', 'en': 'Goliath', 'he': 'גלית', 'cat': 'biblical-figures'},
 {'slug': 'deborah',
  'en': 'Deborah',
  'he': 'דבורה',
  'cat': 'biblical-figures'},
 {'slug': 'doeg', 'en': 'Doeg', 'he': 'דואג', 'cat': 'biblical-figures'},
 {'slug': 'king-david',
  'en': 'King David',
  'he': 'דוד המלך',
  'cat': 'biblical-figures'},
 {'slug': 'the-spies',
  'en': 'The Spies',
  'he': 'המרגלים',
  'cat': 'biblical-figures'},
 {'slug': 'dinah', 'en': 'Dinah', 'he': 'דינה', 'cat': 'biblical-figures'},
 {'slug': 'dan', 'en': 'Dan', 'he': 'דן', 'cat': 'biblical-figures'},
 {'slug': 'daniel', 'en': 'Daniel', 'he': 'דניאל', 'cat': 'biblical-figures'},
 {'slug': 'darius', 'en': 'Darius', 'he': 'דריוש', 'cat': 'biblical-figures'},
 {'slug': 'abel', 'en': 'Abel', 'he': 'הבל', 'cat': 'biblical-figures'},
 {'slug': 'hagar', 'en': 'Hagar', 'he': 'הגר', 'cat': 'biblical-figures'},
 {'slug': 'hoshea-(the-prophet)',
  'en': 'Hosea (the Prophet)',
  'he': 'הושע (הנביא)',
  'cat': 'biblical-figures'},
 {'slug': 'haman', 'en': 'Haman', 'he': 'המן', 'cat': 'biblical-figures'},
 {'slug': 'vashti', 'en': 'Vashti', 'he': 'ושתי', 'cat': 'biblical-figures'},
 {'slug': 'zevulun',
  'en': 'Zevulun',
  'he': 'זבולון',
  'cat': 'biblical-figures'},
 {'slug': 'zechariah',
  'en': 'Zechariah',
  'he': 'זכריה',
  'cat': 'biblical-figures'},
 {'slug': 'zimri', 'en': 'Zimri', 'he': 'זמרי', 'cat': 'biblical-figures'},
 {'slug': 'zeresh', 'en': 'Zeresh', 'he': 'זרש', 'cat': 'biblical-figures'},
 {'slug': 'habakkuk',
  'en': 'Habakkuk',
  'he': 'חבקוק',
  'cat': 'biblical-figures'},
 {'slug': 'chur', 'en': 'Chur', 'he': 'חור', 'cat': 'biblical-figures'},
 {'slug': 'hezekiah',
  'en': 'Hezekiah',
  'he': 'חזקיה',
  'cat': 'biblical-figures'},
 {'slug': 'hiram', 'en': 'Hiram', 'he': 'חירם', 'cat': 'biblical-figures'},
 {'slug': 'ham', 'en': 'Ham', 'he': 'חם', 'cat': 'biblical-figures'},
 {'slug': 'hannah', 'en': 'Hannah', 'he': 'חנה', 'cat': 'biblical-figures'},
 {'slug': 'enoch1',
  'en': 'Enoch',
  'he': 'חנוך בן ירד',
  'cat': 'biblical-figures'},
 {'slug': 'judah', 'en': 'Judah', 'he': 'יהודה', 'cat': 'biblical-figures'},
 {'slug': 'judith', 'en': 'Judith', 'he': 'יהודית', 'cat': 'biblical-figures'},
 {'slug': 'jehoiachin',
  'en': 'Jehoiachin',
  'he': 'יהויכין',
  'cat': 'biblical-figures'},
 {'slug': 'jehoiakim',
  'en': 'Jehoiakim',
  'he': 'יהויקים',
  'cat': 'biblical-figures'},
 {'slug': 'jonadab-the-son-of-rechab',
  'en': 'Jonadab, the Son of Rechab',
  'he': 'יהונדב בן רכב',
  'cat': 'biblical-figures'},
 {'slug': 'jonathan1',
  'en': 'Jonathan',
  'he': 'יהונתן בן שאול',
  'cat': 'biblical-figures'},
 {'slug': 'joshua', 'en': 'Joshua', 'he': 'יהושע', 'cat': 'biblical-figures'},
 {'slug': 'yehoshafat',
  'en': 'Yehoshafat',
  'he': 'יהושפט',
  'cat': 'biblical-figures'},
 {'slug': 'yoav', 'en': 'Yoav', 'he': 'יואב', 'cat': 'biblical-figures'},
 {'slug': 'joash-(king-of-judah)',
  'en': 'Yoash (King of Judah)',
  'he': 'יואש (מלך יהודה)',
  'cat': 'biblical-figures'},
 {'slug': 'yokheved',
  'en': 'Yokheved',
  'he': 'יוכבד',
  'cat': 'biblical-figures'},
 {'slug': 'jonah',
  'en': 'Jonah',
  'he': 'יונה הנביא',
  'cat': 'biblical-figures'},
 {'slug': 'joseph', 'en': 'Joseph', 'he': 'יוסף', 'cat': 'biblical-figures'},
 {'slug': 'ezekiel',
  'en': 'Ezekiel',
  'he': 'יחזקאל',
  'cat': 'biblical-figures'},
 {'slug': 'yael',
  'en': 'Yael',
  'he': 'יעל אשת חבר הקיני',
  'cat': 'biblical-figures'},
 {'slug': 'jacob', 'en': 'Jacob', 'he': 'יעקב', 'cat': 'biblical-figures'},
 {'slug': 'yefet', 'en': 'Yefet', 'he': 'יפת', 'cat': 'biblical-figures'},
 {'slug': 'yiftach', 'en': 'Yiftach', 'he': 'יפתח', 'cat': 'biblical-figures'},
 {'slug': 'isaac-and-esau',
  'en': 'Isaac and Esau',
  'he': 'יצחק ועשו',
  'cat': 'biblical-figures'},
 {'slug': 'isaac', 'en': 'Isaac', 'he': 'יצחק', 'cat': 'biblical-figures'},
 {'slug': 'yerovam-(son-of-nebat)',
  'en': 'Jeroboam (Son of Nebat)',
  'he': 'ירבעם בן נבט',
  'cat': 'biblical-figures'},
 {'slug': 'yokheved',
  'en': 'Yokheved',
  'he': 'יוכבד',
  'cat': 'biblical-figures'},
 {'slug': 'moses', 'en': 'Moses', 'he': 'משה', 'cat': 'biblical-figures'},
 {'slug': 'jeremiah',
  'en': 'Jeremiah',
  'he': 'ירמיהו',
  'cat': 'biblical-figures'},
 {'slug': 'jesse', 'en': 'Jesse', 'he': 'ישי', 'cat': 'biblical-figures'},
 {'slug': 'ishmael',
  'en': 'Ishmael',
  'he': 'ישמעאל',
  'cat': 'biblical-figures'},
 {'slug': 'isaiah', 'en': 'Isaiah', 'he': 'ישעיהו', 'cat': 'biblical-figures'},
 {'slug': 'issachar',
  'en': 'Issachar',
  'he': 'יששכר',
  'cat': 'biblical-figures'},
 {'slug': 'yitro', 'en': 'Yitro', 'he': 'יתרו', 'cat': 'biblical-figures'},
 {'slug': 'cyrus', 'en': 'Cyrus', 'he': 'כורש', 'cat': 'biblical-figures'},
 {'slug': 'caleb',
  'en': 'Caleb',
  'he': 'כלב בן יפונה',
  'cat': 'biblical-figures'},
 {'slug': 'leah', 'en': 'Leah', 'he': 'לאה', 'cat': 'biblical-figures'},
 {'slug': 'lot', 'en': 'Lot', 'he': 'לוט', 'cat': 'biblical-figures'},
 {'slug': 'lilith', 'en': 'Lilith', 'he': 'לילית', 'cat': 'biblical-figures'},
 {'slug': 'lemekh1', 'en': 'Lemekh', 'he': 'למך', 'cat': 'biblical-figures'},
 {'slug': 'micah',
  'en': 'Micah',
  'he': 'מיכה הנביא',
  'cat': 'biblical-figures'},
 {'slug': 'mikhal', 'en': 'Mikhal', 'he': 'מיכל', 'cat': 'biblical-figures'},
 {'slug': 'malachi',
  'en': 'Malachi',
  'he': 'מלאכי',
  'cat': 'biblical-figures'},
 {'slug': 'melchizedek',
  'en': 'Melchizedek',
  'he': 'מלכי צדק',
  'cat': 'biblical-figures'},
 {'slug': 'menasseh-(king-of-judah)',
  'en': 'Menashe (King of Judah)',
  'he': 'המלך מנשה',
  'cat': 'biblical-figures'},
 {'slug': 'mordekhai',
  'en': 'Mordekhai',
  'he': 'מרדכי',
  'cat': 'biblical-figures'},
 {'slug': 'miriam', 'en': 'Miriam', 'he': 'מרים', 'cat': 'biblical-figures'},
 {'slug': 'nebuchadnezzar',
  'en': 'Nebuchadnezzar',
  'he': 'נבוכדנאצר',
  'cat': 'biblical-figures'},
 {'slug': 'navot', 'en': 'Navot', 'he': 'נבות', 'cat': 'biblical-figures'},
 {'slug': 'naval',
  'en': 'Naval',
  'he': 'נבל (איש בתנ"ך)',
  'cat': 'biblical-figures'},
 {'slug': 'nadav-and-avihu',
  'en': 'Nadav and Avihu',
  'he': 'נדב ואביהוא',
  'cat': 'biblical-figures'},
 {'slug': 'noah', 'en': 'Noah', 'he': 'נח', 'cat': 'biblical-figures'},
 {'slug': 'nehemiah',
  'en': 'Nehemiah',
  'he': 'נחמיה',
  'cat': 'biblical-figures'},
 {'slug': 'nimrod', 'en': 'Nimrod', 'he': 'נמרוד', 'cat': 'biblical-figures'},
 {'slug': 'naomi', 'en': 'Naomi', 'he': 'נעמי', 'cat': 'biblical-figures'},
 {'slug': 'naaman', 'en': "Na'aman", 'he': 'נעמן', 'cat': 'biblical-figures'},
 {'slug': 'nephilim',
  'en': 'Nephilim',
  'he': 'נפילים',
  'cat': 'biblical-figures'},
 {'slug': 'naftali',
  'en': 'Naftali',
  'he': 'נפתלי',
  'cat': 'biblical-figures'},
 {'slug': 'sisera', 'en': 'Sisera', 'he': 'סיסרא', 'cat': 'biblical-figures'},
 {'slug': 'sennacherib',
  'en': 'Sennacherib',
  'he': 'סנחריב',
  'cat': 'biblical-figures'},
 {'slug': 'serah-the-daughter-of-asher',
  'en': 'Serah the Daughter of Asher',
  'he': 'סרח בת אשר',
  'cat': 'biblical-figures'},
 {'slug': 'iddo', 'en': 'Iddo', 'he': 'עדו', 'cat': 'biblical-figures'},
 {'slug': 'obadiah',
  'en': 'Obadiah',
  'he': 'עובדיה',
  'cat': 'biblical-figures'},
 {'slug': 'og', 'en': 'Og', 'he': 'עוג', 'cat': 'biblical-figures'},
 {'slug': 'uzziah', 'en': 'Uzziah', 'he': 'עוזיה', 'cat': 'biblical-figures'},
 {'slug': 'ezra', 'en': 'Ezra', 'he': 'עזרא', 'cat': 'biblical-figures'},
 {'slug': 'achan', 'en': 'Achan', 'he': 'עכן', 'cat': 'biblical-figures'},
 {'slug': 'the-sons-of-eli',
  'en': 'The Sons of Eli',
  'he': 'בני עלי',
  'cat': 'biblical-figures'},
 {'slug': 'eli', 'en': 'Eli', 'he': 'עלי', 'cat': 'biblical-figures'},
 {'slug': 'amos', 'en': 'Amos', 'he': 'עמוס', 'cat': 'biblical-figures'},
 {'slug': 'amalek', 'en': 'Amalek', 'he': 'עמלק', 'cat': 'biblical-figures'},
 {'slug': 'amram', 'en': 'Amram', 'he': 'עמרם', 'cat': 'biblical-figures'},
 {'slug': 'amasa', 'en': 'Amasa', 'he': 'עמשא', 'cat': 'biblical-figures'},
 {'slug': 'efron', 'en': 'Efron', 'he': 'עפרון', 'cat': 'biblical-figures'},
 {'slug': 'er-(firstborn-son-of-judah)',
  'en': 'Er (Firstborn Son of Judah)',
  'he': 'ער בכור יהודה',
  'cat': 'biblical-figures'},
 {'slug': 'esau', 'en': 'Esau', 'he': 'עשיו', 'cat': 'biblical-figures'},
 {'slug': 'potiphar',
  'en': 'Potiphar',
  'he': 'פוטיפר',
  'cat': 'biblical-figures'},
 {'slug': 'the-concubine-of-givah',
  'en': 'The Concubine of Givah',
  'he': 'פילגש בגבעה',
  'cat': 'biblical-figures'},
 {'slug': 'pinchas',
  'en': 'Pinchas',
  'he': 'פינחס',
  'cat': 'biblical-figures'},
 {'slug': 'pharaoh', 'en': 'Pharaoh', 'he': 'פרעה', 'cat': 'biblical-figures'},
 {'slug': 'daughters-of-zelophehad',
  'en': 'Daughters of Tzelofchad',
  'he': 'בנות צלפחד',
  'cat': 'biblical-figures'},
 {'slug': 'zelophehad',
  'en': 'Tzelofchad',
  'he': 'צלפחד',
  'cat': 'biblical-figures'},
 {'slug': 'tzipporah',
  'en': 'Tzipporah',
  'he': 'ציפורה',
  'cat': 'biblical-figures'},
 {'slug': 'keturah',
  'en': 'Keturah',
  'he': 'קטורה',
  'cat': 'biblical-figures'},
 {'slug': 'cain', 'en': 'Cain', 'he': 'קין', 'cat': 'biblical-figures'},
 {'slug': 'the-sons-of-korach',
  'en': 'The Sons of Korach',
  'he': 'בני קרח',
  'cat': 'biblical-figures'},
 {'slug': 'korach', 'en': 'Korach', 'he': 'קרח', 'cat': 'biblical-figures'},
 {'slug': 'reuben', 'en': 'Reuben', 'he': 'ראובן', 'cat': 'biblical-figures'},
 {'slug': 'rebecca', 'en': 'Rebecca', 'he': 'רבקה', 'cat': 'biblical-figures'},
 {'slug': 'ruth', 'en': 'Ruth', 'he': 'רות', 'cat': 'biblical-figures'},
 {'slug': 'rahab', 'en': 'Rahab', 'he': 'רחב', 'cat': 'biblical-figures'},
 {'slug': 'rehoboam',
  'en': 'Rehoboam',
  'he': 'רחבעם',
  'cat': 'biblical-figures'},
 {'slug': 'rachel', 'en': 'Rachel', 'he': 'רחל', 'cat': 'biblical-figures'},
 {'slug': 'king-saul',
  'en': 'King Saul',
  'he': 'המלך שאול',
  'cat': 'biblical-figures'},
 {'slug': 'king-solomon',
  'en': 'King Solomon',
  'he': 'שְׁלֹמֹה',
  'cat': 'biblical-figures'},
 {'slug': 'samuel-(prophet)',
  'en': 'Samuel (Prophet)',
  'he': 'שמואל הנביא',
  'cat': 'biblical-figures'},
 {'slug': 'simeon', 'en': 'Simeon', 'he': 'שמעון', 'cat': 'biblical-figures'},
 {'slug': 'shimei', 'en': 'Shimei', 'he': 'שמעי', 'cat': 'biblical-figures'},
 {'slug': 'samson', 'en': 'Samson', 'he': 'שמשון', 'cat': 'biblical-figures'},
 {'slug': 'tamar',
  'en': 'Tamar',
  'he': 'תמר (יהודה)',
  'cat': 'biblical-figures'},
 {'slug': 'terach', 'en': 'Terach', 'he': 'תרח', 'cat': 'biblical-figures'},
 {'slug': 'queen-of-sheba',
  'en': 'Queen of Sheba',
  'he': 'מלכת שבא',
  'cat': 'biblical-figures'},
 {'slug': 'sarah', 'en': 'Sarah', 'he': 'שרה', 'cat': 'biblical-figures'},
 {'slug': 'josiah', 'en': 'Josiah', 'he': 'יאשיהו', 'cat': 'biblical-figures'},
 {'slug': 'zedekiah',
  'en': 'Zedekiah',
  'he': 'צדקיהו',
  'cat': 'biblical-figures'},
 {'slug': 'eve', 'en': 'Eve', 'he': 'חוה', 'cat': 'biblical-figures'},
 {'slug': 'betzalel',
  'en': 'Betzalel',
  'he': 'בצלאל',
  'cat': 'biblical-figures'},
 {'slug': 'batsheva3',
  'en': 'Batsheva',
  'he': 'בת שבע',
  'cat': 'biblical-figures'},
 {'slug': 'shem', 'en': 'Shem', 'he': 'שֵׁם', 'cat': 'biblical-figures'},
 {'slug': 'gideon', 'en': 'Gideon', 'he': 'גדעון', 'cat': 'biblical-figures'},
 {'slug': 'ahasuerus',
  'en': 'Ahasuerus',
  'he': 'אחשוורוש',
  'cat': 'biblical-figures'},
 {'slug': 'pharaohs-daughter',
  'en': "Pharaoh's Daughter",
  'he': 'בתיה',
  'cat': 'biblical-figures'},
 {'slug': 'achitofel',
  'en': 'Achitofel',
  'he': 'אחיתופל',
  'cat': 'biblical-figures'},
 {'slug': 'asher', 'en': 'Asher', 'he': 'אשר', 'cat': 'biblical-figures'},
 {'slug': 'chananiah-mishael-and-azariah',
  'en': 'Chananiah, Mishael and Azariah',
  'he': 'חנניה מישאל ועזריה',
  'cat': 'biblical-figures'},
 {'slug': 'sichon1', 'en': 'Sichon', 'he': 'סיחון', 'cat': 'biblical-figures'},
 {'slug': 'seth', 'en': 'Seth', 'he': 'שת', 'cat': 'biblical-figures'},
 {'slug': 'nachshon-ben-aminadav',
  'en': 'Nachshon Ben Aminadav',
  'he': 'נחשון בן עמינדב',
  'cat': 'biblical-figures'},
 {'slug': 'huldah',
  'en': 'Huldah',
  'he': 'חולדה נביאה',
  'cat': 'biblical-figures'},
 {'slug': 'prayer', 'en': 'Prayer', 'he': 'תפילה', 'cat': 'prayer'},
 {'slug': 'priestly-blessing',
  'en': 'Priestly Blessing',
  'he': 'ברכת כהנים',
  'cat': ''},
 {'slug': 'haggadah', 'en': 'Haggadah', 'he': 'הגדה', 'cat': 'prayer'},
 {'slug': 'kavanah', 'en': 'Kavanah', 'he': 'כוונה', 'cat': 'prayer'},
 {'slug': 'praise-of-god',
  'en': 'Praise of God',
  'he': 'תהילת אלקים',
  'cat': ''},
 {'slug': 'blessings', 'en': 'Blessings', 'he': 'ברכה', 'cat': 'prayer'},
 {'slug': 'birkat-hamazon',
  'en': 'Birkat HaMazon',
  'he': 'ברכת המזון',
  'cat': 'prayer'},
 {'slug': 'havdalah', 'en': 'Havdalah', 'he': 'הבדלה', 'cat': 'prayer'},
 {'slug': 'hallel', 'en': 'Hallel', 'he': 'הַלֵּל', 'cat': 'prayer'},
 {'slug': 'hitbodedut', 'en': 'Hitbodedut', 'he': 'התבודדות', 'cat': 'prayer'},
 {'slug': 'vidui', 'en': 'Vidui', 'he': 'וידוי', 'cat': 'prayer'},
 {'slug': 'niggun', 'en': 'Niggun', 'he': 'ניגון', 'cat': 'prayer'},
 {'slug': 'kiddush', 'en': 'Kiddush', 'he': 'קידוש', 'cat': 'prayer'},
 {'slug': 'kaddish', 'en': 'Kaddish', 'he': 'קדיש', 'cat': 'prayer'},
 {'slug': 'shema', 'en': 'Shema', 'he': 'קריאת שמע', 'cat': 'prayer'},
 {'slug': 'arvit', 'en': 'Arvit', 'he': 'תפילת ערבית', 'cat': 'prayer'},
 {'slug': 'shabbat-prayers',
  'en': 'Shabbat Prayers',
  'he': 'תפילת שבת',
  'cat': 'prayer'},
 {'slug': 'shacharit',
  'en': 'Shacharit',
  'he': 'תפילת שחרית',
  'cat': 'prayer'},
 {'slug': 'tashlich', 'en': 'Tashlich', 'he': 'תשליך', 'cat': 'prayer'},
 {'slug': 'al-hanisim',
  'en': 'Al Hanisim',
  'he': 'על הניסים',
  'cat': 'prayer'},
 {'slug': 'kabbalat-shabbat',
  'en': 'Kabbalat Shabbat',
  'he': 'קבלת שבת',
  'cat': 'prayer'},
 {'slug': 'mourners-kaddish',
  'en': "Mourner's Kaddish",
  'he': 'קדיש יתום',
  'cat': 'prayer'},
 {'slug': 'aleinu', 'en': 'Aleinu', 'he': 'עלינו', 'cat': 'prayer'},
 {'slug': 'lekha-dodi1',
  'en': 'Lekha Dodi',
  'he': 'לכה דודי',
  'cat': 'prayer'},
 {'slug': 'mah-tovu', 'en': 'Mah Tovu', 'he': 'מה טובו', 'cat': 'prayer'},
 {'slug': 'sheva-berakhot',
  'en': 'Sheva Berakhot',
  'he': 'שבע ברכות',
  'cat': 'prayer'},
 {'slug': 'selichot', 'en': 'Selichot', 'he': 'סליחות', 'cat': 'prayer'},
 {'slug': 'vahavta', 'en': "V'ahavta", 'he': 'ואהבת', 'cat': 'prayer'},
 {'slug': 'birkot-hashachar',
  'en': 'Birkot Hashachar',
  'he': 'ברכות השחר',
  'cat': 'prayer'},
 {'slug': 'shemoneh-esrei',
  'en': 'Shemoneh Esrei',
  'he': 'שמונה עשרה',
  'cat': 'prayer'},
 {'slug': 'blessings-(halakhah)',
  'en': 'Blessings (Halakhah)',
  'he': 'ברכות',
  'cat': 'prayer'},
 {'slug': 'tachanun', 'en': 'Tachanun', 'he': 'תחנון', 'cat': 'prayer'},
 {'slug': 'mourning', 'en': 'Mourning', 'he': 'אבלות', 'cat': 'lifecycle'},
 {'slug': 'mother', 'en': 'Mother', 'he': 'אמא', 'cat': 'lifecycle'},
 {'slug': 'bar-mitzvah',
  'en': 'Bar Mitzvah',
  'he': 'בר מצווה',
  'cat': 'lifecycle'},
 {'slug': 'divorce', 'en': 'Divorce', 'he': 'גירושין', 'cat': 'lifecycle'},
 {'slug': 'parents', 'en': 'Parents', 'he': 'הורים', 'cat': 'lifecycle'},
 {'slug': 'education', 'en': 'Education', 'he': 'חינוך', 'cat': 'lifecycle'},
 {'slug': 'yahrzeit', 'en': 'Yahrzeit', 'he': 'יאהרצייט', 'cat': 'lifecycle'},
 {'slug': 'children', 'en': 'Children', 'he': 'ילדים', 'cat': 'lifecycle'},
 {'slug': 'ketubah', 'en': 'Ketubah', 'he': 'כתובה', 'cat': 'lifecycle'},
 {'slug': 'birth', 'en': 'Birth', 'he': 'לידה', 'cat': 'lifecycle'},
 {'slug': 'circumcision',
  'en': 'Circumcision',
  'he': 'ברית מילה',
  'cat': 'lifecycle'},
 {'slug': 'death', 'en': 'Death', 'he': 'מוות', 'cat': 'lifecycle'},
 {'slug': 'marriage', 'en': 'Marriage', 'he': 'נישואים', 'cat': 'lifecycle'},
 {'slug': 'fertility', 'en': 'Fertility', 'he': 'פוריות', 'cat': 'lifecycle'},
 {'slug': 'burial', 'en': 'Burial', 'he': 'קבורה', 'cat': 'lifecycle'},
 {'slug': 'conversion', 'en': 'Conversion', 'he': 'גיור', 'cat': 'lifecycle'},
 {'slug': 'bat-mitzvah',
  'en': 'Bat Mitzvah',
  'he': 'בת מצווה',
  'cat': 'lifecycle'},
 {'slug': 'pidyon-haben',
  'en': 'Pidyon Haben',
  'he': 'פדיון הבן',
  'cat': 'lifecycle'},
 {'slug': 'etrog', 'en': 'Etrog', 'he': 'אתרוג', 'cat': 'ritual-objects'},
 {'slug': 'four-cups',
  'en': 'Four Cups',
  'he': 'ארבע כוסות',
  'cat': 'ritual-objects'},
 {'slug': 'priestly-garments',
  'en': 'Priestly Garments',
  'he': 'בגדי כהונה',
  'cat': 'ritual-objects'},
 {'slug': 'cup-for-the-blessing',
  'en': 'Cup of Blessing',
  'he': 'כוס של ברכה',
  'cat': 'ritual-objects'},
 {'slug': 'the-gold-altar',
  'en': 'The Golden Altar',
  'he': 'מזבח הזהב',
  'cat': 'ritual-objects'},
 {'slug': 'the-copper-altar',
  'en': 'The Copper Altar',
  'he': 'מזבח הנחושת',
  'cat': 'ritual-objects'},
 {'slug': 'menorah1', 'en': 'Menorah', 'he': '', 'cat': 'ritual-objects'},
 {'slug': 'the-curtain',
  'en': 'The Curtain',
  'he': 'הפרוכת',
  'cat': 'ritual-objects'},
 {'slug': 'temple-vessels',
  'en': 'Temple Vessels',
  'he': 'כלי המקדש',
  'cat': 'ritual-objects'},
 {'slug': 'head-coverings',
  'en': 'Head Coverings',
  'he': 'כסוי הראש',
  'cat': 'ritual-objects'},
 {'slug': 'the-tablets',
  'en': 'The Tablets',
  'he': 'הלוחות',
  'cat': 'ritual-objects'},
 {'slug': 'lulav', 'en': 'Lulav', 'he': 'לולב', 'cat': 'ritual-objects'},
 {'slug': 'showbread',
  'en': 'Showbread',
  'he': 'לחם הפנים',
  'cat': 'ritual-objects'},
 {'slug': 'mezuzah', 'en': 'Mezuzah', 'he': 'מזוזה', 'cat': 'ritual-objects'},
 {'slug': 'maaser-sheni',
  'en': "Ma'aser Sheni",
  'he': 'מעשר שני',
  'cat': 'ritual-objects'},
 {'slug': 'mikveh', 'en': 'Mikveh', 'he': 'מקווה', 'cat': 'ritual-objects'},
 {'slug': 'mishkan', 'en': 'Mishkan', 'he': 'משכן', 'cat': 'ritual-objects'},
 {'slug': 'candles', 'en': 'Candles', 'he': 'נרות', 'cat': 'ritual-objects'},
 {'slug': 'sukkah', 'en': 'Sukkah', 'he': 'סוכה', 'cat': 'ritual-objects'},
 {'slug': 'torah-scrolls',
  'en': 'Torah Scroll',
  'he': 'ספר תורה',
  'cat': 'ritual-objects'},
 {'slug': 'parah-adumah',
  'en': 'Parah Adumah',
  'he': 'פרה אדומה',
  'cat': 'ritual-objects'},
 {'slug': 'tzitzit', 'en': 'Tzitzit', 'he': 'ציצית', 'cat': 'ritual-objects'},
 {'slug': 'incense', 'en': 'Incense', 'he': 'קטורת', 'cat': 'ritual-objects'},
 {'slug': 'mincha-(קרבן)',
  'en': 'Mincha (קרבן)',
  'he': 'קרבן מנחה',
  'cat': 'ritual-objects'},
 {'slug': 'libations',
  'en': 'Libations',
  'he': 'נסכים',
  'cat': 'ritual-objects'},
 {'slug': 'omer-offering',
  'en': 'Omer Offering',
  'he': 'קרבן העומר',
  'cat': 'ritual-objects'},
 {'slug': 'shabbat-candles',
  'en': 'Shabbat Candles',
  'he': 'נר שבת',
  'cat': 'ritual-objects'},
 {'slug': 'shofar', 'en': 'Shofar', 'he': 'שופר', 'cat': 'ritual-objects'},
 {'slug': 'oils1', 'en': 'Oils', 'he': 'שמן', 'cat': 'ritual-objects'},
 {'slug': 'tefillin',
  'en': 'Tefillin',
  'he': 'תפילין',
  'cat': 'ritual-objects'},
 {'slug': 'terumah', 'en': 'Terumah', 'he': 'תרומה', 'cat': 'ritual-objects'},
 {'slug': 'geniza', 'en': 'Genizah', 'he': 'גניזה', 'cat': 'ritual-objects'},
 {'slug': 'kippah', 'en': 'Kippah', 'he': 'כיפה', 'cat': 'ritual-objects'},
 {'slug': 'tallit', 'en': 'Tallit', 'he': 'טלית', 'cat': 'ritual-objects'},
 {'slug': 'man-and-wife',
  'en': 'Man and Wife',
  'he': 'איש ואשה',
  'cat': 'social-issues'},
 {'slug': 'converts', 'en': 'Converts', 'he': 'גר', 'cat': 'social-issues'},
 {'slug': 'identity', 'en': 'Identity', 'he': 'זהות', 'cat': 'social-issues'},
 {'slug': 'women', 'en': 'Women', 'he': 'נשים', 'cat': 'social-issues'},
 {'slug': 'ownership',
  'en': 'Ownership',
  'he': 'בעלות',
  'cat': 'social-issues'},
 {'slug': 'diaspora',
  'en': 'Diaspora',
  'he': 'תפוצות',
  'cat': 'social-issues'},
 {'slug': 'strangers',
  'en': 'Strangers',
  'he': 'זרים',
  'cat': 'social-issues'},
 {'slug': 'jewish-people',
  'en': 'Jewish People',
  'he': 'עם ישראל',
  'cat': 'social-issues'},
 {'slug': 'human-dignity',
  'en': 'Human Dignity',
  'he': 'כבוד אנושי',
  'cat': 'social-issues'},
 {'slug': 'deceit', 'en': 'Deceit', 'he': 'תרמית', 'cat': 'social-issues'},
 {'slug': 'power', 'en': 'Power', 'he': 'כוח', 'cat': 'social-issues'},
 {'slug': 'money', 'en': 'Money', 'he': 'כסף', 'cat': 'social-issues'},
 {'slug': 'wars', 'en': 'Wars', 'he': 'מלחמה', 'cat': 'social-issues'},
 {'slug': 'governments',
  'en': 'Governments',
  'he': 'ממשלה',
  'cat': 'social-issues'},
 {'slug': 'leadership',
  'en': 'Leadership',
  'he': 'מנהיגות',
  'cat': 'social-issues'},
 {'slug': 'censuses', 'en': 'Censuses', 'he': 'מפקד', 'cat': 'social-issues'},
 {'slug': 'trade', 'en': 'Trade', 'he': 'מסחר', 'cat': 'social-issues'},
 {'slug': 'travel', 'en': 'Travel', 'he': 'נסיעה', 'cat': 'social-issues'},
 {'slug': 'non-jews', 'en': 'Non Jews', 'he': 'גוים', 'cat': 'social-issues'},
 {'slug': 'tzaddik', 'en': 'Tzaddik', 'he': '', 'cat': ''},
 {'slug': 'revenge', 'en': 'Revenge', 'he': 'נקמה', 'cat': 'social-issues'},
 {'slug': 'business', 'en': 'Business', 'he': 'עסק', 'cat': 'social-issues'},
 {'slug': 'slaves', 'en': 'Slaves', 'he': 'עבדים', 'cat': 'social-issues'},
 {'slug': 'work', 'en': 'Work', 'he': 'עֲבוֹדָה', 'cat': 'social-issues'},
 {'slug': 'poverty', 'en': 'Poverty', 'he': 'עוני', 'cat': 'social-issues'},
 {'slug': 'punishment',
  'en': 'Punishment',
  'he': 'ענישה',
  'cat': 'social-issues'},
 {'slug': 'wealth', 'en': 'Wealth', 'he': 'עושר', 'cat': 'social-issues'},
 {'slug': 'poor', 'en': 'Poor', 'he': 'עני', 'cat': 'social-issues'},
 {'slug': 'oppression',
  'en': 'Oppression',
  'he': 'עושק',
  'cat': 'social-issues'},
 {'slug': 'workers', 'en': 'Workers', 'he': 'פועל', 'cat': 'social-issues'},
 {'slug': 'action', 'en': 'Action', 'he': 'פעולה', 'cat': 'social-issues'},
 {'slug': 'leaders-(פרנס)',
  'en': 'Leaders (פרנס)',
  'he': 'פרנס',
  'cat': 'social-issues'},
 {'slug': 'society',
  'en': 'Society',
  'he': 'חברה (סביבה אנושית)',
  'cat': 'social-issues'},
 {'slug': 'authority',
  'en': 'Authority',
  'he': 'סמכות',
  'cat': 'social-issues'},
 {'slug': 'hunger', 'en': 'Hunger', 'he': 'רעב', 'cat': 'social-issues'},
 {'slug': 'mentally-handicapped-people',
  'en': 'Mentally Handicapped People',
  'he': 'שוטה',
  'cat': 'social-issues'},
 {'slug': 'partnership',
  'en': 'Partnership',
  'he': 'שותפות',
  'cat': 'social-issues'},
 {'slug': 'neighbors',
  'en': 'Neighbors',
  'he': 'שכנים',
  'cat': 'social-issues'},
 {'slug': 'agency', 'en': 'Agency', 'he': 'שליחות', 'cat': 'social-issues'},
 {'slug': 'hate', 'en': 'Hate', 'he': 'שנאה', 'cat': 'social-issues'},
 {'slug': 'murder', 'en': 'Murder', 'he': 'רצח', 'cat': 'social-issues'},
 {'slug': 'feminism',
  'en': 'Feminism',
  'he': 'פמיניזם',
  'cat': 'social-issues'},
 {'slug': 'sexuality',
  'en': 'Sexuality',
  'he': 'מיניות',
  'cat': 'social-issues'},
 {'slug': 'abortion',
  'en': 'Abortion',
  'he': 'הַפָּלָה',
  'cat': 'social-issues'},
 {'slug': 'inclusion',
  'en': 'Inclusion',
  'he': 'הכללה',
  'cat': 'social-issues'},
 {'slug': 'disability',
  'en': 'Disability',
  'he': 'נכות',
  'cat': 'social-issues'},
 {'slug': 'political-thought',
  'en': 'Political Thought',
  'he': 'חשיבה פוליטית',
  'cat': 'social-issues'},
 {'slug': 'civil-discourse',
  'en': 'Civil Discourse',
  'he': 'שיח אזרחי',
  'cat': 'social-issues'},
 {'slug': 'relationships',
  'en': 'Relationships',
  'he': 'יחסים',
  'cat': 'social-issues'},
 {'slug': 'pluralism',
  'en': 'Pluralism',
  'he': 'פלורליזם',
  'cat': 'social-issues'},
 {'slug': 'democracy',
  'en': 'Democracy',
  'he': 'דמוקרטיה',
  'cat': 'social-issues'},
 {'slug': 'race', 'en': 'Race', 'he': 'גזע', 'cat': 'social-issues'},
 {'slug': 'racism', 'en': 'Racism', 'he': 'גזענות', 'cat': 'social-issues'},
 {'slug': 'diversity', 'en': 'Diversity', 'he': 'גיוון', 'cat': ''},
 {'slug': 'protection',
  'en': 'Protection',
  'he': 'הגנה',
  'cat': 'social-issues'},
 {'slug': 'modernity', 'en': 'Modernity', 'he': 'מודרניות', 'cat': ''},
 {'slug': 'independence', 'en': 'Independence', 'he': 'עצמאות', 'cat': ''},
 {'slug': 'emancipation1', 'en': 'Emancipation', 'he': 'גאולה', 'cat': ''},
 {'slug': 'migrants', 'en': 'Migrants', 'he': '', 'cat': ''},
 {'slug': 'innovation', 'en': 'Innovation', 'he': 'חדשנות', 'cat': ''},
 {'slug': 'technology', 'en': 'Technology', 'he': 'טכנולוגיה', 'cat': ''},
 {'slug': 'management', 'en': 'Management', 'he': 'הנהלה', 'cat': ''},
 {'slug': 'masculinity', 'en': 'Masculinity', 'he': 'גבריות', 'cat': ''},
 {'slug': 'disabilities', 'en': 'Disabilities', 'he': 'מוגבלות', 'cat': ''},
 {'slug': 'social-justice',
  'en': 'Social Justice',
  'he': 'צדק חברתי',
  'cat': 'social-issues'},
 {'slug': 'marah', 'en': 'Marah', 'he': 'מרה', 'cat': 'stories'},
 {'slug': 'covenant-with-the-patriarchs',
  'en': 'Covenant with the Patriarchs',
  'he': 'ברית אבות',
  'cat': 'stories'},
 {'slug': 'prophecy-of-the-patriarchs',
  'en': 'Prophecy of the Patriarchs',
  'he': 'נבואת אבות',
  'cat': 'stories'},
 {'slug': 'abraham-in-ur-kasdim-and-his-departure-from-there',
  'en': 'Abraham in Ur Kasdim and his Departure from There',
  'he': 'אברהם באור כשדים ויציאתו משם',
  'cat': 'stories'},
 {'slug': 'abraham-in-egypt',
  'en': 'Abraham in Egypt',
  'he': 'אברהם במצרים',
  'cat': 'stories'},
 {'slug': 'covenant-of-abraham',
  'en': 'Covenant of Abraham',
  'he': 'ברית אברהם',
  'cat': 'stories'},
 {'slug': 'gods-blessing-and-promise-to-abraham',
  'en': "God's Blessing and Promise to Abraham",
  'he': "ברכת והבטחת ה' לאברהם",
  'cat': 'stories'},
 {'slug': 'abraham-and-the-hittites',
  'en': 'Abraham and the Hittites',
  'he': 'אברהם ובני חת',
  'cat': 'stories'},
 {'slug': 'abraham-and-the-angels',
  'en': 'Abraham and the Angels',
  'he': 'אברהם והמלאכים',
  'cat': 'stories'},
 {'slug': 'abraham-and-the-kings',
  'en': 'Abraham and the Kings',
  'he': 'אברהם והמלכים',
  'cat': 'stories'},
 {'slug': 'abraham-and-sodom',
  'en': 'Abraham and Sodom',
  'he': 'אברהם וסדום',
  'cat': 'stories'},
 {'slug': 'prophecy-of-abraham',
  'en': 'Prophecy of Abraham',
  'he': 'נבואת אברהם',
  'cat': 'stories'},
 {'slug': 'tests-of-abraham',
  'en': 'Tests of Abraham',
  'he': 'נסיונות אברהם',
  'cat': 'stories'},
 {'slug': 'creation-of-man',
  'en': 'Creation of Man',
  'he': 'בריאת אדם',
  'cat': 'stories'},
 {'slug': 'adams-sin-and-his-punishment',
  'en': "Adam's Sin and His Punishment",
  'he': 'חטא אדם הראשון ועונשו',
  'cat': 'stories'},
 {'slug': 'aarons-sin',
  'en': 'Aaron and the Golden Calf',
  'he': 'אהרן וחטא העגל',
  'cat': 'stories'},
 {'slug': 'aarons-death',
  'en': "Aaron's Death",
  'he': 'מיתת אהרן',
  'cat': 'stories'},
 {'slug': 'high-priest',
  'en': 'High Priest',
  'he': 'כהן גדול',
  'cat': 'biblical-figures'},
 {'slug': 'the-great-assembly',
  'en': 'The Great Assembly',
  'he': 'אנשי כנסת הגדולה',
  'cat': 'stories'},
 {'slug': 'destruction-of-the-land-of-israel',
  'en': 'Destruction of the Land of Israel',
  'he': 'חרבן ארץ ישראל',
  'cat': 'stories'},
 {'slug': 'conquest-and-division',
  'en': 'Conquest and Division',
  'he': 'כיבוש וחלוקה',
  'cat': 'stories'},
 {'slug': 'destruction-of-babylonia',
  'en': 'Destruction of Babylonia',
  'he': 'חורבן בבל',
  'cat': 'stories'},
 {'slug': 'destruction-of-the-temple',
  'en': 'Destruction of the Temple',
  'he': 'חורבן בית המקדש',
  'cat': 'stories'},
 {'slug': 'inauguration-of-the-temple',
  'en': 'Inauguration of the Temple',
  'he': 'חנכת בית המקדש',
  'cat': 'stories'},
 {'slug': 'balaams-prophecy',
  'en': "Balaam's Prophecy",
  'he': 'נבואת בלעם',
  'cat': 'stories'},
 {'slug': 'the-children-of-the-angels',
  'en': '"The Children of the Angels"',
  'he': 'בני האלהים',
  'cat': 'stories'},
 {'slug': 'in-the-beginning-of',
  'en': '"In the Beginning of"',
  'he': 'בראשית',
  'cat': 'stories'},
 {'slug': 'creation-of-light-and-luminaires',
  'en': 'Creation of Light and Luminaires',
  'he': 'בריאת האור והמאורות',
  'cat': 'stories'},
 {'slug': 'creation-of-the-animals',
  'en': 'Creation of the Animals',
  'he': 'בריאת בעלי החיים',
  'cat': 'stories'},
 {'slug': 'that-it-was-good',
  'en': '"That it was Good"',
  'he': 'כי טוב',
  'cat': 'stories'},
 {'slug': 'creation-of-water',
  'en': 'Creation of Water',
  'he': 'בריאת המים',
  'cat': 'stories'},
 {'slug': 'creation-of-plants',
  'en': 'Creation of Plants',
  'he': 'בריאת הצמחים',
  'cat': 'stories'},
 {'slug': 'creation-of-heavens-and-earth',
  'en': 'Creation of Heavens and Earth',
  'he': 'בריאת שמים וארץ',
  'cat': 'stories'},
 {'slug': 'creation', 'en': 'Creation', 'he': 'בריאה', 'cat': 'stories'},
 {'slug': 'gog-and-magog',
  'en': 'Gog and Magog',
  'he': 'גוג ומגוג',
  'cat': 'stories'},
 {'slug': 'decree-against-sons',
  'en': 'Decree Against Sons',
  'he': 'גזרת הבנים',
  'cat': 'stories'},
 {'slug': 'israel-in-egypt',
  'en': 'Israel in Egypt',
  'he': 'ישראל במצרים',
  'cat': 'stories'},
 {'slug': 'egyptian-subjugation',
  'en': 'Egyptian Subjugation',
  'he': 'שעבוד מצרים',
  'cat': 'stories'},
 {'slug': 'egyptian-exile',
  'en': 'Egyptian Exile',
  'he': 'גלות מצרים',
  'cat': 'stories'},
 {'slug': 'garden-of-eden',
  'en': 'Garden of Eden',
  'he': 'גן עדן',
  'cat': 'stories'},
 {'slug': 'plague-of-pestilence-(דבר-)',
  'en': 'Plague of Pestilence (דֶּבֶר )',
  'he': 'דבר',
  'cat': 'stories'},
 {'slug': 'the-house-of-david',
  'en': 'The House of David',
  'he': 'בית דוד',
  'cat': 'stories'},
 {'slug': 'david-and-the-temple',
  'en': 'David and the Temple',
  'he': 'דוד ובית המקדש',
  'cat': 'stories'},
 {'slug': 'david-and-the-ark',
  'en': 'David and the Ark',
  'he': 'דוד והארון',
  'cat': 'stories'},
 {'slug': 'davids-sin',
  'en': 'David and Batsheva',
  'he': 'דוד ובת שבע',
  'cat': 'stories'},
 {'slug': 'davids-wars',
  'en': "David's Wars",
  'he': 'מלחמות דוד',
  'cat': 'stories'},
 {'slug': 'davids-census',
  'en': "David's Census",
  'he': 'המניין בידי דוד',
  'cat': 'stories'},
 {'slug': 'generation-of-enosh',
  'en': 'Generation of Enosh',
  'he': 'דור אנוש',
  'cat': 'stories'},
 {'slug': 'generation-of-the-flood',
  'en': 'Generation of the Flood',
  'he': 'דור המבול',
  'cat': 'stories'},
 {'slug': 'well-in-the-desert',
  'en': 'Well in the Desert',
  'he': 'הבאר במדבר',
  'cat': 'stories'},
 {'slug': 'meat-in-the-sinai-desert',
  'en': 'Meat in the Sinai Desert',
  'he': 'הבשר במדבר סיני',
  'cat': 'stories'},
 {'slug': 'appointment-of-judges-for-the-generation-of-the-desert',
  'en': 'Appointment of Judges for The Generation of the Desert',
  'he': 'מינוי דיינים בדור המדבר',
  'cat': 'stories'},
 {'slug': 'edom-and-the-generation-of-the-desert',
  'en': 'Edom and the Generation of the Desert',
  'he': 'דור המדבר ואדום',
  'cat': 'stories'},
 {'slug': 'golden-calf',
  'en': 'Golden Calf',
  'he': 'עגל הזהב',
  'cat': 'stories'},
 {'slug': 'sin-of-the-spies',
  'en': 'Sin of the Spies',
  'he': 'חטא המרגלים',
  'cat': 'stories'},
 {'slug': 'sin-of-peor',
  'en': 'Sin of Peor',
  'he': 'חטא פעור',
  'cat': 'stories'},
 {'slug': 'war-with-midian',
  'en': 'War with Midian',
  'he': 'מלחמת מדיין',
  'cat': 'stories'},
 {'slug': 'manna', 'en': 'Manna', 'he': 'מן בדור המדבר', 'cat': 'stories'},
 {'slug': 'journey-in-the-desert',
  'en': 'Journey in the Desert',
  'he': 'המסע במדבר',
  'cat': 'stories'},
 {'slug': 'the-gatherer',
  'en': 'The Gatherer',
  'he': 'המקושש',
  'cat': 'stories'},
 {'slug': 'naaseh-venishma',
  'en': 'Naaseh Venishma',
  'he': 'נעשה ונשמע',
  'cat': 'stories'},
 {'slug': 'sacrifices-in-the-desert',
  'en': 'Sacrifices in the Desert',
  'he': 'הקורבנות במדבר',
  'cat': 'stories'},
 {'slug': 'complaints-in-the-desert',
  'en': 'Complaints in the Desert',
  'he': 'התלונות במדב',
  'cat': 'stories'},
 {'slug': 'generation-of-the-desert',
  'en': 'Generation of the Desert',
  'he': 'דור המדבר',
  'cat': 'stories'},
 {'slug': 'generation-of-the-dispersion',
  'en': 'Generation of the Dispersion',
  'he': 'דור הפלגה',
  'cat': 'stories'},
 {'slug': 'abels-sacrifice',
  'en': "Abel's Sacrifice",
  'he': 'קרבן הבל',
  'cat': 'stories'},
 {'slug': 'destruction-of-jerusalem',
  'en': 'Destruction of Jerusalem',
  'he': 'חורבן',
  'cat': 'stories'},
 {'slug': 'judahs-blessing',
  'en': "Judah's Blessing",
  'he': 'ברכת יהודה',
  'cat': 'stories'},
 {'slug': 'conquest-of-jericho',
  'en': 'Conquest of Jericho',
  'he': 'כבוש יריחו',
  'cat': 'stories'},
 {'slug': 'stopping-of-the-sun-in-gibeon',
  'en': 'Stopping of the Sun in Gibeon',
  'he': 'עמידת השמש בגבעון',
  'cat': 'stories'},
 {'slug': 'josephs-blessing',
  'en': "Joseph's Blessing",
  'he': 'ברכת יוסף',
  'cat': 'stories'},
 {'slug': 'joseph-and-potiphars-wife',
  'en': "Joseph and Potiphar's Wife",
  'he': 'יוסף ואשת פוטיפר',
  'cat': 'stories'},
 {'slug': 'joseph-in-egypt',
  'en': 'Joseph in Egypt',
  'he': 'יוסף במצרים',
  'cat': 'stories'},
 {'slug': 'joseph-and-the-wine-steward',
  'en': 'Joseph and the Wine Steward',
  'he': 'יוסף ושר המשקים',
  'cat': 'stories'},
 {'slug': 'josephs-dream',
  'en': "Joseph's Dream",
  'he': 'חלום יוסף',
  'cat': 'stories'},
 {'slug': 'the-sale-of-joseph',
  'en': 'The Sale of Joseph',
  'he': 'מכירת יוסף',
  'cat': 'stories'},
 {'slug': 'the-prophecy-of-ezekiel',
  'en': 'The Prophecy of Ezekiel',
  'he': 'נבואת יחזקאל',
  'cat': 'stories'},
 {'slug': 'jacob-and-the-birthright',
  'en': 'Jacob and the Birthright',
  'he': 'יעקב והבכורה',
  'cat': 'stories'},
 {'slug': 'jacobs-blessing',
  'en': "Jacob's Blessing",
  'he': 'ברכת יעקב',
  'cat': 'stories'},
 {'slug': 'the-promise-to-jacob',
  'en': 'The Promise to Jacob',
  'he': 'ההבטחה ליעקב',
  'cat': 'stories'},
 {'slug': 'jacobs-dream',
  'en': "Jacob's Dream",
  'he': 'חלום יעקב',
  'cat': 'stories'},
 {'slug': 'jacob-and-the-angel',
  'en': 'Jacob and the Angel',
  'he': 'יעקב והמלאך',
  'cat': 'stories'},
 {'slug': 'jacob-and-the-sticks',
  'en': 'Jacob and the Sticks',
  'he': 'יעקב והמקלות',
  'cat': 'stories'},
 {'slug': 'jacob-in-egypt',
  'en': 'Jacob in Egypt',
  'he': 'יעקב ומצרים',
  'cat': 'stories'},
 {'slug': 'jacobs-oath',
  'en': "Jacob's Oath",
  'he': 'נדרו של יעקב',
  'cat': 'stories'},
 {'slug': 'jacobs-burial',
  'en': "Jacob's Burial",
  'he': 'קבורת יעקב',
  'cat': 'stories'},
 {'slug': 'isaacs-wells',
  'en': "Isaac's Wells",
  'he': 'בארות יצחק',
  'cat': 'stories'},
 {'slug': 'isaacs-blessing',
  'en': "Isaac's Blessing",
  'he': 'ברכת יצחק',
  'cat': 'stories'},
 {'slug': 'moses-signs',
  'en': "Moses' Signs",
  'he': 'אותות יציאת מצרים',
  'cat': 'stories'},
 {'slug': 'borrowing-the-property-during-the-exodus-from-egypt',
  'en': 'Borrowing the Property during the Exodus from Egypt',
  'he': 'שאלת הרכוש ביציאת מצרים',
  'cat': 'stories'},
 {'slug': 'retributions-during-the-exodus-from-egypt',
  'en': 'Retributions during the Exodus from Egypt',
  'he': 'שפטים ביציאת מצרים',
  'cat': 'stories'},
 {'slug': 'the-exodus-from-egypt',
  'en': 'The Exodus from Egypt',
  'he': 'יציאת מצרים',
  'cat': 'stories'},
 {'slug': 'crossing-the-jordan-river-and-setting-of-the-stones',
  'en': 'Crossing the Jordan River and Setting of the Stones',
  'he': 'עבר הירדן והקמת האבנים',
  'cat': 'stories'},
 {'slug': 'journey-of-the-ark',
  'en': 'Journey of the Ark',
  'he': 'מסע הארון',
  'cat': 'stories'},
 {'slug': 'blessing-of-levi',
  'en': 'Blessing of Levi',
  'he': 'ברכת לוי',
  'cat': 'stories'},
 {'slug': 'counting-of-the-levites',
  'en': 'Counting of the Levites',
  'he': 'מניין הלויים',
  'cat': 'stories'},
 {'slug': 'leviathan', 'en': 'Leviathan', 'he': 'לויתן', 'cat': 'stories'},
 {'slug': 'tower-of-babel',
  'en': 'Tower of Babel',
  'he': 'מגדל בבל',
  'cat': 'stories'},
 {'slug': 'the-idol-of-micha',
  'en': 'The Idol of Micha',
  'he': 'פסל מיכה',
  'cat': 'stories'},
 {'slug': 'famine-in-egypt',
  'en': 'Famine in Egypt',
  'he': 'הרעב במצרים',
  'cat': 'stories'},
 {'slug': 'moses-and-the-tent-of-meeting',
  'en': 'Moses and the Tent of Meeting',
  'he': 'משה ואוהל מועד',
  'cat': 'stories'},
 {'slug': 'moses-in-midian',
  'en': 'Moses in Midian',
  'he': 'משה במדין',
  'cat': 'stories'},
 {'slug': 'moses-at-the-bush',
  'en': 'Moses at the Bush',
  'he': 'משה בסנה',
  'cat': 'stories'},
 {'slug': 'moses-blessing',
  'en': "Moses' Blessing",
  'he': 'ברכת משה',
  'cat': 'stories'},
 {'slug': 'moses-and-josephs-coffin',
  'en': "Moses and Joseph's Coffin",
  'he': 'משה וארון יוסף',
  'cat': 'stories'},
 {'slug': 'moses-and-the-tablets',
  'en': 'Moses and the Tablets',
  'he': 'משה והלוחות',
  'cat': 'stories'},
 {'slug': 'moses-and-the-egyptian',
  'en': 'Moses and the Egyptian',
  'he': 'משה והמצרי',
  'cat': 'stories'},
 {'slug': 'moses-and-israel',
  'en': 'Moses and Israel',
  'he': 'משה וישראל',
  'cat': 'stories'},
 {'slug': 'moses-knowledge',
  'en': "Moses' Knowledge",
  'he': 'ידיעת משה',
  'cat': 'stories'},
 {'slug': 'moses-and-the-priesthood',
  'en': 'Moses and the Priesthood',
  'he': 'משה והכהונה',
  'cat': 'stories'},
 {'slug': 'moses-birth',
  'en': "Moses' Birth",
  'he': 'לידת משה',
  'cat': 'stories'},
 {'slug': 'the-waters-of-meribah',
  'en': 'The Waters of Meribah',
  'he': 'מי מריבה',
  'cat': 'stories'},
 {'slug': 'moses-death-and-burial',
  'en': "Moses' Death and Burial",
  'he': 'מיתת משה וקבורתו',
  'cat': 'stories'},
 {'slug': 'moses-prophecy',
  'en': "Moses' Prophecy",
  'he': 'נבואת משה',
  'cat': 'stories'},
 {'slug': 'moses-rebuke',
  'en': "Moses' Rebuke",
  'he': 'תוכחת משה',
  'cat': 'stories'},
 {'slug': 'moses-and-the-torah',
  'en': 'Moses and the Torah',
  'he': 'תורת משה',
  'cat': 'stories'},
 {'slug': 'moses-prayer-after-the-sin-of-the-spies',
  'en': "Moses' Prayer after the Sin of the Spies",
  'he': 'תפילת משה לאחר חטא המרגלים',
  'cat': 'stories'},
 {'slug': 'moses-prayer-after-the-sin-of-the-calf',
  'en': "Moses' Prayer after the Sin of the Calf",
  'he': 'תפילת משה לאחר חטא העגל',
  'cat': 'stories'},
 {'slug': 'raising-up-and-anointing-the-tabernacle',
  'en': 'Raising Up and Anointing the Tabernacle',
  'he': 'הקמת המשכן ומשיחתו',
  'cat': 'stories'},
 {'slug': 'tabernacle-inauguration',
  'en': 'Tabernacle Inauguration',
  'he': 'חנוכת המשכן',
  'cat': 'stories'},
 {'slug': 'tabernacles-journey',
  'en': "Tabernacle's Journey",
  'he': 'מסע המשכן',
  'cat': 'stories'},
 {'slug': 'tabernacles-making',
  'en': "Tabernacle's Making",
  'he': 'מעשה המשכן',
  'cat': 'stories'},
 {'slug': 'donations-for-the-tabernacle',
  'en': 'Donations for the Tabernacle',
  'he': 'נדבת המשכן',
  'cat': 'stories'},
 {'slug': 'days-of-cordoning',
  'en': 'Days of Cordoning',
  'he': 'ימי הגבלה',
  'cat': 'stories'},
 {'slug': 'tzaraat', 'en': 'Tzara’at', 'he': 'צרעת', 'cat': 'stories'},
 {'slug': 'noah-and-the-ark',
  'en': 'Noah and the Ark',
  'he': 'תיבת נח',
  'cat': 'stories'},
 {'slug': 'noah-and-the-vineyard',
  'en': 'Noah and the Vineyard',
  'he': 'נח והכרם',
  'cat': 'stories'},
 {'slug': 'noahs-sacrifice',
  'en': "Noah's Sacrifice",
  'he': 'קרבן נח',
  'cat': 'stories'},
 {'slug': 'sin-and-punishment-of-the-serpent',
  'en': 'Sin and Punishment of the Serpent',
  'he': 'חטא הנחש ועונש',
  'cat': 'stories'},
 {'slug': 'the-worship-of-molech',
  'en': 'The Worship of Molech',
  'he': 'עבודת המולך',
  'cat': 'stories'},
 {'slug': 'pillar-of-cloud',
  'en': 'Pillar of Cloud',
  'he': 'עמוד ענן',
  'cat': 'stories'},
 {'slug': 'war-with-amalek',
  'en': 'War with Amalek',
  'he': 'מלחמת עמלק',
  'cat': 'stories'},
 {'slug': 'the-tree-of-knowledge',
  'en': 'The Tree of Knowledge',
  'he': 'עץ הדעת',
  'cat': 'stories'},
 {'slug': 'the-tree-of-life',
  'en': 'The Tree of Life',
  'he': 'עץ החיים',
  'cat': 'stories'},
 {'slug': 'binding-of-isaac',
  'en': 'Binding of Isaac',
  'he': 'עקידה',
  'cat': 'stories'},
 {'slug': 'plague-of-locusts',
  'en': 'Plague of Locusts',
  'he': 'מכת ארבה',
  'cat': 'stories'},
 {'slug': 'plague-of-hail',
  'en': 'Plague of Hail',
  'he': 'מכת ברד',
  'cat': 'stories'},
 {'slug': 'plague-of-blood',
  'en': 'Plague of Blood',
  'he': 'מכת דם',
  'cat': 'stories'},
 {'slug': 'warnings-about-the-ten-plagues',
  'en': 'Warnings about the Ten Plagues',
  'he': 'התראה בעשר המכות',
  'cat': 'stories'},
 {'slug': 'magicians-and-the-ten-plagues',
  'en': 'Magicians and the Ten Plagues',
  'he': 'החרטומים בעשר המכות',
  'cat': 'stories'},
 {'slug': 'plague-of-darkness',
  'en': 'Plague of Darkness',
  'he': 'מכת חושך',
  'cat': 'stories'},
 {'slug': 'plague-of-lice',
  'en': 'Plague of Lice',
  'he': 'מכת כינים',
  'cat': 'stories'},
 {'slug': 'plague-of-the-firstborn',
  'en': 'Plague of the Firstborn',
  'he': 'מכת בכורות',
  'cat': 'stories'},
 {'slug': 'plague-of-wild-animals',
  'en': 'Plague of Wild Animals',
  'he': 'מכת ערוב',
  'cat': 'stories'},
 {'slug': 'plague-of-frogs',
  'en': 'Plague of Frogs',
  'he': 'מכת צפרדע',
  'cat': 'stories'},
 {'slug': 'plague-of-boils',
  'en': 'Plague of Boils',
  'he': 'מכת שחין',
  'cat': 'stories'},
 {'slug': 'the-ten-plagues',
  'en': 'The Ten Plagues',
  'he': 'המכות',
  'cat': 'stories'},
 {'slug': 'the-ten-commandments',
  'en': 'The Ten Commandments',
  'he': 'עשרת הדיברות',
  'cat': 'stories'},
 {'slug': 'the-ten-tribes',
  'en': 'The Ten Tribes',
  'he': 'עשרת השבטים',
  'cat': 'stories'},
 {'slug': 'the-hardening-of-pharaohs-heart',
  'en': "The Hardening of Pharaoh's Heart",
  'he': 'חיזוק לב פרעה',
  'cat': 'stories'},
 {'slug': 'pharaohs-dream',
  'en': "Pharaoh's Dream",
  'he': 'חלום פרעה',
  'cat': 'stories'},
 {'slug': 'cains-sacrifice',
  'en': "Cain's Sacrifice",
  'he': 'קרבן קין',
  'cat': 'stories'},
 {'slug': 'tribes', 'en': 'Tribes', 'he': 'שבטים', 'cat': 'stories'},
 {'slug': 'the-seven-nations',
  'en': 'The Seven Nations',
  'he': 'שבעת העממים',
  'cat': 'stories'},
 {'slug': 'song-of-the-sea1',
  'en': 'Song of the Sea',
  'he': 'שירת הים',
  'cat': 'stories'},
 {'slug': 'giving-of-the-torah',
  'en': 'Giving of the Torah',
  'he': 'מתן תורה',
  'cat': 'stories'},
 {'slug': 'flood', 'en': 'Flood', 'he': 'מבול', 'cat': 'stories'},
 {'slug': 'splitting-of-the-red-sea',
  'en': 'Splitting of the Red Sea',
  'he': 'קריעת ים סוף',
  'cat': 'stories'},
 {'slug': 'values', 'en': 'Values', 'he': 'ערכים', 'cat': 'values'},
 {'slug': 'knowing-god',
  'en': 'Knowing God',
  'he': 'ידיעת השם',
  'cat': 'values'},
 {'slug': 'unity', 'en': 'Unity', 'he': 'אחדות', 'cat': 'values'},
 {'slug': 'peace', 'en': 'Peace', 'he': 'שלום', 'cat': 'values'},
 {'slug': 'middot', 'en': 'Middot', 'he': 'מידות', 'cat': 'values'},
 {'slug': 'life', 'en': 'Life', 'he': 'חיים', 'cat': 'values'},
 {'slug': 'love', 'en': 'Love', 'he': 'אהבה', 'cat': 'values'},
 {'slug': 'happiness', 'en': 'Happiness', 'he': 'אושר', 'cat': 'values'},
 {'slug': 'faith', 'en': 'Faith', 'he': 'אמונה', 'cat': 'values'},
 {'slug': 'courage', 'en': 'Courage', 'he': 'אומץ', 'cat': 'values'},
 {'slug': 'truth', 'en': 'Truth', 'he': 'אמת', 'cat': 'values'},
 {'slug': 'humor', 'en': 'Humor', 'he': 'הומור', 'cat': 'values'},
 {'slug': 'trust', 'en': 'Trust', 'he': 'בטחון', 'cat': 'values'},
 {'slug': 'bal-tashchit',
  'en': 'Bal Tashchit',
  'he': 'בל תשחית',
  'cat': 'values'},
 {'slug': 'visiting-the-sick',
  'en': 'Visiting the Sick',
  'he': 'ביקור חולים',
  'cat': 'values'},
 {'slug': 'expertise', 'en': 'Expertise', 'he': 'בקיאות', 'cat': 'values'},
 {'slug': 'strength', 'en': 'Strength', 'he': 'גבורה', 'cat': 'values'},
 {'slug': 'kindness', 'en': 'Kindness', 'he': 'גמילות חסדים', 'cat': 'values'},
 {'slug': 'devekut', 'en': 'Devekut', 'he': 'דבקות', 'cat': 'values'},
 {'slug': 'imagination', 'en': 'Imagination', 'he': 'דמיון', 'cat': 'values'},
 {'slug': 'thanks', 'en': 'Thanks', 'he': 'תודה', 'cat': 'values'},
 {'slug': 'welcoming-guests',
  'en': 'Welcoming Guests',
  'he': 'הכנסת אורחים',
  'cat': 'values'},
 {'slug': 'gratitude', 'en': 'Gratitude', 'he': 'הכרת הטוב', 'cat': 'values'},
 {'slug': 'modesty', 'en': 'Modesty', 'he': 'צניעות', 'cat': 'values'},
 {'slug': 'renewal', 'en': 'Renewal', 'he': 'התחדשות', 'cat': 'values'},
 {'slug': 'carefulness', 'en': 'Carefulness', 'he': 'זהירות', 'cat': 'values'},
 {'slug': 'memory', 'en': 'Memory', 'he': 'זיכרון', 'cat': 'values'},
 {'slug': 'alacrity', 'en': 'Alacrity', 'he': 'זריזות', 'cat': 'values'},
 {'slug': 'friendship', 'en': 'Friendship', 'he': 'חברות', 'cat': 'values'},
 {'slug': 'wisdom', 'en': 'Wisdom', 'he': 'חכמה', 'cat': 'values'},
 {'slug': 'compassion', 'en': 'Compassion', 'he': 'חמלה', 'cat': 'values'},
 {'slug': 'giving', 'en': 'Giving', 'he': 'נתינה', 'cat': 'values'},
 {'slug': 'freedom1', 'en': 'Freedom', 'he': 'חירות', 'cat': 'values'},
 {'slug': 'knowing', 'en': 'Knowing', 'he': 'ידיעה', 'cat': 'values'},
 {'slug': 'honesty', 'en': 'Honesty', 'he': 'יושרה', 'cat': 'values'},
 {'slug': 'righteous', 'en': 'Righteous', 'he': 'ישר', 'cat': 'values'},
 {'slug': 'honoring-parents',
  'en': 'Honoring Parents',
  'he': 'כיבוד הורים',
  'cat': 'values'},
 {'slug': 'respect', 'en': 'Respect', 'he': 'כבוד', 'cat': 'values'},
 {'slug': 'atonement', 'en': 'Atonement', 'he': 'כפרה', 'cat': 'values'},
 {'slug': 'learning', 'en': 'Learning', 'he': 'לימוד', 'cat': 'values'},
 {'slug': 'teaching', 'en': 'Teaching', 'he': 'הוראה', 'cat': 'values'},
 {'slug': 'forgiveness-(מחילה)',
  'en': 'Forgiveness (מחילה)',
  'he': 'מחילה',
  'cat': 'values'},
 {'slug': 'machloket', 'en': 'Machloket', 'he': 'מחלוקת', 'cat': 'values'},
 {'slug': 'generosity', 'en': 'Generosity', 'he': 'נדיבות', 'cat': 'values'},
 {'slug': 'comfort', 'en': 'Comfort', 'he': 'נוחות', 'cat': 'values'},
 {'slug': 'rebuke', 'en': 'Rebuke', 'he': 'תוכחה', 'cat': 'values'},
 {'slug': 'forgiveness', 'en': 'Forgiveness', 'he': 'סליחה', 'cat': 'values'},
 {'slug': 'curiosity', 'en': 'Curiosity', 'he': 'סקרנות', 'cat': 'values'},
 {'slug': 'love-of-god1',
  'en': 'Love of God',
  'he': "אהבת ה'",
  'cat': 'values'},
 {'slug': 'yirat-shamayim',
  'en': 'Yirat Shamayim',
  'he': 'יראת שמיים',
  'cat': 'values'},
 {'slug': 'avodat-hashem',
  'en': 'Avodat Hashem',
  'he': "עבודת ה'",
  'cat': 'values'},
 {'slug': 'humility', 'en': 'Humility', 'he': 'ענוה', 'cat': 'values'},
 {'slug': 'responsibility',
  'en': 'Responsibility',
  'he': 'אחריות',
  'cat': 'values'},
 {'slug': 'fear-(פחד)', 'en': 'Fear (פחד)', 'he': 'פחד', 'cat': 'values'},
 {'slug': 'tzedakah', 'en': 'Tzedakah', 'he': 'צדקה', 'cat': 'values'},
 {'slug': 'kehillah', 'en': 'Kehillah', 'he': 'קהילה', 'cat': 'values'},
 {'slug': 'hope', 'en': 'Hope', 'he': 'תקוה', 'cat': 'values'},
 {'slug': 'zeal', 'en': 'Zeal', 'he': 'קנאות', 'cat': 'values'},
 {'slug': 'listening', 'en': 'Listening', 'he': 'הקשבה', 'cat': 'values'},
 {'slug': 'spirituality',
  'en': 'Spirituality',
  'he': 'רוחניות',
  'cat': 'values'},
 {'slug': 'mercy', 'en': 'Mercy', 'he': 'רחמים', 'cat': 'values'},
 {'slug': 'questions', 'en': 'Questions', 'he': 'שאלות', 'cat': 'values'},
 {'slug': 'discernment', 'en': 'Discernment', 'he': 'שכל', 'cat': 'values'},
 {'slug': 'wholeness', 'en': 'Wholeness', 'he': 'שלמות', 'cat': 'values'},
 {'slug': 'joy', 'en': 'Joy', 'he': 'שמחה', 'cat': 'values'},
 {'slug': 'silence', 'en': 'Silence', 'he': 'שתיקה', 'cat': 'values'},
 {'slug': 'tikkun', 'en': 'Tikkun', 'he': 'תיקון', 'cat': 'values'},
 {'slug': 'teshuvah', 'en': 'Teshuvah', 'he': 'תשובה', 'cat': 'values'},
 {'slug': 'chevruta', 'en': 'Chavruta', 'he': 'חברותא', 'cat': 'values'},
 {'slug': 'consent', 'en': 'Consent', 'he': 'הסכמה', 'cat': 'values'},
 {'slug': 'mindfulness',
  'en': 'Mindfulness',
  'he': 'שימת לב',
  'cat': 'values'},
 {'slug': 'creativity', 'en': 'Creativity', 'he': 'יצירתיות', 'cat': 'values'},
 {'slug': 'torah-study',
  'en': 'Torah Study',
  'he': 'לימוד תורה',
  'cat': 'values'},
 {'slug': 'argument', 'en': 'Argument', 'he': 'טענה', 'cat': 'values'},
 {'slug': 'welcoming', 'en': 'Welcoming', 'he': 'סבר פנים', 'cat': ''},
 {'slug': 'perspective', 'en': 'Perspective', 'he': 'פרספקטיבה', 'cat': ''},
 {'slug': 'shalom-bayit',
  'en': 'Shalom Bayit',
  'he': 'שלום בית',
  'cat': 'values'},
 {'slug': 'empathy', 'en': 'Empathy', 'he': 'אמפתיה', 'cat': ''},
 {'slug': 'growth', 'en': 'Growth', 'he': 'צמיחה', 'cat': ''},
 {'slug': 'inspiration', 'en': 'Inspiration', 'he': 'השראה', 'cat': ''},
 {'slug': 'vulnerability', 'en': 'Vulnerability', 'he': 'פגיעות', 'cat': ''},
 {'slug': 'love-your-neighbor-as-yourself',
  'en': 'Love Your Neighbor as Yourself',
  'he': 'ואהבת לרעך כמוך',
  'cat': 'values'},
 {'slug': 'neshama', 'en': 'Neshama', 'he': 'נשמה', 'cat': 'beliefs'},
 {'slug': 'image-of-god',
  'en': 'Image of God',
  'he': 'צלם אלוקים',
  'cat': 'beliefs'},
 {'slug': 'god-and-man',
  'en': 'God and Man',
  'he': 'אלקים ואדם',
  'cat': 'beliefs'},
 {'slug': 'physicality',
  'en': 'Incorporeality of God',
  'he': 'שלילת גשמות האל',
  'cat': 'beliefs'},
 {'slug': 'hashgacha',
  'en': 'Hashgacha',
  'he': 'השגחה אלוקית',
  'cat': 'beliefs'},
 {'slug': 'monotheism',
  'en': 'Monotheism',
  'he': 'מונותאיזם',
  'cat': 'beliefs'},
 {'slug': 'gods-existence',
  'en': "God's Existence",
  'he': 'מציאות אלקים',
  'cat': 'beliefs'},
 {'slug': 'gods-will',
  'en': "God's Will",
  'he': 'רצון אלקים',
  'cat': 'beliefs'},
 {'slug': 'god', 'en': 'God', 'he': 'אלוהים', 'cat': 'beliefs'},
 {'slug': 'bat-kol', 'en': 'Bat Kol', 'he': 'בת קול', 'cat': 'beliefs'},
 {'slug': 'gehinnom', 'en': 'Gehinnom', 'he': 'גהינום', 'cat': 'beliefs'},
 {'slug': 'reincarnation',
  'en': 'Reincarnation',
  'he': 'גלגול נשמות',
  'cat': 'beliefs'},
 {'slug': 'religion', 'en': 'Religion', 'he': 'דת', 'cat': 'beliefs'},
 {'slug': 'effect-of-sin',
  'en': 'Effect of Sin',
  'he': 'פעולת החטא',
  'cat': 'beliefs'},
 {'slug': 'impulses', 'en': 'Impulses', 'he': 'יצרים', 'cat': 'beliefs'},
 {'slug': 'priesthood', 'en': 'Priesthood', 'he': 'כהונה', 'cat': 'beliefs'},
 {'slug': 'the-throne-of-glory',
  'en': 'The Throne of Glory',
  'he': 'כסא הכבוד',
  'cat': 'beliefs'},
 {'slug': 'heretics', 'en': 'Heretics', 'he': 'כופרים', 'cat': 'beliefs'},
 {'slug': 'the-future-to-come',
  'en': 'The Future to Come',
  'he': 'לעתיד לבא',
  'cat': 'beliefs'},
 {'slug': 'metatron', 'en': 'Metatron', 'he': 'מטטרון', 'cat': 'beliefs'},
 {'slug': 'michael', 'en': 'Michael', 'he': 'מיכאל', 'cat': 'beliefs'},
 {'slug': 'gabriel-the-angel',
  'en': 'Gabriel the Angel',
  'he': 'המלאך גבריאל',
  'cat': 'beliefs'},
 {'slug': 'chayot', 'en': 'Chayot', 'he': 'חיות', 'cat': 'beliefs'},
 {'slug': 'the-angel-of-death',
  'en': 'The Angel of Death',
  'he': 'מלאך המות',
  'cat': 'beliefs'},
 {'slug': 'maaseh-hamerkavah',
  'en': "Ma'aseh Hamerkavah",
  'he': 'מעשה מרכבה',
  'cat': 'beliefs'},
 {'slug': 'the-effects-of-a-commandment',
  'en': 'The Effects of a Commandment',
  'he': 'פעולת המצווה',
  'cat': 'beliefs'},
 {'slug': 'mitzvot', 'en': 'Mitzvot', 'he': 'מצוות', 'cat': 'beliefs'},
 {'slug': 'the-messianic-era',
  'en': 'The Messianic Era',
  'he': 'ימות המשיח',
  'cat': 'beliefs'},
 {'slug': 'mashiach', 'en': 'Mashiach', 'he': 'משיח', 'cat': 'beliefs'},
 {'slug': 'prophecy', 'en': 'Prophecy', 'he': 'נבואה', 'cat': 'beliefs'},
 {'slug': 'prophets', 'en': 'Prophets', 'he': 'נביאים', 'cat': 'beliefs'},
 {'slug': 'miracles', 'en': 'Miracles', 'he': 'נס', 'cat': 'beliefs'},
 {'slug': 'souls1', 'en': 'Souls', 'he': 'נפש', 'cat': 'beliefs'},
 {'slug': 'extra-soul',
  'en': 'Extra Soul',
  'he': 'נשמה יתרה',
  'cat': 'beliefs'},
 {'slug': 'sitra-achra',
  'en': 'Sitra Achra',
  'he': 'סטרא אחרא',
  'cat': 'beliefs'},
 {'slug': 'samael', 'en': 'Samael', 'he': 'סמאל', 'cat': 'beliefs'},
 {'slug': 'sanhedrin', 'en': 'Sanhedrin', 'he': 'סנהדרין', 'cat': 'history'},
 {'slug': 'sefirot',
  'en': 'Sefirot (Kabbalah)',
  'he': 'ספירות (קבלה)',
  'cat': 'kabbalah'},
 {'slug': 'idolatry', 'en': 'Idolatry', 'he': 'עבודה זרה', 'cat': 'beliefs'},
 {'slug': 'olam-haba', 'en': 'Olam Haba', 'he': 'עולם הבא', 'cat': 'beliefs'},
 {'slug': 'olam-hazeh',
  'en': 'Olam Hazeh',
  'he': 'עולם הזה',
  'cat': 'beliefs'},
 {'slug': 'theodicy', 'en': 'Theodicy', 'he': 'תאודיציה', 'cat': 'beliefs'},
 {'slug': 'holiness', 'en': 'Holiness', 'he': 'קדושה', 'cat': 'beliefs'},
 {'slug': 'rabbinic-authority',
  'en': 'Rabbinic Authority',
  'he': 'רבנות',
  'cat': 'beliefs'},
 {'slug': 'ruach-hakodesh1',
  'en': 'Ruach Hakodesh',
  'he': 'רוח הקודש',
  'cat': 'beliefs'},
 {'slug': 'satan', 'en': 'Satan', 'he': 'שטן', 'cat': 'beliefs'},
 {'slug': 'shekhinah', 'en': 'Shekhinah', 'he': 'שכינה', 'cat': 'beliefs'},
 {'slug': 'the-tetragrammaton',
  'en': 'The Tetragrammaton',
  'he': 'שם הויה',
  'cat': ''},
 {'slug': 'the-written-torah-and-the-oral-torah',
  'en': 'The Written Torah and the Oral Torah',
  'he': 'תורה שבכתב ושבעל פה',
  'cat': 'beliefs'},
 {'slug': 'torah', 'en': 'Torah', 'he': 'תורה', 'cat': 'beliefs'},
 {'slug': 'resurrection',
  'en': 'Resurrection',
  'he': 'תחיית המתים',
  'cat': 'beliefs'},
 {'slug': 'revelation', 'en': 'Revelation', 'he': 'התגלות', 'cat': 'beliefs'},
 {'slug': 'rituals1', 'en': 'Rituals', 'he': 'טקס', 'cat': ''},
 {'slug': 'chosenness', 'en': 'Chosenness', 'he': 'בחירה', 'cat': 'beliefs'},
 {'slug': 'book-of-life',
  'en': 'Book of Life',
  'he': 'ספר החיים',
  'cat': 'beliefs'},
 {'slug': 'prophetess', 'en': 'Prophetess', 'he': 'נביאה', 'cat': 'beliefs'},
 {'slug': 'beit-din', 'en': 'Beit Din', 'he': 'בית דין', 'cat': 'beliefs'},
 {'slug': 'angels', 'en': 'Angels', 'he': 'מלאכים', 'cat': 'supernatural'},
 {'slug': 'yetzer-hatov',
  'en': 'Yetzer Hatov',
  'he': 'יצר טוב',
  'cat': 'beliefs'},
 {'slug': 'yetzer-hara',
  'en': 'Yetzer Hara',
  'he': 'יצר הרע',
  'cat': 'beliefs'},
 {'slug': 'air', 'en': 'Air', 'he': 'אויר', 'cat': 'nature'},
 {'slug': 'animals', 'en': 'Animals', 'he': 'בעלי חיים', 'cat': 'nature'},
 {'slug': 'ants', 'en': 'Ants', 'he': 'נמלה', 'cat': 'nature'},
 {'slug': 'astronomy', 'en': 'Astronomy', 'he': 'אסטרונומיה', 'cat': 'nature'},
 {'slug': 'birds', 'en': 'Birds', 'he': 'ציפורים', 'cat': 'nature'},
 {'slug': 'camels', 'en': 'Camels', 'he': 'גמל', 'cat': 'nature'},
 {'slug': 'cats', 'en': 'Cats', 'he': 'חתול', 'cat': 'nature'},
 {'slug': 'cedars', 'en': 'Cedars', 'he': 'ארז', 'cat': 'nature'},
 {'slug': 'clouds', 'en': 'Clouds', 'he': 'ענן', 'cat': 'nature'},
 {'slug': 'dates', 'en': 'Dates', 'he': 'תמרים', 'cat': 'nature'},
 {'slug': 'deserts', 'en': 'Deserts', 'he': 'מדבר', 'cat': 'nature'},
 {'slug': 'nature', 'en': 'Nature', 'he': 'טבע', 'cat': 'nature'},
 {'slug': 'dew', 'en': 'Dew', 'he': 'טל', 'cat': 'nature'},
 {'slug': 'dirt', 'en': 'Dirt', 'he': 'עפר', 'cat': 'nature'},
 {'slug': 'dogs', 'en': 'Dogs', 'he': 'כלב', 'cat': 'nature'},
 {'slug': 'donkeys', 'en': 'Donkeys', 'he': 'חמור', 'cat': 'nature'},
 {'slug': 'doves', 'en': 'Doves', 'he': 'יונה', 'cat': 'nature'},
 {'slug': 'eagles', 'en': 'Eagles', 'he': 'נשר', 'cat': 'nature'},
 {'slug': 'earth', 'en': 'Earth', 'he': 'תֵּבֵל', 'cat': 'nature'},
 {'slug': 'ecology', 'en': 'Ecology', 'he': 'אקולוגיה', 'cat': 'nature'},
 {'slug': 'environment', 'en': 'Environment', 'he': 'סביבה', 'cat': 'nature'},
 {'slug': 'ewes', 'en': 'Ewes', 'he': 'אילה', 'cat': 'nature'},
 {'slug': 'figs', 'en': 'Figs', 'he': 'תאנה', 'cat': 'nature'},
 {'slug': 'fire', 'en': 'Fire', 'he': 'אש', 'cat': 'nature'},
 {'slug': 'fish', 'en': 'Fish', 'he': 'דג', 'cat': 'nature'},
 {'slug': 'flax', 'en': 'Flax', 'he': 'פשתים', 'cat': 'nature'},
 {'slug': 'frogs', 'en': 'Frogs', 'he': 'צפרדע', 'cat': 'nature'},
 {'slug': 'gazelles', 'en': 'Gazelles', 'he': 'צבי', 'cat': 'nature'},
 {'slug': 'goats', 'en': 'Goats', 'he': 'עז', 'cat': 'nature'},
 {'slug': 'goats-(שעירים)',
  'en': 'Goats (שעירים)',
  'he': 'שעירים',
  'cat': 'nature'},
 {'slug': 'grapes', 'en': 'Grapes', 'he': 'ענבים', 'cat': 'nature'},
 {'slug': 'grass', 'en': 'Grass', 'he': 'עשב', 'cat': 'nature'},
 {'slug': 'horses', 'en': 'Horses', 'he': 'סוס', 'cat': 'nature'},
 {'slug': 'lambs', 'en': 'Lambs', 'he': 'כבש', 'cat': 'nature'},
 {'slug': 'land', 'en': 'Land', 'he': 'ארץ', 'cat': 'nature'},
 {'slug': 'light', 'en': 'Light', 'he': 'אור', 'cat': 'nature'},
 {'slug': 'lilies', 'en': 'Lilies', 'he': 'שושנה', 'cat': 'nature'},
 {'slug': 'lions', 'en': 'Lions', 'he': 'אריה', 'cat': 'nature'},
 {'slug': 'arbeh', 'en': 'Locusts', 'he': 'ארבה', 'cat': 'nature'},
 {'slug': 'man-and-animals',
  'en': 'Man and Animals',
  'he': 'אדם ובעלי חיים',
  'cat': 'nature'},
 {'slug': 'mice', 'en': 'Mice', 'he': 'עכבר', 'cat': 'nature'},
 {'slug': 'mountains', 'en': 'Mountains', 'he': 'הר', 'cat': 'nature'},
 {'slug': 'mules', 'en': 'Mules', 'he': 'פרד', 'cat': 'nature'},
 {'slug': 'myrtles', 'en': 'Myrtles', 'he': 'הדס', 'cat': 'nature'},
 {'slug': 'night', 'en': 'Night', 'he': 'לילה', 'cat': 'nature'},
 {'slug': 'oxen', 'en': 'Oxen', 'he': 'שור', 'cat': 'nature'},
 {'slug': 'pigs', 'en': 'Pigs', 'he': 'חזיר', 'cat': 'nature'},
 {'slug': 'plants', 'en': 'Plants', 'he': 'צמח', 'cat': 'nature'},
 {'slug': 'rain', 'en': 'Rain', 'he': 'גשם', 'cat': 'nature'},
 {'slug': 'rams', 'en': 'Rams', 'he': 'איל', 'cat': 'nature'},
 {'slug': 'ravens', 'en': 'Ravens', 'he': 'עורב', 'cat': 'nature'},
 {'slug': 'rivers', 'en': 'Rivers', 'he': 'נהר', 'cat': 'nature'},
 {'slug': 'roosters', 'en': 'Roosters', 'he': 'תרנגול', 'cat': 'nature'},
 {'slug': 'science', 'en': 'Science', 'he': 'מדע', 'cat': 'nature'},
 {'slug': 'scorpions', 'en': 'Scorpions', 'he': 'עקרב', 'cat': 'nature'},
 {'slug': 'seas1', 'en': 'Seas', 'he': 'ים', 'cat': 'nature'},
 {'slug': 'sherets', 'en': 'Sherets', 'he': 'שרץ', 'cat': 'nature'},
 {'slug': 'snakes1', 'en': 'Snakes', 'he': 'נחש', 'cat': 'nature'},
 {'slug': 'snow', 'en': 'Snow', 'he': 'שלג', 'cat': 'nature'},
 {'slug': 'spring', 'en': 'Spring', 'he': 'אביב', 'cat': 'nature'},
 {'slug': 'springs', 'en': 'Springs', 'he': 'מעין', 'cat': 'nature'},
 {'slug': 'summer', 'en': 'Summer', 'he': 'קיץ', 'cat': 'nature'},
 {'slug': 'sun', 'en': 'Sun', 'he': 'שמש', 'cat': 'nature'},
 {'slug': 'sustainability', 'en': 'Sustainability', 'he': 'קיימות', 'cat': ''},
 {'slug': 'tapuach', 'en': 'Tapuach', 'he': 'תפוח', 'cat': 'nature'},
 {'slug': 'the-elements',
  'en': 'The Elements',
  'he': 'ארבעה יסודות',
  'cat': 'nature'},
 {'slug': 'the-moon', 'en': 'The Moon', 'he': 'לבנה', 'cat': 'nature'},
 {'slug': 'the-ocean', 'en': 'The Ocean', 'he': 'אוקיינוס', 'cat': 'nature'},
 {'slug': 'trees', 'en': 'Trees', 'he': 'עץ', 'cat': 'nature'},
 {'slug': 'vines', 'en': 'Vines', 'he': 'גפן', 'cat': 'nature'},
 {'slug': 'water', 'en': 'Water', 'he': 'מים', 'cat': 'nature'},
 {'slug': 'weather', 'en': 'Weather', 'he': 'מזג אויר', 'cat': 'nature'},
 {'slug': 'wild-animals', 'en': 'Wild Animals', 'he': 'חיה', 'cat': 'nature'},
 {'slug': 'willows', 'en': 'Willows', 'he': 'ערבה (עץ)', 'cat': 'nature'},
 {'slug': 'winds', 'en': 'Winds', 'he': 'רוח', 'cat': 'nature'},
 {'slug': 'wolves', 'en': 'Wolves', 'he': 'זאב', 'cat': 'nature'},
 {'slug': 'worms', 'en': 'Worms', 'he': 'תולעים', 'cat': 'nature'},
 {'slug': 'yavneh', 'en': 'Yavneh', 'he': 'יבנה', 'cat': 'places'},
 {'slug': 'edom', 'en': 'Edom', 'he': 'אדום (עם)', 'cat': 'places'},
 {'slug': 'ohel-moed', 'en': 'Ohel Moed', 'he': 'אוהל מועד', 'cat': 'places'},
 {'slug': 'the-four-kingdoms',
  'en': 'The Four Kingdoms',
  'he': 'ארבע מלכויות',
  'cat': 'places'},
 {'slug': 'alexandria',
  'en': 'Alexandria',
  'he': 'אלכסנדריא',
  'cat': 'places'},
 {'slug': 'the-four-rivers',
  'en': 'The Four Rivers',
  'he': 'ארבעה נהרות',
  'cat': 'places'},
 {'slug': 'distinctions-of-the-land-of-israel',
  'en': 'Distinctions of the Land of Israel',
  'he': 'מעלות ארץ ישראל',
  'cat': 'places'},
 {'slug': 'babel', 'en': 'Babel', 'he': 'בבל', 'cat': 'places'},
 {'slug': 'beersheba', 'en': 'Beersheba', 'he': 'באר שבע', 'cat': 'places'},
 {'slug': 'beit-el', 'en': 'Beit El', 'he': 'בית אל', 'cat': 'places'},
 {'slug': 'beit-hamikdash',
  'en': 'Beit Hamikdash',
  'he': 'בית המקדש',
  'cat': 'places'},
 {'slug': 'beitar', 'en': 'Beitar', 'he': 'ביתר', 'cat': 'places'},
 {'slug': 'galil', 'en': 'Galil', 'he': 'גליל', 'cat': 'places'},
 {'slug': 'germany', 'en': 'Germany', 'he': 'גרמניה', 'cat': 'places'},
 {'slug': 'damascus', 'en': 'Damascus', 'he': 'דמשק', 'cat': 'places'},
 {'slug': 'har-gerizim-vehar-eival',
  'en': 'Mount Gerizim and Mount Ebal',
  'he': 'הר גריזים ועיבל',
  'cat': 'places'},
 {'slug': 'moriah', 'en': 'Moriah', 'he': 'הר המוריה', 'cat': 'places'},
 {'slug': 'outside-of-israel',
  'en': 'Outside of Israel',
  'he': 'חוץ לארץ',
  'cat': 'places'},
 {'slug': 'tiberias', 'en': 'Tiberias', 'he': 'טבריה', 'cat': 'places'},
 {'slug': 'the-land-of-judah',
  'en': 'The Land of Judah',
  'he': 'ארץ יהודה',
  'cat': 'places'},
 {'slug': 'greece', 'en': 'Greece', 'he': 'יון', 'cat': 'places'},
 {'slug': 'jerusalem', 'en': 'Jerusalem', 'he': 'ירושלים', 'cat': 'places'},
 {'slug': 'kush', 'en': 'Kush', 'he': 'כוש', 'cat': 'places'},
 {'slug': 'levite-cities',
  'en': 'Levite Cities',
  'he': 'ערי הלויים',
  'cat': 'places'},
 {'slug': 'midian', 'en': 'Midian', 'he': 'מדין', 'cat': 'places'},
 {'slug': 'moab', 'en': 'Moab', 'he': 'מואב', 'cat': 'places'},
 {'slug': 'partitions',
  'en': 'Partitions',
  'he': 'מחיצה (כללי)',
  'cat': 'places'},
 {'slug': 'encampment-of-israel',
  'en': 'Encampment of Israel',
  'he': 'מחנה ישראל',
  'cat': 'places'},
 {'slug': 'cave-of-the-patriarchs',
  'en': 'Cave of the Patriarchs',
  'he': 'מערת המכפלה',
  'cat': 'places'},
 {'slug': 'egypt', 'en': 'Egypt', 'he': 'מצרים', 'cat': 'places'},
 {'slug': 'tabernacle-courtyard',
  'en': 'Tabernacle Courtyard',
  'he': 'חצר המשכן',
  'cat': 'places'},
 {'slug': 'the-nile-river',
  'en': 'The Nile River',
  'he': 'נילוס',
  'cat': 'places'},
 {'slug': 'nineveh', 'en': 'Nineveh', 'he': 'נינוה', 'cat': 'places'},
 {'slug': 'sodom', 'en': 'Sodom', 'he': 'סדום', 'cat': 'places'},
 {'slug': 'syria', 'en': 'Syria', 'he': 'סוריה', 'cat': 'places'},
 {'slug': 'ever-hayarden',
  'en': 'Ever HaYarden',
  'he': 'עבר הירדן',
  'cat': 'places'},
 {'slug': 'cities', 'en': 'Cities', 'he': 'עיר', 'cat': 'places'},
 {'slug': 'ammon', 'en': 'Ammon', 'he': 'עמון', 'cat': 'places'},
 {'slug': 'gemorrah', 'en': 'Gemorrah', 'he': 'עמורה', 'cat': 'places'},
 {'slug': 'tyre', 'en': 'Tyre', 'he': 'צור', 'cat': 'places'},
 {'slug': 'zion', 'en': 'Zion', 'he': 'ציון', 'cat': 'places'},
 {'slug': 'rome', 'en': 'Rome', 'he': 'רומי', 'cat': 'places'},
 {'slug': 'the-tabernacle-in-shiloh',
  'en': 'The Tabernacle in Shiloh',
  'he': 'משכן שילה',
  'cat': 'places'},
 {'slug': 'shechem', 'en': 'Shechem', 'he': 'שכם', 'cat': 'places'},
 {'slug': 'heavens', 'en': 'Heavens', 'he': 'שמים', 'cat': 'nature'},
 {'slug': 'sharon', 'en': 'HaSharon', 'he': 'השרון', 'cat': 'places'},
 {'slug': 'tarshish', 'en': 'Tarshish', 'he': 'תרשיש', 'cat': 'places'},
 {'slug': 'beit-midrash',
  'en': 'Beit Midrash',
  'he': 'בית מדרש',
  'cat': 'places'},
 {'slug': 'temple-mount',
  'en': 'Temple Mount',
  'he': 'הר הבית',
  'cat': 'places'},
 {'slug': 'red-sea', 'en': 'Red Sea', 'he': 'ים סוף', 'cat': 'places'},
 {'slug': 'mount-sinai',
  'en': 'Mount Sinai',
  'he': 'הר סיני',
  'cat': 'places'},
 {'slug': 'second-temple',
  'en': 'Second Temple',
  'he': 'בית שני',
  'cat': 'places'},
 {'slug': 'en-dor', 'en': 'En Dor', 'he': 'עין דור', 'cat': 'places'},
 {'slug': 'jericho', 'en': 'Jericho', 'he': 'יריחו', 'cat': 'places'},
 {'slug': 'israel', 'en': 'Israel', 'he': 'ישראל', 'cat': 'places'},
 {'slug': 'ashur', 'en': 'Assyria', 'he': 'אשור', 'cat': 'places'},
 {'slug': 'food', 'en': 'Food', 'he': 'מזון', 'cat': 'food'},
 {'slug': 'eating', 'en': 'Eating', 'he': 'אכילה', 'cat': 'food'},
 {'slug': 'honey', 'en': 'Honey', 'he': '', 'cat': ''},
 {'slug': 'olives', 'en': 'Olives', 'he': 'זיתים', 'cat': 'food'},
 {'slug': 'milk', 'en': 'Milk', 'he': 'חָלָב', 'cat': 'food'},
 {'slug': 'challah', 'en': 'Challah', 'he': 'חלה', 'cat': 'food'},
 {'slug': 'chametz', 'en': 'Chametz', 'he': 'חמץ', 'cat': 'food'},
 {'slug': 'agriculture', 'en': 'Agriculture', 'he': 'חקלאות', 'cat': 'food'},
 {'slug': 'wine', 'en': 'Wine', 'he': 'יין', 'cat': 'food'},
 {'slug': 'fresh-grain', 'en': 'Fresh Grain', 'he': 'כרמל', 'cat': 'food'},
 {'slug': 'bread', 'en': 'Bread', 'he': 'לחם', 'cat': 'food'},
 {'slug': 'kashrut', 'en': 'Kashrut', 'he': 'כשרות', 'cat': 'food'},
 {'slug': 'maror', 'en': 'Maror', 'he': 'מרור', 'cat': 'food'},
 {'slug': 'planting', 'en': 'Planting', 'he': 'שתילה', 'cat': 'food'},
 {'slug': 'peppers', 'en': 'Peppers', 'he': 'פלפל', 'cat': 'food'},
 {'slug': 'fruit', 'en': 'Fruit', 'he': 'פרי', 'cat': 'food'},
 {'slug': 'flour', 'en': 'Flour', 'he': 'קמח', 'cat': 'food'},
 {'slug': 'drinking', 'en': 'Drinking', 'he': 'שתיה', 'cat': 'food'},
 {'slug': 'spices', 'en': 'Spices', 'he': 'תבלין', 'cat': 'food'},
 {'slug': 'food-ethics', 'en': 'Food Ethics', 'he': '', 'cat': ''},
 {'slug': 'alcohol', 'en': 'Alcohol', 'he': 'אלכוהול', 'cat': 'food'},
 {'slug': 'vegetarianism',
  'en': 'Vegetarianism',
  'he': 'צמחונות',
  'cat': 'food'},
 {'slug': 'meat', 'en': 'Meat', 'he': 'בשר', 'cat': 'food'},
 {'slug': 'kitniyot', 'en': 'Kitniyot', 'he': 'קטניות', 'cat': 'food'},
 {'slug': 'matzah', 'en': 'Matzah', 'he': 'מצה', 'cat': 'food'},
 {'slug': 'pomegranates', 'en': 'Pomegranates', 'he': 'רימון', 'cat': 'food'},
 {'slug': 'wheat', 'en': 'Wheat', 'he': 'חטה', 'cat': 'food'},
 {'slug': 'philosophy',
  'en': 'Philosophy',
  'he': 'פילוסופיה',
  'cat': 'philosophy'},
 {'slug': 'ethics', 'en': 'Ethics', 'he': 'אתיקה', 'cat': 'philosophy'},
 {'slug': 'human-knowledge',
  'en': 'Human Knowledge',
  'he': 'ידיעה אנושית',
  'cat': 'philosophy'},
 {'slug': 'free-will',
  'en': 'Free Will',
  'he': 'בחירה חופשית',
  'cat': 'philosophy'},
 {'slug': 'evil', 'en': 'Evil', 'he': 'רוע', 'cat': ''},
 {'slug': 'time', 'en': 'Time', 'he': 'זמן', 'cat': 'philosophy'},
 {'slug': 'dreams', 'en': 'Dreams', 'he': 'חלום', 'cat': 'philosophy'},
 {'slug': 'beauty', 'en': 'Beauty', 'he': 'יופי', 'cat': 'philosophy'},
 {'slug': 'thoughts', 'en': 'Thoughts', 'he': 'מחשבה', 'cat': 'philosophy'},
 {'slug': 'actuality', 'en': 'Reality', 'he': 'מציאות', 'cat': 'philosophy'},
 {'slug': 'evildoers', 'en': 'Evildoers', 'he': 'רשע', 'cat': 'philosophy'},
 {'slug': 'jewish-identity',
  'en': 'Jewish Identity',
  'he': 'זהות יהודית',
  'cat': 'philosophy'},
 {'slug': 'universalism',
  'en': 'Universalism',
  'he': 'אוניברסליזם',
  'cat': 'philosophy'},
 {'slug': 'psychology',
  'en': 'Psychology',
  'he': 'פסיכולוגיה',
  'cat': 'philosophy'},
 {'slug': 'determinism',
  'en': 'Determinism',
  'he': 'דטרמיניזם',
  'cat': 'philosophy'},
 {'slug': 'knowledge', 'en': 'Knowledge', 'he': 'ידע', 'cat': 'philosophy'},
 {'slug': 'purpose-of-life',
  'en': 'Purpose of Life',
  'he': 'תפקיד החיים',
  'cat': 'philosophy'},
 {'slug': 'good', 'en': 'Good', 'he': 'טוב', 'cat': 'philosophy'},
 {'slug': 'folklore',
  'en': 'Folklore',
  'he': 'פולקלור',
  'cat': 'supernatural'},
 {'slug': 'superstitions1',
  'en': 'Superstitions',
  'he': 'אמונה טפלה',
  'cat': 'supernatural'},
 {'slug': 'magicians',
  'en': 'Magicians',
  'he': 'חרטומים',
  'cat': 'supernatural'},
 {'slug': 'harmful-forces',
  'en': 'Harmful Forces',
  'he': 'מזיקין',
  'cat': 'supernatural'},
 {'slug': 'demons', 'en': 'Demons', 'he': 'שדים', 'cat': 'supernatural'},
 {'slug': 'golems', 'en': 'Golems', 'he': 'גולם', 'cat': 'supernatural'},
 {'slug': 'infertility', 'en': 'Infertility', 'he': 'עקרות', 'cat': 'health'},
 {'slug': 'medicine', 'en': 'Medicine', 'he': 'תרופה', 'cat': 'health'},
 {'slug': 'mental-health', 'en': 'Mental Health', 'he': '', 'cat': 'health'},
 {'slug': 'organ-donation',
  'en': 'Organ Donation',
  'he': 'תרומת איברים',
  'cat': 'health'},
 {'slug': 'physicians', 'en': 'Physicians', 'he': 'רופא', 'cat': 'health'},
 {'slug': 'sleep', 'en': 'Sleep', 'he': 'שינה', 'cat': 'health'},
 {'slug': 'health', 'en': 'Health', 'he': 'בריאות', 'cat': 'health'},
 {'slug': 'art', 'en': 'Art', 'he': 'אָמָּנוּת', 'cat': 'art'},
 {'slug': 'colors', 'en': 'Colors', 'he': 'צבע', 'cat': 'art'},
 {'slug': 'songs', 'en': 'Songs', 'he': 'שירים', 'cat': 'art'},
 {'slug': 'music', 'en': 'Music', 'he': 'מוסיקה', 'cat': 'art'},
 {'slug': 'piyyut', 'en': 'Piyyut', 'he': 'פיוט', 'cat': 'prayer'},
 {'slug': 'dances1', 'en': 'Dances', 'he': 'ריקוד', 'cat': 'art'},
 {'slug': 'poetry', 'en': 'Poetry', 'he': 'שירה', 'cat': 'art'},
 {'slug': 'rabbi-akiva',
  'en': 'Rabbi Akiva',
  'he': 'רבי עקיבא',
  'cat': 'talmudic-figures'},
 {'slug': 'shimon-bar-yochai',
  'en': 'Shimon Bar Yochai',
  'he': 'שמעון בר יוחאי',
  'cat': 'talmudic-figures'},
 {'slug': 'nahum-of-gamzo',
  'en': 'Nahum of Gamzo',
  'he': 'נחום איש גמזו',
  'cat': 'talmudic-figures'},
 {'slug': 'avtalyon',
  'en': 'Avtalyon',
  'he': 'אבטליון',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-meir',
  'en': 'Rabbi Meir',
  'he': 'רבי מאיר',
  'cat': 'talmudic-figures'},
 {'slug': 'shemaiah',
  'en': 'Shemaiah',
  'he': 'שמעיה',
  'cat': 'talmudic-figures'},
 {'slug': 'shammai', 'en': 'Shammai', 'he': 'שמאי', 'cat': 'talmudic-figures'},
 {'slug': 'hillel', 'en': 'Hillel', 'he': 'הִלֵּל', 'cat': 'talmudic-figures'},
 {'slug': 'rav',
  'en': 'Rav',
  'he': 'רב (שם אמורא)',
  'cat': 'talmudic-figures'},
 {'slug': 'rava', 'en': 'Rava', 'he': 'רבא', 'cat': 'talmudic-figures'},
 {'slug': 'rav-sheshet',
  'en': 'Rav Sheshet',
  'he': 'רב ששת',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-eliezer-b-hyrcanus',
  'en': 'Rabbi Eliezer b. Hyrcanus',
  'he': 'רבי אליעזר',
  'cat': 'talmudic-figures'},
 {'slug': 'akavyah-b-mahalalel',
  'en': "Akavyah b. Mahalal'el",
  'he': 'עקביא בן מהללאל',
  'cat': 'talmudic-figures'},
 {'slug': 'rabban-shimon-b-gamliel-(ii)',
  'en': 'Rabban Shimon b. Gamliel (II)',
  'he': 'רבן שמעון בן גמליאל (2)',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-shimon-b-lakish',
  'en': 'Rabbi Shimon b. Lakish',
  'he': 'רבי שמעון בן לקיש',
  'cat': 'talmudic-figures'},
 {'slug': 'rabi', 'en': 'Rabi', 'he': 'רבי', 'cat': 'talmudic-figures'},
 {'slug': 'rav-zera',
  'en': 'Rav Zera',
  'he': 'רב זירא',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbah-bar-bar-chanah',
  'en': 'Rabbah Bar Bar Chanah',
  'he': 'רבה בר בר חנה',
  'cat': 'talmudic-figures'},
 {'slug': 'shimon-b-zoma',
  'en': '[Shimon] b. Zoma',
  'he': 'בן זומא',
  'cat': 'talmudic-figures'},
 {'slug': 'sumkhos',
  'en': 'Sumkhos',
  'he': 'סומכוס',
  'cat': 'talmudic-figures'},
 {'slug': 'ulla', 'en': 'Ulla', 'he': 'עולא', 'cat': 'talmudic-figures'},
 {'slug': 'rabbi-yohanan-hasandlar',
  'en': 'Rabbi Yohanan Hasandlar',
  'he': 'ר יוחנן הסנדלר',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-yehoshua-b-levi',
  'en': 'Rabbi Yehoshua b. Levi',
  'he': 'רבי יהושע בן לוי',
  'cat': 'talmudic-figures'},
 {'slug': 'abaye', 'en': 'Abaye', 'he': 'אביי', 'cat': 'talmudic-figures'},
 {'slug': 'elisha-ben-abuya',
  'en': 'Elisha Ben Abuya',
  'he': 'אלישע בן אבויה',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-elazar-b-azaryah',
  'en': 'Rabbi Elazar b. Azaryah',
  'he': 'רבי אלעזר בן עזריה',
  'cat': 'talmudic-figures'},
 {'slug': 'rabban-yochanan-b-zakkai',
  'en': 'Rabban Yochanan b. Zakkai',
  'he': 'רבן יוחנן בן זכאי',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-chanina-b-dosa',
  'en': 'Rabbi Chanina b. Dosa',
  'he': 'רבי חנינא בן דוסא',
  'cat': 'talmudic-figures'},
 {'slug': 'yochanan-ben-bag-bag',
  'en': '[Yochanan] Ben Bag Bag',
  'he': 'יוחנן בן בג בג',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-chiyya',
  'en': 'Rabbi Chiyya',
  'he': 'רבי חייא',
  'cat': 'talmudic-figures'},
 {'slug': 'beruriah',
  'en': 'Beruriah',
  'he': 'ברוריה',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-hananyah-b-teradyon',
  'en': 'Rabbi Hananyah b. Teradyon',
  'he': 'רבי חנינה בן תרדיון',
  'cat': 'talmudic-figures'},
 {'slug': 'shmuel-(amora)',
  'en': 'Shmuel (Amora)',
  'he': 'שמואל (שם אמורא)',
  'cat': 'talmudic-figures'},
 {'slug': 'shimon-b-shetach',
  'en': 'Shimon b. Shetach',
  'he': 'שמעון בן שטח',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-yehoshua-b-hananyah',
  'en': 'Rabbi Yehoshua [b. Hananyah]',
  'he': 'ר יהושע',
  'cat': 'talmudic-figures'},
 {'slug': 'shimon-b-azzai',
  'en': '[Shimon] b. Azzai',
  'he': 'בן עזאי',
  'cat': 'talmudic-figures'},
 {'slug': 'bar-kokhba',
  'en': 'Bar Kokhba',
  'he': 'בר כוכבא',
  'cat': 'talmudic-figures'},
 {'slug': 'rabbi-tarfon',
  'en': 'Rabbi Tarfon',
  'he': 'רבי טרפון',
  'cat': 'talmudic-figures'},
 {'slug': 'rav-pappa',
  'en': 'Rav Pappa',
  'he': 'רב פפא',
  'cat': 'talmudic-figures'},
 {'slug': 'rav-chisda',
  'en': 'Rav Chisda',
  'he': 'רב חסדא',
  'cat': 'talmudic-figures'},
 {'slug': 'rabban-gamliel',
  'en': 'Rabban Gamliel of Yavneh (II)',
  'he': 'רבן גמליאל דיבנה',
  'cat': 'talmudic-figures'},
 {'slug': 'rav-ashi',
  'en': 'Rav Ashi',
  'he': 'רב אשי',
  'cat': 'talmudic-figures'},
 {'slug': 'rav-huna',
  'en': 'Rav Huna',
  'he': 'רב הונא',
  'cat': 'talmudic-figures'},
 {'slug': '13-principles-of-faith',
  'en': '13 Principles of Faith',
  'he': '',
  'cat': 'beliefs'},
 {'slug': 'redemption-of-captives',
  'en': 'Redemption of Captives',
  'he': 'פדיון שבויים',
  'cat': 'laws'},
 {'slug': 'mishloach-manot',
  'en': 'Mishloach Manot',
  'he': 'משלוח מנות',
  'cat': 'laws'},
 {'slug': 'the-book-of-esther',
  'en': 'The Book of Esther',
  'he': 'מגילת אסתר',
  'cat': 'stories'},
 {'slug': 'zachor', 'en': 'Zachor', 'he': 'זכור', 'cat': 'prayer'},
 {'slug': 'oral-torah',
  'en': 'Oral Torah',
  'he': 'תורה שבעל פה',
  'cat': 'halachic-principles'},
 {'slug': 'kings', 'en': 'Kings', 'he': 'מלך', 'cat': 'social-issues'},
 {'slug': 'sacrifices', 'en': 'Sacrifices', 'he': 'קרבן', 'cat': 'laws'},
 {'slug': 'shemitah',
  'en': 'Shemittah',
  'he': 'שמיטה',
  'cat': 'agricultural-law'},
 {'slug': 'jubilee', 'en': 'Jubilee', 'he': 'יובל', 'cat': ''},
 {'slug': 'eye-for-an-eye',
  'en': 'Eye for an Eye',
  'he': 'עין תחת עין',
  'cat': 'halachic-principles'},
 {'slug': 'cities-of-refuge',
  'en': 'Cities of Refuge',
  'he': 'ערי מקלט',
  'cat': ''},
 {'slug': 'exile', 'en': 'Exile', 'he': 'גלות', 'cat': 'history'},
 {'slug': 'bikkurim',
  'en': 'Bikkurim',
  'he': 'ביכורים',
  'cat': 'agricultural-law'},
 {'slug': 'shifrah-and-puah1',
  'en': 'Shifrah and Puah',
  'he': 'שפרה ופועה',
  'cat': 'biblical-figures'},
 {'slug': 'rainbows', 'en': 'Rainbows', 'he': '', 'cat': ''},
 {'slug': 'gift-giving',
  'en': 'Gift Giving',
  'he': 'דיני מתנות ותרומות',
  'cat': 'laws'},
 {'slug': 'minhag',
  'en': 'Minhag',
  'he': 'מנהג',
  'cat': 'halachic-principles'},
 {'slug': 'ben-sorer-umoreh',
  'en': 'Ben Sorer Umoreh',
  'he': 'בן סורר ומורה',
  'cat': 'family-law'},
 {'slug': 'the-four-parshiot',
  'en': 'The Four Parshiot',
  'he': 'ארבע פרשיות',
  'cat': ''},
 {'slug': 'tzaraat', 'en': 'Tzara’at', 'he': 'צרעת', 'cat': 'stories'},
 {'slug': 'tumah', 'en': 'Tumah', 'he': 'טומאה', 'cat': ''},
 {'slug': 'taharah',
  'en': 'Taharah',
  'he': 'טהרה',
  'cat': 'laws-of-impurity-and-purity'},
 {'slug': 'niddah',
  'en': 'Niddah',
  'he': 'נידה',
  'cat': 'laws-of-impurity-and-purity'},
 {'slug': 'hasmoneans',
  'en': 'Hasmoneans',
  'he': 'חשמונאים',
  'cat': 'history'},
 {'slug': 'the-book-of-ruth',
  'en': 'The Book of Ruth',
  'he': 'מגילת רות',
  'cat': ''},
 {'slug': 'clothing', 'en': 'Clothing', 'he': 'בגדים', 'cat': ''},
 {'slug': 'head-coverings',
  'en': 'Head Coverings',
  'he': 'כסוי הראש',
  'cat': 'ritual-objects'},
 {'slug': 'adar', 'en': 'Adar', 'he': 'אדר', 'cat': ''},
 {'slug': 'baseless-hatred1',
  'en': 'Baseless Hatred',
  'he': 'שנאת חינם',
  'cat': 'values'},
 {'slug': 'altars', 'en': 'Altars', 'he': 'מזבחות', 'cat': 'ritual-objects'},
 {'slug': 'seven-species',
  'en': 'Seven Species',
  'he': 'שבעת המינים',
  'cat': 'food'},
 {'slug': 'jewish-unity',
  'en': 'Jewish Unity',
  'he': 'אחדות ישראל',
  'cat': ''},
 {'slug': 'lashon-hara',
  'en': 'Lashon Hara',
  'he': 'לשון הרע',
  'cat': 'human-ethics'},
 {'slug': 'justice', 'en': 'Justice', 'he': 'צדק', 'cat': 'values'},
 {'slug': 'tekhelet', 'en': 'Tekhelet', 'he': 'תכלת', 'cat': ''},
 {'slug': 'halakhah', 'en': 'Halakhah', 'he': 'הלכה', 'cat': ''},
 {'slug': 'minyan',
  'en': 'Minyan',
  'he': 'מניין (מושג הלכתי)',
  'cat': 'laws-of-prayer'},
 {'slug': 'kiddush-hashem',
  'en': 'Kiddush Hashem',
  'he': 'קידוש השם',
  'cat': ''},
 {'slug': 'shaliach-tsibur',
  'en': 'Shaliach Tsibur',
  'he': 'שליח צבור',
  'cat': 'laws-of-prayer'},
 {'slug': 'azazel', 'en': 'Azazel', 'he': 'עזאזל', 'cat': ''},
 {'slug': 'chasidut', 'en': 'Chasidut', 'he': 'חסידות (תנועה)', 'cat': ''},
 {'slug': 'agunah', 'en': 'Agunah', 'he': 'עגונה', 'cat': 'family-law'},
 {'slug': 'judges-(שופט)', 'en': 'Judges (שופט)', 'he': 'שופט', 'cat': ''},
 {'slug': 'babylonian-exile',
  'en': 'Babylonian Exile',
  'he': 'גלות בבל',
  'cat': 'history'},
 {'slug': 'yannai', 'en': 'King Yannai', 'he': 'ינאי המלך', 'cat': 'history'},
 {'slug': 'letters', 'en': 'Letters', 'he': 'אותיות', 'cat': ''},
 {'slug': 'numbers', 'en': 'Numbers', 'he': 'מספר', 'cat': ''},
 {'slug': 'ushpizin', 'en': 'Ushpizin', 'he': 'אושפיזין', 'cat': ''},
 {'slug': 'bodies', 'en': 'Body', 'he': 'גוף', 'cat': 'health'},
 {'slug': 'shalosh-regalim',
  'en': 'Shalosh Regalim',
  'he': 'שלושה רגלים',
  'cat': 'laws-of-the-calendar'},
 {'slug': 'writing', 'en': 'Writing', 'he': 'כתיבה', 'cat': ''},
 {'slug': 'gender', 'en': 'Gender', 'he': 'מין', 'cat': 'social-issues'},
 {'slug': 'humanity', 'en': 'Humanity', 'he': 'אנושיות', 'cat': ''},
 {'slug': 'calendar', 'en': 'Calendar', 'he': 'לוח שנה', 'cat': ''},
 {'slug': 'safek', 'en': 'Safek', 'he': 'ספק', 'cat': ''},
 {'slug': 'stars', 'en': 'Stars', 'he': 'כוכב', 'cat': ''},
 {'slug': 'burning-bush', 'en': 'Burning Bush', 'he': 'סנה בוער', 'cat': ''},
 {'slug': 'tikkun-olam',
  'en': 'Tikkun Olam',
  'he': 'תיקון עולם',
  'cat': 'halachic-principles'},
 {'slug': 'students', 'en': 'Students', 'he': 'תלמיד', 'cat': ''},
 {'slug': 'birthright', 'en': 'Birthright', 'he': 'בכורה', 'cat': ''},
 {'slug': 'pregnancy', 'en': 'Pregnancy', 'he': 'הריון (תהליך)', 'cat': ''},
 {'slug': 'women-in-tanakh1',
  'en': 'Women in Tanakh',
  'he': 'נשים בתנ"ך',
  'cat': ''},
 {'slug': 'sadness', 'en': 'Sadness', 'he': 'עצב', 'cat': ''},
 {'slug': 'oaths',
  'en': 'Oaths',
  'he': 'שבועה',
  'cat': 'laws-of-optional-restrictions'},
 {'slug': 'laughter', 'en': 'Laughter', 'he': 'צחוק', 'cat': ''},
 {'slug': 'birthdays', 'en': 'Birthdays', 'he': 'יום הולדת', 'cat': ''},
 {'slug': 'aron-habrit',
  'en': 'Aron HaBrit',
  'he': 'ארון הברית',
  'cat': 'laws-of-worship-of-god'},
 {'slug': 'mistakes', 'en': 'Mistakes', 'he': 'טעות', 'cat': ''},
 {'slug': 'nazir',
  'en': 'Nazir',
  'he': 'נזיר',
  'cat': 'laws-of-optional-restrictions'},
 {'slug': 'midrash', 'en': 'Midrash', 'he': 'מדרש', 'cat': ''},
 {'slug': 'vows',
  'en': 'Vows',
  'he': 'נדרים',
  'cat': 'laws-of-optional-restrictions'},
 {'slug': 'eruv', 'en': 'Eruv', 'he': '', 'cat': ''},
 {'slug': 'kal-vechomer',
  'en': 'Kal Vechomer',
  'he': 'קל וחומר',
  'cat': 'halachic-principles'},
 {'slug': 'netilat-yadayim',
  'en': 'Netilat Yadayim',
  'he': 'נטילת ידים',
  'cat': 'laws-of-impurity-and-purity'},
 {'slug': 'father', 'en': 'Father', 'he': '', 'cat': ''},
 {'slug': 'pirkei-avot',
  'en': 'Pirkei Avot',
  'he': 'פרקי אבות',
  'cat': 'values'},
 {'slug': 'haftarah', 'en': 'Haftarah', 'he': 'הפטרה', 'cat': ''},
 {'slug': 'mishnah', 'en': 'Mishnah', 'he': 'משנה', 'cat': ''},
 {'slug': 'talmud', 'en': 'Talmud', 'he': 'תלמוד', 'cat': ''},
 {'slug': 'tosafot', 'en': 'Tosafot', 'he': 'תוספות', 'cat': 'authors'},
 {'slug': 'marta-the-daughter-of-boethus',
  'en': 'Marta, the Daughter of Boethus',
  'he': 'מרתא בת בייתוס',
  'cat': ''},
 {'slug': 'shiluach-haken',
  'en': 'Shiluach Haken',
  'he': 'שילוח הקן',
  'cat': 'laws-of-food'},
 {'slug': 'derekh-eretz',
  'en': 'Derekh Eretz',
  'he': 'דרך ארץ',
  'cat': 'human-ethics'},
 {'slug': 'name-pasuk', 'en': 'Name Pasuk', 'he': '', 'cat': ''},
 {'slug': 'yom-tov', 'en': 'Yom Tov', 'he': 'יום טוב', 'cat': ''},
 {'slug': 'mirrors', 'en': 'Mirrors', 'he': 'מראה', 'cat': ''},
 {'slug': 'yalta', 'en': 'Yalta', 'he': 'ילתא', 'cat': ''},
 {'slug': 'rav-rechumi', 'en': 'Rav Rechumi', 'he': 'רב רחומי', 'cat': ''},
 {'slug': 'homes', 'en': 'Homes', 'he': 'בית', 'cat': ''},
 {'slug': 'amen', 'en': 'Amen', 'he': 'אמן', 'cat': 'prayer'},
 {'slug': 'synagogues', 'en': 'Synagogues', 'he': 'בית כנסת', 'cat': ''},
 {'slug': 'sefirot',
  'en': 'Sefirot (Kabbalah)',
  'he': 'ספירות (קבלה)',
  'cat': 'kabbalah'},
 {'slug': 'malkhut1',
  'en': 'Malkhut (Kabbalah)',
  'he': 'מַלְכוּת (קבלה)',
  'cat': 'kabbalah'},
 {'slug': 'bina2',
  'en': 'Bina (Kabbalah)',
  'he': 'בִּינָה (קבלה)',
  'cat': 'kabbalah'},
 {'slug': 'tzimtzum1',
  'en': 'Tzimtzum (Kabbalah)',
  'he': 'צִמְצוּם (קבלה)',
  'cat': 'kabbalah'},
 {'slug': 'ein-sof1',
  'en': 'Ein Sof (Kabbalah)',
  'he': 'אֵין סוֹף (קבלה)',
  'cat': 'kabbalah'},
 {'slug': 'neshama1',
  'en': 'Neshama (Kabbalah)',
  'he': 'נְשָׁמָה (קבלה)',
  'cat': 'kabbalah'},
 {'slug': 'atzilut',
  'en': 'Atzilut (Kabbalah)',
  'he': 'אֲצִילוּת (קבלה)',
  'cat': 'kabbalah'},
 {'slug': 'yom-hashoah', 'en': 'Yom HaShoah', 'he': 'יום השואה', 'cat': ''}];
